In [1191]:
#回帰分析で予測してみるよ_20230909_
#データを作ってみよう

# import pandas as pd
# import numpy as np

#データ編集

# class Num3:
#     def __init__(self):
#         pass
        
        
#     def show(self):
#         pass
        
        
#     if __name__ == '__main__':
#         dataset='/workdir/Num_3_predict/01_output/Num_3_2018_2022.csv'
#         df=pd.read_csv(dataset)
#         print(df)

In [1192]:
#重回帰分析で予測してみるよ_20230909_
#001 フォルダー作成
import os
import pandas as pd # type: ignore
import numpy as np # type: ignore
from sklearn.preprocessing import OneHotEncoder # type: ignore

#docker のときは/workdir/ を追記する
data_dir="Num_4_predict"

input_dir=os.path.join(data_dir,"00_input")
output_dir=os.path.join(data_dir,"01_output")
output_results_dir=os.path.join(data_dir,"02_output_results")
master_dir=os.path.join(data_dir,"03_master")

data_dir_2="Num_4_predict/00_input"
data_dir_3="Num_4_predict/01_output"
all_data_dir=os.path.join(data_dir_2,"001_all_data")
all_data_inital_dir=os.path.join(data_dir_2,"001_all_data_inital")
challenge_1_data=os.path.join(data_dir_3,"Challenge_1")
display(input_dir)

'Num_4_predict\\00_input'

In [1193]:
#002　フォルダー出力
os.makedirs(input_dir,exist_ok=True)
os.makedirs(output_dir,exist_ok=True)
os.makedirs(output_results_dir,exist_ok=True)
os.makedirs(master_dir,exist_ok=True)

os.makedirs(all_data_dir,exist_ok=True)
os.makedirs(all_data_inital_dir,exist_ok=True)

In [1194]:
#003　csv_取得
import glob
# Num_3_file=os.path.join(input_dir,'Num_3_predict/00_input/Num_3_*.csv')
Num_4_file=os.path.join(input_dir,'Num_4_*.csv')
Num_4_paths=glob.glob(Num_4_file)
Num_4_paths=sorted(Num_4_paths)
display(Num_4_paths)

['Num_4_predict\\00_input\\Num_4_2018.csv',
 'Num_4_predict\\00_input\\Num_4_2019.csv',
 'Num_4_predict\\00_input\\Num_4_2020.csv',
 'Num_4_predict\\00_input\\Num_4_2021.csv',
 'Num_4_predict\\00_input\\Num_4_2022.csv',
 'Num_4_predict\\00_input\\Num_4_2023.csv',
 'Num_4_predict\\00_input\\Num_4_2024.csv',
 'Num_4_predict\\00_input\\Num_4_2025.csv',
 'Num_4_predict\\00_input\\Num_4_2026.csv']

In [1195]:
#004 csv_data 呼び出して確認
Num_4_predict_dir=os.path.join(data_dir,'00_input')
Num_4_file='Num_4_2026.csv' #西暦ごとに出力 + #005欠損値も確認
Num_4=pd.read_csv(os.path.join(Num_4_predict_dir,Num_4_file))
display(Num_4.head())

,No,date,Lottery_result,Thousands,hundreds_place,tens_place,ones_place
0,1,2026/1/5,7526,7,5,2,6
1,2,2026/1/6,2300,2,3,0,0
2,3,2026/1/7,7263,7,2,6,3
3,4,2026/1/8,1632,1,6,3,2
4,5,2026/1/9,6551,6,5,5,1

In [1196]:
#005 欠損値の確認---どちらでもOK--- 
Num_4.isnull().sum #Falseは欠損なし

<bound method NDFrame._add_numeric_operations.<locals>.sum of        No   date  Lottery_result  Thousands  hundreds_place  tens_place  \
0   False  False           False      False           False       False
1   False  False           False      False           False       False
2   False  False           False      False           False       False
3   False  False           False      False           False       False
4   False  False           False      False           False       False
5   False  False           False      False           False       False
6   False  False           False      False           False       False
7   False  False           False      False           False       False
8   False  False           False      False           False       False
9   False  False           False      False           False       False
10  False  False           False      False           False       False
11  False  False           False      False           False       False
12  False  False           False      False           False       False
13  False  False           False      False           False       False
14  False  False           False      False           False       False
15  False  False           False      False           False       False
16  False  False           False      False           False       False
17  False  False           False      False           False       False
18  False  False           False      False           False       False
19  False  False           False      False           False       False
20  False  False           False      False           False       False
21  False  False           False      False           False       False
22  False  False           False      False           False       False
23  False  False           False      False           False       False
24  False  False           False      False           False       False
25  False  False           False      False           False       False
26  False  False           False      False           False       False
27  False  False           False      False           False       False
28  False  False           False      False           False       False
29  False  False           False      False           False       False
30  False  False           False      False           False       False
31  False  False           False      False           False       False
32  False  False           False      False           False       False
33  False  False           False      False           False       False
34  False  False           False      False           False       False
35  False  False           False      False           False       False
36  False  False           False      False           False       False
37  False  False           False      False           False       False
38  False  False           False      False           False       False
39  False  False           False      False           False       False
40  False  False           False      False           False       False
41  False  False           False      False           False       False
42  False  False           False      False           False       False
43  False  False           False      False           False       False
44  False  False           False      False           False       False
45  False  False           False      False           False       False
46  False  False           False      False           False       False
47  False  False           False      False           False       False
48  False  False           False      False           False       False
49  False  False           False      False           False       False
50  False  False           False      False           False       False
51  False  False           False      False           False       False
52  False  False           False      False           False       False
53  False  False           False      False           False       False
54  False  False           False      False           False       False
55  False  False           False      False           False       False
56  False  False           False      False           False       False
57  False  False           False      False           False       False

    ones_place
0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
30       False
31       False
32       False
33       False
34       False
35       False
36       False
37       False
38       False
39       False
40       False
41       False
42       False
43       False
44       False
45       False
46       False
47       False
48       False
49       False
50       False
51       False
52       False
53       False
54       False
55       False
56       False
57       False  >

In [1197]:
#006 2018_2023 csvの結合 9年分
import pandas as pd # type: ignore
Num_4_2018_2026=pd.DataFrame()

for file in Num_4_paths:
    Num_4_data=pd.read_csv(file)
    display(f'{file}:{len(Num_4_data)}')
    Num_4_2018_2026=pd.concat([Num_4_2018_2026,Num_4_data],ignore_index=True)

'Num_4_predict\\00_input\\Num_4_2018.csv:257'

'Num_4_predict\\00_input\\Num_4_2019.csv:257'

'Num_4_predict\\00_input\\Num_4_2020.csv:257'

'Num_4_predict\\00_input\\Num_4_2021.csv:259'

'Num_4_predict\\00_input\\Num_4_2022.csv:256'

'Num_4_predict\\00_input\\Num_4_2023.csv:258'

'Num_4_predict\\00_input\\Num_4_2024.csv:258'

'Num_4_predict\\00_input\\Num_4_2025.csv:257'

'Num_4_predict\\00_input\\Num_4_2026.csv:58'

In [1198]:
#007 csvファイル確認
Num_4_2018_2026

,No,date,Lottery_result,Thousands,hundreds_place,tens_place,ones_place
0,1,2018/1/4,5319,5,3,1,9
1,2,2018/1/5,6489,6,4,8,9
2,3,2018/1/8,5346,5,3,4,6
3,4,2018/1/9,9751,9,7,5,1
4,5,2018/1/10,1523,1,5,2,3
...,...,...,...,...,...,...,...
2112,54,2026/3/19,6454,6,4,5,4
2113,55,2026/3/20,9781,9,7,8,1
2114,56,2026/3/23,3851,3,8,5,1
2115,57,2026/3/24,9577,9,5,7,7
2116,58,2026/3/25,5452,5,4,5,2

In [1199]:
#008 ファイルの欠損値確認
Num_4_2018_2026.isnull().sum() #0はなし

No                0
date              0
Lottery_result    0
Thousands         0
hundreds_place    0
tens_place        0
ones_place        0
dtype: int64

In [1200]:
#009 data type 確認
Num_4_2018_2026.dtypes

No                 int64
date              object
Lottery_result     int64
Thousands          int64
hundreds_place     int64
tens_place         int64
ones_place         int64
dtype: object

In [1201]:
#2026/2/24_ここから作成ね

In [1202]:
#010 dateのobject を datetime に変換
import pandas as pd

Num_4_2018_2026['date']=pd.to_datetime(Num_4_2018_2026['date'])

In [1203]:
#011 data type 確認
Num_4_2018_2026.dtypes

No                         int64
date              datetime64[ns]
Lottery_result             int64
Thousands                  int64
hundreds_place             int64
tens_place                 int64
ones_place                 int64
dtype: object

In [1204]:
#ここで"Lottery_result" をint型の変換-----20260322機械側メモリー使用を抑えるため-----
Num_4_2018_2026=Num_4_2018_2026.astype({'Lottery_result': 'int32'})

#ほかの列もint型に変換してみる
Num_4_2018_2026=Num_4_2018_2026.astype({'No': 'int32','Thousands': 'int32', 'hundreds_place': 'int32', 'tens_place': 'int32', 'ones_place': 'int32'})
print(Num_4_2018_2026.dtypes)

No                         int32
date              datetime64[ns]
Lottery_result             int32
Thousands                  int32
hundreds_place             int32
tens_place                 int32
ones_place                 int32
dtype: object

In [1205]:
#012 次回の結果の列を作成 Next_result
#df_add=pd.DataFrame({'Next_result':Num_3_2018_2022.loc[1:1488,'Lottery_result']})#都度、rows=入力する
df_add=pd.DataFrame({'Next_result':Num_4_2018_2026.loc[1::,'Lottery_result']})#2行目から最終行まで
df_add

      Next_result
1            6489
2            5346
3            9751
4            1523
5            5820
...           ...
2112         6454
2113         9781
2114         3851
2115         9577
2116         5452

[2116 rows x 1 columns]

In [1206]:
#ここでの'Next_result'のint型の確認----先にLottery_resultのint型に変換しているので、Next_resultもint型になっているはず-----
print(df_add.dtypes)

#int型をint64からint32へ変換-----20260322機械側メモリー使用を抑えるため-----
# df_add = df_add.astype({'Next_result': 'int32'})
# print(df_add.dtypes)

Next_result    int32
dtype: object

In [1207]:
#013 indexを0から振り直す
df_add=df_add.reset_index()
df_add

      index  Next_result
0         1         6489
1         2         5346
2         3         9751
3         4         1523
4         5         5820
...     ...          ...
2111   2112         6454
2112   2113         9781
2113   2114         3851
2114   2115         9577
2115   2116         5452

[2116 rows x 2 columns]

In [1208]:
#014 不要な列を削除
drop_col=['index']
df_add_1=df_add.drop(drop_col,axis=1)
df_add_1

      Next_result
0            6489
1            5346
2            9751
3            1523
4            5820
...           ...
2111         6454
2112         9781
2113         3851
2114         9577
2115         5452

[2116 rows x 1 columns]

In [1209]:
#015 元データの最後の行を削除
Num_4_2018_2026=Num_4_2018_2026.drop(Num_4_2018_2026.index[-1])#初期_index=[1289]---[-1]は最終行
Num_4_2018_2026

,No,date,Lottery_result,Thousands,hundreds_place,tens_place,ones_place
0,1,2018-01-04,5319,5,3,1,9
1,2,2018-01-05,6489,6,4,8,9
2,3,2018-01-08,5346,5,3,4,6
3,4,2018-01-09,9751,9,7,5,1
4,5,2018-01-10,1523,1,5,2,3
...,...,...,...,...,...,...,...
2111,53,2026-03-18,6449,6,4,4,9
2112,54,2026-03-19,6454,6,4,5,4
2113,55,2026-03-20,9781,9,7,8,1
2114,56,2026-03-23,3851,3,8,5,1
2115,57,2026-03-24,9577,9,5,7,7

In [1210]:
#016 元データとNext_result結合
Num_4_2018_2026 = pd.concat([Num_4_2018_2026, df_add_1], axis=1)
Num_4_2018_2026

,No,date,Lottery_result,Thousands,hundreds_place,tens_place,ones_place,Next_result
0,1,2018-01-04,5319,5,3,1,9,6489
1,2,2018-01-05,6489,6,4,8,9,5346
2,3,2018-01-08,5346,5,3,4,6,9751
3,4,2018-01-09,9751,9,7,5,1,1523
4,5,2018-01-10,1523,1,5,2,3,5820
...,...,...,...,...,...,...,...,...
2111,53,2026-03-18,6449,6,4,4,9,6454
2112,54,2026-03-19,6454,6,4,5,4,9781
2113,55,2026-03-20,9781,9,7,8,1,3851
2114,56,2026-03-23,3851,3,8,5,1,9577
2115,57,2026-03-24,9577,9,5,7,7,5452

In [1211]:
#017 作成したファイルをcsvで出力
#data_file='Num_3_2018_2024.csv'
data_file='Num_4_2018_2026.csv'
Num_4_2018_2026.to_csv(os.path.join(challenge_1_data,data_file),index=False)

In [1212]:
#018 add three を作成→　add fourに更新
df_add=pd.DataFrame({'add_four':Num_4_2018_2026[['Thousands','hundreds_place','tens_place','ones_place']].sum(axis=1)})
df_add

      add_four
0           18
1           27
2           18
3           22
4           11
...        ...
2111        23
2112        19
2113        25
2114        17
2115        28

[2116 rows x 1 columns]

In [1213]:
#019 元データとadd_three結合
Num_4_2018_2026 = pd.concat([Num_4_2018_2026, df_add], axis=1)
Num_4_2018_2026

,No,date,Lottery_result,Thousands,hundreds_place,tens_place,ones_place,Next_result,add_four
0,1,2018-01-04,5319,5,3,1,9,6489,18
1,2,2018-01-05,6489,6,4,8,9,5346,27
2,3,2018-01-08,5346,5,3,4,6,9751,18
3,4,2018-01-09,9751,9,7,5,1,1523,22
4,5,2018-01-10,1523,1,5,2,3,5820,11
...,...,...,...,...,...,...,...,...,...
2111,53,2026-03-18,6449,6,4,4,9,6454,23
2112,54,2026-03-19,6454,6,4,5,4,9781,19
2113,55,2026-03-20,9781,9,7,8,1,3851,25
2114,56,2026-03-23,3851,3,8,5,1,9577,17
2115,57,2026-03-24,9577,9,5,7,7,5452,28

In [1214]:
#020 曜日変数を取得
Num_4_2018_2026['day_of_week']=Num_4_2018_2026['date'].dt.day_of_week
Num_4_2018_2026

,No,date,Lottery_result,Thousands,hundreds_place,tens_place,ones_place,Next_result,add_four,day_of_week
0,1,2018-01-04,5319,5,3,1,9,6489,18,3
1,2,2018-01-05,6489,6,4,8,9,5346,27,4
2,3,2018-01-08,5346,5,3,4,6,9751,18,0
3,4,2018-01-09,9751,9,7,5,1,1523,22,1
4,5,2018-01-10,1523,1,5,2,3,5820,11,2
...,...,...,...,...,...,...,...,...,...,...
2111,53,2026-03-18,6449,6,4,4,9,6454,23,2
2112,54,2026-03-19,6454,6,4,5,4,9781,19,3
2113,55,2026-03-20,9781,9,7,8,1,3851,25,4
2114,56,2026-03-23,3851,3,8,5,1,9577,17,0
2115,57,2026-03-24,9577,9,5,7,7,5452,28,1

In [1215]:
#021 統計量の算出
Num_4_2018_2026.describe()

,No,Lottery_result,Thousands,hundreds_place,tens_place,ones_place,Next_result,add_four,day_of_week
count,2116.000000,2116.000000,2116.000000,2116.000000,2116.000000,2116.000000,2116.000000,2116.000000,2116.000000
mean,126.526938,4907.972590,4.411626,4.465028,4.531191,4.560019,4908.035444,17.967864,1.998110
std,75.178317,2881.267162,2.868305,2.885720,2.940300,2.846538,2881.277583,5.776934,1.415549
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,59.750000,2404.750000,2.000000,2.000000,2.000000,2.000000,2404.750000,14.000000,1.000000
50%,126.000000,4866.500000,4.000000,4.000000,5.000000,5.000000,4866.500000,18.000000,2.000000
75%,192.000000,7337.500000,7.000000,7.000000,7.000000,7.000000,7337.500000,22.000000,3.000000
max,259.000000,9997.000000,9.000000,9.000000,9.000000,9.000000,9997.000000,35.000000,4.000000

In [1216]:
#022 分布グラフの確認__時間かかるからコメントアウト
# import seaborn as sns
# sns.displot(Num_3_2018_2022['Lottery_result'],bins=20,kde=True)
# sns.displot(Num_3_2018_2022['hundreds_place'],bins=10,kde=True)
# sns.displot(Num_3_2018_2022['tens_place'],bins=10,kde=True)
# sns.displot(Num_3_2018_2022['ones_place'],bins=10,kde=True)
# sns.displot(Num_3_2018_2022['day_of_week'],bins=10,kde=True)
# sns.displot(Num_3_2018_2022['add_three'],bins=20,kde=True)#傾向あり

In [1217]:
#023 相関をグラフ確認__時間かかるからコメントアウト
# sns.pairplot(Num_3_2018_2022)

In [1218]:
#024 曜日と曜日の変数と年を取得
Num_4_2018_2026['day_name']=Num_4_2018_2026['date'].dt.day_name() #曜日名
Num_4_2018_2026['year']=Num_4_2018_2026['date'].dt.year
Num_4_2018_2026

,No,date,Lottery_result,Thousands,hundreds_place,tens_place,ones_place,Next_result,add_four,day_of_week,day_name,year
0,1,2018-01-04,5319,5,3,1,9,6489,18,3,Thursday,2018
1,2,2018-01-05,6489,6,4,8,9,5346,27,4,Friday,2018
2,3,2018-01-08,5346,5,3,4,6,9751,18,0,Monday,2018
3,4,2018-01-09,9751,9,7,5,1,1523,22,1,Tuesday,2018
4,5,2018-01-10,1523,1,5,2,3,5820,11,2,Wednesday,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
2111,53,2026-03-18,6449,6,4,4,9,6454,23,2,Wednesday,2026
2112,54,2026-03-19,6454,6,4,5,4,9781,19,3,Thursday,2026
2113,55,2026-03-20,9781,9,7,8,1,3851,25,4,Friday,2026
2114,56,2026-03-23,3851,3,8,5,1,9577,17,0,Monday,2026
2115,57,2026-03-24,9577,9,5,7,7,5452,28,1,Tuesday,2026

In [1219]:
#025 ここで「百+十」結合の列をいれる-----20240506 初期は年も結合して年毎でカウントする作戦を変更-----最後で列は消す-----「+」の列を追加20240713---20240803---
#hundreds+tenの6年のとき異常な数値が頻繁に発生したので戻し検討中-----20240828----- なので年ごとの百の位の出現回数に戻す

Num_4_2018_2026 = pd.DataFrame(Num_4_2018_2026)
# t1 = Num_4_2018_2026['hundreds_place']
t1 = Num_4_2018_2026['Thousands']
t2 = Num_4_2018_2026['year']
# t3 = Num_3_2018_2023['tens_place']

# df_test['hp_year_join'] = t1.astype(str) + t3.astype(str) + t2.astype(str)
# df_test = pd.DataFrame(t1.astype(str) + t3.astype(str), columns=['hundreds+ten'])#カラム名追加
df_test = pd.DataFrame(t1.astype(str) + t2.astype(str), columns=['Thousands+year'])#カラム名追加

df_test

     Thousands+year
0             52018
1             62018
2             52018
3             92018
4             12018
...             ...
2111          62026
2112          62026
2113          92026
2114          32026
2115          92026

[2116 rows x 1 columns]

In [1220]:
#026-----文字型からint型に変更する----
df_test = df_test.astype(int)
df_test

      Thousands+year
0              52018
1              62018
2              52018
3              92018
4              12018
...              ...
2111           62026
2112           62026
2113           92026
2114           32026
2115           92026

[2116 rows x 1 columns]

In [1221]:
#027-----参考で8年間の2桁の出現頻度をカウント--- Max38回だから40回で変数化でいこう-----   20240831--出現回数だけを変数化でいこう-----
# df_test_count = pd.DataFrame({'6year_count': df_test.loc[:,'hundreds+ten'].value_counts()})
df_test_count = pd.DataFrame({'8year_count': df_test.loc[:,'Thousands+year'].value_counts()})

df_test_count

       8year_count
22020           37
52018           36
22023           36
62018           34
12023           33
...            ...
2026             5
82026            4
12026            2
42026            2
52026            2

[90 rows x 1 columns]

In [1222]:
#Test-----ここでhundreds_placeの8年間の出現頻度をカウントを確認-----Max204回だからこのままの数値を変数化、なんだか百の位の出現頻度を同じ変数のようなので保留-----2024/8/31-----
df_test_count_next = pd.DataFrame({'8year_count_next': Num_4_2018_2026.loc[:,'Thousands'].value_counts()})

df_test_count_next

   8year_count_next
2               253
8               219
1               217
5               212
6               210
0               210
3               207
9               197
4               197
7               194

In [1223]:
#028----ここで元データとhundreds+tenを結合-----  20240831----ここで元データとThousands+yearを結合に更新-----
Num_4_2018_2026 = pd.concat([Num_4_2018_2026, df_test], axis=1)
Num_4_2018_2026

,No,date,Lottery_result,Thousands,hundreds_place,tens_place,ones_place,Next_result,add_four,day_of_week,day_name,year,Thousands+year
0,1,2018-01-04,5319,5,3,1,9,6489,18,3,Thursday,2018,52018
1,2,2018-01-05,6489,6,4,8,9,5346,27,4,Friday,2018,62018
2,3,2018-01-08,5346,5,3,4,6,9751,18,0,Monday,2018,52018
3,4,2018-01-09,9751,9,7,5,1,1523,22,1,Tuesday,2018,92018
4,5,2018-01-10,1523,1,5,2,3,5820,11,2,Wednesday,2018,12018
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,53,2026-03-18,6449,6,4,4,9,6454,23,2,Wednesday,2026,62026
2112,54,2026-03-19,6454,6,4,5,4,9781,19,3,Thursday,2026,62026
2113,55,2026-03-20,9781,9,7,8,1,3851,25,4,Friday,2026,92026
2114,56,2026-03-23,3851,3,8,5,1,9577,17,0,Monday,2026,32026
2115,57,2026-03-24,9577,9,5,7,7,5452,28,1,Tuesday,2026,92026

In [1224]:
#029-----hundreds+ten　を取得して新しい出現回数列追加_2桁(twodigits)のカウンターを追加20240803-----　20240831-----hundreds+yearの出現回数へ戻す-----

import collections
# list_num = Num_3_2018_2023['hundreds+ten']
list_num = Num_4_2018_2026['Thousands+year']

df1=collections.Counter(list_num)

# new_column = [df1[item] for item in Num_3_2018_2023['hundreds+ten'].tolist()]
new_column = [df1[item] for item in Num_4_2018_2026['Thousands+year'].tolist()]
Num_4_2018_2026['td_ct'] = new_column
Num_4_2018_2026

,No,date,Lottery_result,Thousands,hundreds_place,tens_place,ones_place,Next_result,add_four,day_of_week,day_name,year,Thousands+year,td_ct
0,1,2018-01-04,5319,5,3,1,9,6489,18,3,Thursday,2018,52018,36
1,2,2018-01-05,6489,6,4,8,9,5346,27,4,Friday,2018,62018,34
2,3,2018-01-08,5346,5,3,4,6,9751,18,0,Monday,2018,52018,36
3,4,2018-01-09,9751,9,7,5,1,1523,22,1,Tuesday,2018,92018,18
4,5,2018-01-10,1523,1,5,2,3,5820,11,2,Wednesday,2018,12018,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,53,2026-03-18,6449,6,4,4,9,6454,23,2,Wednesday,2026,62026,10
2112,54,2026-03-19,6454,6,4,5,4,9781,19,3,Thursday,2026,62026,10
2113,55,2026-03-20,9781,9,7,8,1,3851,25,4,Friday,2026,92026,9
2114,56,2026-03-23,3851,3,8,5,1,9577,17,0,Monday,2026,32026,8
2115,57,2026-03-24,9577,9,5,7,7,5452,28,1,Tuesday,2026,92026,9

In [1225]:
#030-----td_ctをダミー変数化35回で-----40回へ更新

import os
import pandas as pd # type: ignore
import numpy as np # type: ignore
from sklearn.preprocessing import OneHotEncoder # type: ignore

df_n=range(0,41,1)

counter_list=df_n
enc=OneHotEncoder(categories=[counter_list],sparse_output=False)
counter_d=enc.fit_transform(Num_4_2018_2026[['td_ct']])
df_counter_td=pd.DataFrame(counter_d,index=Num_4_2018_2026.index,columns=counter_list,dtype='int')

df_counter_td

#警告コメントは将来非推奨になるので注意ということ→ 20251231_sparse=False から sparse_output=False に変更

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2112,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2113,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2114,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2115,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [1226]:
#031-----Namberのカラム名の変更twodigit_count----初期は直接記載したけど増えたので一括処理に更新-----hundreds+yearに更新

for i in range(41):
        name=('td_ct' + str(i))
   
        df_counter_td = df_counter_td.rename(columns={i: name})
        
df_counter_td

,td_ct0,td_ct1,td_ct2,td_ct3,td_ct4,td_ct5,td_ct6,td_ct7,td_ct8,td_ct9,...,td_ct31,td_ct32,td_ct33,td_ct34,td_ct35,td_ct36,td_ct37,td_ct38,td_ct39,td_ct40
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2112,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2113,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2114,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2115,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [1227]:
#032-----元データとhundred+ten の　td_ct　ダミー変数を結合-----
Num_4_2018_2026 = pd.concat([Num_4_2018_2026, df_counter_td], axis=1)
Num_4_2018_2026

,No,date,Lottery_result,Thousands,hundreds_place,tens_place,ones_place,Next_result,add_four,day_of_week,...,td_ct31,td_ct32,td_ct33,td_ct34,td_ct35,td_ct36,td_ct37,td_ct38,td_ct39,td_ct40
0,1,2018-01-04,5319,5,3,1,9,6489,18,3,...,0,0,0,0,0,1,0,0,0,0
1,2,2018-01-05,6489,6,4,8,9,5346,27,4,...,0,0,0,1,0,0,0,0,0,0
2,3,2018-01-08,5346,5,3,4,6,9751,18,0,...,0,0,0,0,0,1,0,0,0,0
3,4,2018-01-09,9751,9,7,5,1,1523,22,1,...,0,0,0,0,0,0,0,0,0,0
4,5,2018-01-10,1523,1,5,2,3,5820,11,2,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,53,2026-03-18,6449,6,4,4,9,6454,23,2,...,0,0,0,0,0,0,0,0,0,0
2112,54,2026-03-19,6454,6,4,5,4,9781,19,3,...,0,0,0,0,0,0,0,0,0,0
2113,55,2026-03-20,9781,9,7,8,1,3851,25,4,...,0,0,0,0,0,0,0,0,0,0
2114,56,2026-03-23,3851,3,8,5,1,9577,17,0,...,0,0,0,0,0,0,0,0,0,0
2115,57,2026-03-24,9577,9,5,7,7,5452,28,1,...,0,0,0,0,0,0,0,0,0,0

In [1228]:
#033 8年間の出現頻度をカウント-----Namberの数を知る
df_add=pd.DataFrame({'8year_ago':Num_4_2018_2026.loc[:,'Lottery_result'].value_counts()})
df_add

      8year_ago
4208          3
2057          3
1610          3
1540          3
17            3
...         ...
256           1
2024          1
5010          1
8722          1
9577          1

[1913 rows x 1 columns]

In [1229]:
#034 8年間のdataをカウント
df_add=pd.DataFrame({'year_data':Num_4_2018_2026.loc[:,'year'].value_counts()})
df_add

      year_data
2024        259
2021        259
2023        258
2018        257
2019        257
2025        257
2020        256
2022        256
2026         57

In [1230]:
#035 8年間の3桁数字の頻度をカウント__Namberの数を知る
df_add_0=pd.DataFrame({'2018_ago':Num_4_2018_2026.loc[0:257,'Lottery_result'].value_counts()})#+257
df_add_1=pd.DataFrame({'2019_ago':Num_4_2018_2026.loc[258:515,'Lottery_result'].value_counts()})#258+257=515
df_add_2=pd.DataFrame({'2020_ago':Num_4_2018_2026.loc[516:772,'Lottery_result'].value_counts()})#516+256=772
df_add_3=pd.DataFrame({'2021_ago':Num_4_2018_2026.loc[773:1032,'Lottery_result'].value_counts()})#773+259=1032
df_add_4=pd.DataFrame({'2022_ago':Num_4_2018_2026.loc[1033:1289,'Lottery_result'].value_counts()})#1033+256=1289
df_add_5=pd.DataFrame({'2023_ago':Num_4_2018_2026.loc[1290:1548,'Lottery_result'].value_counts()})#1290+258=1548

# df_add_5=pd.DataFrame({'2023_ago':Num_3_2018_2022.loc[1290:1487,'Lottery_result'].value_counts()})#行数を更新する
df_add_6=pd.DataFrame({'2024_ago':Num_4_2018_2026.loc[1549:1808,'Lottery_result'].value_counts()})#1290行～最終行までに更新　→1549+259=1808
df_add_7=pd.DataFrame({'2025_ago':Num_4_2018_2026.loc[1809:2066,'Lottery_result'].value_counts()})#1808行～最終行までに更新 →1809+257=2066
df_add_8=pd.DataFrame({'2026_ago':Num_4_2018_2026.loc[2067::,'Lottery_result'].value_counts()})#2066行～最終行までに更新

print(df_add_0)
print(df_add_1)
print(df_add_2)
print(df_add_3)
print(df_add_4)
print(df_add_5)
print(df_add_6)
print(df_add_7)
print(df_add_8)

      2018_ago
8323         2
621          2
8823         2
3501         2
7005         1
...        ...
8659         1
6485         1
6515         1
1143         1
5939         1

[254 rows x 1 columns]
      2019_ago
7632         2
7206         2
8719         2
8447         2
4945         2
...        ...
4143         1
4388         1
9254         1
5090         1
6143         1

[253 rows x 1 columns]
      2020_ago
6591         2
4198         1
6653         1
7738         1
8063         1
...        ...
9011         1
7471         1
6531         1
6845         1
1530         1

[256 rows x 1 columns]
      2021_ago
3193         2
9613         2
1275         2
4594         2
5711         2
...        ...
5039         1
1790         1
1482         1
6075         1
6768         1

[255 rows x 1 columns]
      2022_ago
2334         2
2057         2
8432         2
3703         1
2808         1
...        ...
3272         1
6801         1
7574         1
6575         1
395          1

[254 rows x 1 columns]
      2023_ago
1308         2
7211         2
4608         1
402          1
6372         1
...        ...
9262         1
8990         1
7143         1
9826         1
7124         1

[257 rows x 1 columns]
      2024_ago
9214         1
2390         1
1491         1
9909         1
205          1
...        ...
1380         1
8588         1
4677         1
8006         1
135          1

[260 rows x 1 columns]
      2025_ago
7263         2
1366         1
774          1
549          1
538          1
...        ...
9899         1
2718         1
9115         1
3697         1
2404         1

[257 rows x 1 columns]
      2026_ago
8060         1
9166         1
2476         1
9508         1
1918         1
3099         1
2586         1
7626         1
9087         1
8404         1
2852         1
7592         1
4819         1
2631         1
6092         1
9420         1
247          1
3421         1
2295         1
6449         1
6454         1
9781         1
3851         1
3115         1
8440         1
6436         1
505          1
8174         1
9534         1
615          1
6022         1
515          1
176          1
7964         1
4588         1
6120         1
9827         1
9945         1
3727         1
3834         1
5517         1
6403         1
3798         1
3395         1
7896         1
5004         1
6376         1
6978         1
9577         1

In [1231]:
#036-----参考_8年間の百位の頻度をカウント__hundreds_placeの数を知る_2024/3/9
df_add_h0=pd.DataFrame({'2018_ago':Num_4_2018_2026.loc[0:257,'hundreds_place'].value_counts()})
df_add_h1=pd.DataFrame({'2019_ago':Num_4_2018_2026.loc[258:515,'hundreds_place'].value_counts()})
df_add_h2=pd.DataFrame({'2020_ago':Num_4_2018_2026.loc[516:772,'hundreds_place'].value_counts()})
df_add_h3=pd.DataFrame({'2021_ago':Num_4_2018_2026.loc[773:1032,'hundreds_place'].value_counts()})
df_add_h4=pd.DataFrame({'2022_ago':Num_4_2018_2026.loc[1033:1289,'hundreds_place'].value_counts()})
df_add_h5=pd.DataFrame({'2023_ago':Num_4_2018_2026.loc[1290:1548,'hundreds_place'].value_counts()})

# df_add_5=pd.DataFrame({'2023_ago':Num_3_2018_2022.loc[1290:1487,'Lottery_result'].value_counts()})#行数を更新する
df_add_h6=pd.DataFrame({'2024_ago':Num_4_2018_2026.loc[1549:1808,'hundreds_place'].value_counts()})#1290行～最終行までに更新　→1549+259=1808
df_add_h7=pd.DataFrame({'2025_ago':Num_4_2018_2026.loc[1809:2066,'hundreds_place'].value_counts()})#1808行～最終行までに更新 →1809+257=2066
df_add_h8=pd.DataFrame({'2026_ago':Num_4_2018_2026.loc[2067::,'hundreds_place'].value_counts()})#2067行～最終行までに更新

print(df_add_h0)
print(df_add_h1)
print(df_add_h2)
print(df_add_h3)
print(df_add_h4)
print(df_add_h5)
print(df_add_h6)
print(df_add_h7)
print(df_add_h8)

   2018_ago
1        32
8        31
6        30
3        29
9        28
5        27
0        26
4        21
7        20
2        14
   2019_ago
0        31
5        31
2        28
7        28
6        27
1        27
3        27
9        21
4        20
8        18
   2020_ago
4        33
8        29
7        29
0        28
9        27
5        25
1        23
6        22
2        22
3        19
   2021_ago
7        31
1        30
8        30
9        27
5        27
6        26
0        24
2        24
4        21
3        20
   2022_ago
3        34
0        29
9        27
5        27
8        26
7        26
6        23
1        23
4        21
2        21
   2023_ago
1        35
2        31
3        29
4        28
9        27
7        23
5        23
0        22
6        21
8        20
   2024_ago
2        32
6        30
0        28
3        28
1        27
9        24
5        24
8        23
7        22
4        22
   2025_ago
3        36
8        32
1        28
7        27
2        26
4        25
9        24
5        21
6        20
0        19
   2026_ago
4         9
5         9
0         6
8         6
1         5
9         4
6         3
7         3
3         2
2         2

In [1232]:
#037----- Nambarの出現をダミー変数化する基本的な構文
df=range(0,10000,1)
# Num_list=pd.DataFrame(columns=df,dtype='int')
Num_list=df
enc=OneHotEncoder(categories=[Num_list],sparse_output=False)
Num_d=enc.fit_transform(Num_4_2018_2026[['Lottery_result']])
df_Num=pd.DataFrame(Num_d,index=Num_4_2018_2026.index,columns=Num_list,dtype='int')
df_Num

#警告コメントは将来非推奨になるので注意ということ→ 20251231_sparse=False から sparse_output=False に変更

,0,1,2,3,4,5,6,7,8,9,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2112,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2113,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2114,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2115,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [1233]:
#038----- Numberのカラム名取得
df=df_Num.columns.values
df

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

In [1234]:
#ここでリスト化のテスト中-----20260306-----数秒で完了速い様子みる

new_names = [f'num_{i}' for i in df_Num]
new_names

['num_0',
 'num_1',
 'num_2',
 'num_3',
 'num_4',
 'num_5',
 'num_6',
 'num_7',
 'num_8',
 'num_9',
 'num_10',
 'num_11',
 'num_12',
 'num_13',
 'num_14',
 'num_15',
 'num_16',
 'num_17',
 'num_18',
 'num_19',
 'num_20',
 'num_21',
 'num_22',
 'num_23',
 'num_24',
 'num_25',
 'num_26',
 'num_27',
 'num_28',
 'num_29',
 'num_30',
 'num_31',
 'num_32',
 'num_33',
 'num_34',
 'num_35',
 'num_36',
 'num_37',
 'num_38',
 'num_39',
 'num_40',
 'num_41',
 'num_42',
 'num_43',
 'num_44',
 'num_45',
 'num_46',
 'num_47',
 'num_48',
 'num_49',
 'num_50',
 'num_51',
 'num_52',
 'num_53',
 'num_54',
 'num_55',
 'num_56',
 'num_57',
 'num_58',
 'num_59',
 'num_60',
 'num_61',
 'num_62',
 'num_63',
 'num_64',
 'num_65',
 'num_66',
 'num_67',
 'num_68',
 'num_69',
 'num_70',
 'num_71',
 'num_72',
 'num_73',
 'num_74',
 'num_75',
 'num_76',
 'num_77',
 'num_78',
 'num_79',
 'num_80',
 'num_81',
 'num_82',
 'num_83',
 'num_84',
 'num_85',
 'num_86',
 'num_87',
 'num_88',
 'num_89',
 'num_90',
 'num_91',
 'num_92',
 'num_93',
 'num_94',
 'num_95',
 'num_96',
 'num_97',
 'num_98',
 'num_99',
 'num_100',
 'num_101',
 'num_102',
 'num_103',
 'num_104',
 'num_105',
 'num_106',
 'num_107',
 'num_108',
 'num_109',
 'num_110',
 'num_111',
 'num_112',
 'num_113',
 'num_114',
 'num_115',
 'num_116',
 'num_117',
 'num_118',
 'num_119',
 'num_120',
 'num_121',
 'num_122',
 'num_123',
 'num_124',
 'num_125',
 'num_126',
 'num_127',
 'num_128',
 'num_129',
 'num_130',
 'num_131',
 'num_132',
 'num_133',
 'num_134',
 'num_135',
 'num_136',
 'num_137',
 'num_138',
 'num_139',
 'num_140',
 'num_141',
 'num_142',
 'num_143',
 'num_144',
 'num_145',
 'num_146',
 'num_147',
 'num_148',
 'num_149',
 'num_150',
 'num_151',
 'num_152',
 'num_153',
 'num_154',
 'num_155',
 'num_156',
 'num_157',
 'num_158',
 'num_159',
 'num_160',
 'num_161',
 'num_162',
 'num_163',
 'num_164',
 'num_165',
 'num_166',
 'num_167',
 'num_168',
 'num_169',
 'num_170',
 'num_171',
 'num_172',
 'num_173',
 'num_174',
 'num_175',
 'num_176',
 'num_177',
 'num_178',
 'num_179',
 'num_180',
 'num_181',
 'num_182',
 'num_183',
 'num_184',
 'num_185',
 'num_186',
 'num_187',
 'num_188',
 'num_189',
 'num_190',
 'num_191',
 'num_192',
 'num_193',
 'num_194',
 'num_195',
 'num_196',
 'num_197',
 'num_198',
 'num_199',
 'num_200',
 'num_201',
 'num_202',
 'num_203',
 'num_204',
 'num_205',
 'num_206',
 'num_207',
 'num_208',
 'num_209',
 'num_210',
 'num_211',
 'num_212',
 'num_213',
 'num_214',
 'num_215',
 'num_216',
 'num_217',
 'num_218',
 'num_219',
 'num_220',
 'num_221',
 'num_222',
 'num_223',
 'num_224',
 'num_225',
 'num_226',
 'num_227',
 'num_228',
 'num_229',
 'num_230',
 'num_231',
 'num_232',
 'num_233',
 'num_234',
 'num_235',
 'num_236',
 'num_237',
 'num_238',
 'num_239',
 'num_240',
 'num_241',
 'num_242',
 'num_243',
 'num_244',
 'num_245',
 'num_246',
 'num_247',
 'num_248',
 'num_249',
 'num_250',
 'num_251',
 'num_252',
 'num_253',
 'num_254',
 'num_255',
 'num_256',
 'num_257',
 'num_258',
 'num_259',
 'num_260',
 'num_261',
 'num_262',
 'num_263',
 'num_264',
 'num_265',
 'num_266',
 'num_267',
 'num_268',
 'num_269',
 'num_270',
 'num_271',
 'num_272',
 'num_273',
 'num_274',
 'num_275',
 'num_276',
 'num_277',
 'num_278',
 'num_279',
 'num_280',
 'num_281',
 'num_282',
 'num_283',
 'num_284',
 'num_285',
 'num_286',
 'num_287',
 'num_288',
 'num_289',
 'num_290',
 'num_291',
 'num_292',
 'num_293',
 'num_294',
 'num_295',
 'num_296',
 'num_297',
 'num_298',
 'num_299',
 'num_300',
 'num_301',
 'num_302',
 'num_303',
 'num_304',
 'num_305',
 'num_306',
 'num_307',
 'num_308',
 'num_309',
 'num_310',
 'num_311',
 'num_312',
 'num_313',
 'num_314',
 'num_315',
 'num_316',
 'num_317',
 'num_318',
 'num_319',
 'num_320',
 'num_321',
 'num_322',
 'num_323',
 'num_324',
 'num_325',
 'num_326',
 'num_327',
 'num_328',
 'num_329',
 'num_330',
 'num_331',
 'num_332',
 'num_333',
 'num_334',
 'num_335',
 'num_336',
 'num_337',
 'num_338',
 'num_339',
 'num_340',
 'num_341',
 'num_342',
 'num_343',
 'num_344',
 'num_345',
 'num_346',
 'num_347',
 'num_348',
 'num_349',
 'num_350',
 'num_351',
 'num_352',
 'num_353',
 'num_354',
 'num_355',
 'num_356',
 'num_357',
 'num_358',
 'num_359',
 'num_360',
 'num_361',
 'num_362',
 'num_363',
 'num_364',
 'num_365',
 'num_366',
 'num_367',
 'num_368',
 'num_369',
 'num_370',
 'num_371',
 'num_372',
 'num_373',
 'num_374',
 'num_375',
 'num_376',
 'num_377',
 'num_378',
 'num_379',
 'num_380',
 'num_381',
 'num_382',
 'num_383',
 'num_384',
 'num_385',
 'num_386',
 'num_387',
 'num_388',
 'num_389',
 'num_390',
 'num_391',
 'num_392',
 'num_393',
 'num_394',
 'num_395',
 'num_396',
 'num_397',
 'num_398',
 'num_399',
 'num_400',
 'num_401',
 'num_402',
 'num_403',
 'num_404',
 'num_405',
 'num_406',
 'num_407',
 'num_408',
 'num_409',
 'num_410',
 'num_411',
 'num_412',
 'num_413',
 'num_414',
 'num_415',
 'num_416',
 'num_417',
 'num_418',
 'num_419',
 'num_420',
 'num_421',
 'num_422',
 'num_423',
 'num_424',
 'num_425',
 'num_426',
 'num_427',
 'num_428',
 'num_429',
 'num_430',
 'num_431',
 'num_432',
 'num_433',
 'num_434',
 'num_435',
 'num_436',
 'num_437',
 'num_438',
 'num_439',
 'num_440',
 'num_441',
 'num_442',
 'num_443',
 'num_444',
 'num_445',
 'num_446',
 'num_447',
 'num_448',
 'num_449',
 'num_450',
 'num_451',
 'num_452',
 'num_453',
 'num_454',
 'num_455',
 'num_456',
 'num_457',
 'num_458',
 'num_459',
 'num_460',
 'num_461',
 'num_462',
 'num_463',
 'num_464',
 'num_465',
 'num_466',
 'num_467',
 'num_468',
 'num_469',
 'num_470',
 'num_471',
 'num_472',
 'num_473',
 'num_474',
 'num_475',
 'num_476',
 'num_477',
 'num_478',
 'num_479',
 'num_480',
 'num_481',
 'num_482',
 'num_483',
 'num_484',
 'num_485',
 'num_486',
 'num_487',
 'num_488',
 'num_489',
 'num_490',
 'num_491',
 'num_492',
 'num_493',
 'num_494',
 'num_495',
 'num_496',
 'num_497',
 'num_498',
 'num_499',
 'num_500',
 'num_501',
 'num_502',
 'num_503',
 'num_504',
 'num_505',
 'num_506',
 'num_507',
 'num_508',
 'num_509',
 'num_510',
 'num_511',
 'num_512',
 'num_513',
 'num_514',
 'num_515',
 'num_516',
 'num_517',
 'num_518',
 'num_519',
 'num_520',
 'num_521',
 'num_522',
 'num_523',
 'num_524',
 'num_525',
 'num_526',
 'num_527',
 'num_528',
 'num_529',
 'num_530',
 'num_531',
 'num_532',
 'num_533',
 'num_534',
 'num_535',
 'num_536',
 'num_537',
 'num_538',
 'num_539',
 'num_540',
 'num_541',
 'num_542',
 'num_543',
 'num_544',
 'num_545',
 'num_546',
 'num_547',
 'num_548',
 'num_549',
 'num_550',
 'num_551',
 'num_552',
 'num_553',
 'num_554',
 'num_555',
 'num_556',
 'num_557',
 'num_558',
 'num_559',
 'num_560',
 'num_561',
 'num_562',
 'num_563',
 'num_564',
 'num_565',
 'num_566',
 'num_567',
 'num_568',
 'num_569',
 'num_570',
 'num_571',
 'num_572',
 'num_573',
 'num_574',
 'num_575',
 'num_576',
 'num_577',
 'num_578',
 'num_579',
 'num_580',
 'num_581',
 'num_582',
 'num_583',
 'num_584',
 'num_585',
 'num_586',
 'num_587',
 'num_588',
 'num_589',
 'num_590',
 'num_591',
 'num_592',
 'num_593',
 'num_594',
 'num_595',
 'num_596',
 'num_597',
 'num_598',
 'num_599',
 'num_600',
 'num_601',
 'num_602',
 'num_603',
 'num_604',
 'num_605',
 'num_606',
 'num_607',
 'num_608',
 'num_609',
 'num_610',
 'num_611',
 'num_612',
 'num_613',
 'num_614',
 'num_615',
 'num_616',
 'num_617',
 'num_618',
 'num_619',
 'num_620',
 'num_621',
 'num_622',
 'num_623',
 'num_624',
 'num_625',
 'num_626',
 'num_627',
 'num_628',
 'num_629',
 'num_630',
 'num_631',
 'num_632',
 'num_633',
 'num_634',
 'num_635',
 'num_636',
 'num_637',
 'num_638',
 'num_639',
 'num_640',
 'num_641',
 'num_642',
 'num_643',
 'num_644',
 'num_645',
 'num_646',
 'num_647',
 'num_648',
 'num_649',
 'num_650',
 'num_651',
 'num_652',
 'num_653',
 'num_654',
 'num_655',
 'num_656',
 'num_657',
 'num_658',
 'num_659',
 'num_660',
 'num_661',
 'num_662',
 'num_663',
 'num_664',
 'num_665',
 'num_666',
 'num_667',
 'num_668',
 'num_669',
 'num_670',
 'num_671',
 'num_672',
 'num_673',
 'num_674',
 'num_675',
 'num_676',
 'num_677',
 'num_678',
 'num_679',
 'num_680',
 'num_681',
 'num_682',
 'num_683',
 'num_684',
 'num_685',
 'num_686',
 'num_687',
 'num_688',
 'num_689',
 'num_690',
 'num_691',
 'num_692',
 'num_693',
 'num_694',
 'num_695',
 'num_696',
 'num_697',
 'num_698',
 'num_699',
 'num_700',
 'num_701',
 'num_702',
 'num_703',
 'num_704',
 'num_705',
 'num_706',
 'num_707',
 'num_708',
 'num_709',
 'num_710',
 'num_711',
 'num_712',
 'num_713',
 'num_714',
 'num_715',
 'num_716',
 'num_717',
 'num_718',
 'num_719',
 'num_720',
 'num_721',
 'num_722',
 'num_723',
 'num_724',
 'num_725',
 'num_726',
 'num_727',
 'num_728',
 'num_729',
 'num_730',
 'num_731',
 'num_732',
 'num_733',
 'num_734',
 'num_735',
 'num_736',
 'num_737',
 'num_738',
 'num_739',
 'num_740',
 'num_741',
 'num_742',
 'num_743',
 'num_744',
 'num_745',
 'num_746',
 'num_747',
 'num_748',
 'num_749',
 'num_750',
 'num_751',
 'num_752',
 'num_753',
 'num_754',
 'num_755',
 'num_756',
 'num_757',
 'num_758',
 'num_759',
 'num_760',
 'num_761',
 'num_762',
 'num_763',
 'num_764',
 'num_765',
 'num_766',
 'num_767',
 'num_768',
 'num_769',
 'num_770',
 'num_771',
 'num_772',
 'num_773',
 'num_774',
 'num_775',
 'num_776',
 'num_777',
 'num_778',
 'num_779',
 'num_780',
 'num_781',
 'num_782',
 'num_783',
 'num_784',
 'num_785',
 'num_786',
 'num_787',
 'num_788',
 'num_789',
 'num_790',
 'num_791',
 'num_792',
 'num_793',
 'num_794',
 'num_795',
 'num_796',
 'num_797',
 'num_798',
 'num_799',
 'num_800',
 'num_801',
 'num_802',
 'num_803',
 'num_804',
 'num_805',
 'num_806',
 'num_807',
 'num_808',
 'num_809',
 'num_810',
 'num_811',
 'num_812',
 'num_813',
 'num_814',
 'num_815',
 'num_816',
 'num_817',
 'num_818',
 'num_819',
 'num_820',
 'num_821',
 'num_822',
 'num_823',
 'num_824',
 'num_825',
 'num_826',
 'num_827',
 'num_828',
 'num_829',
 'num_830',
 'num_831',
 'num_832',
 'num_833',
 'num_834',
 'num_835',
 'num_836',
 'num_837',
 'num_838',
 'num_839',
 'num_840',
 'num_841',
 'num_842',
 'num_843',
 'num_844',
 'num_845',
 'num_846',
 'num_847',
 'num_848',
 'num_849',
 'num_850',
 'num_851',
 'num_852',
 'num_853',
 'num_854',
 'num_855',
 'num_856',
 'num_857',
 'num_858',
 'num_859',
 'num_860',
 'num_861',
 'num_862',
 'num_863',
 'num_864',
 'num_865',
 'num_866',
 'num_867',
 'num_868',
 'num_869',
 'num_870',
 'num_871',
 'num_872',
 'num_873',
 'num_874',
 'num_875',
 'num_876',
 'num_877',
 'num_878',
 'num_879',
 'num_880',
 'num_881',
 'num_882',
 'num_883',
 'num_884',
 'num_885',
 'num_886',
 'num_887',
 'num_888',
 'num_889',
 'num_890',
 'num_891',
 'num_892',
 'num_893',
 'num_894',
 'num_895',
 'num_896',
 'num_897',
 'num_898',
 'num_899',
 'num_900',
 'num_901',
 'num_902',
 'num_903',
 'num_904',
 'num_905',
 'num_906',
 'num_907',
 'num_908',
 'num_909',
 'num_910',
 'num_911',
 'num_912',
 'num_913',
 'num_914',
 'num_915',
 'num_916',
 'num_917',
 'num_918',
 'num_919',
 'num_920',
 'num_921',
 'num_922',
 'num_923',
 'num_924',
 'num_925',
 'num_926',
 'num_927',
 'num_928',
 'num_929',
 'num_930',
 'num_931',
 'num_932',
 'num_933',
 'num_934',
 'num_935',
 'num_936',
 'num_937',
 'num_938',
 'num_939',
 'num_940',
 'num_941',
 'num_942',
 'num_943',
 'num_944',
 'num_945',
 'num_946',
 'num_947',
 'num_948',
 'num_949',
 'num_950',
 'num_951',
 'num_952',
 'num_953',
 'num_954',
 'num_955',
 'num_956',
 'num_957',
 'num_958',
 'num_959',
 'num_960',
 'num_961',
 'num_962',
 'num_963',
 'num_964',
 'num_965',
 'num_966',
 'num_967',
 'num_968',
 'num_969',
 'num_970',
 'num_971',
 'num_972',
 'num_973',
 'num_974',
 'num_975',
 'num_976',
 'num_977',
 'num_978',
 'num_979',
 'num_980',
 'num_981',
 'num_982',
 'num_983',
 'num_984',
 'num_985',
 'num_986',
 'num_987',
 'num_988',
 'num_989',
 'num_990',
 'num_991',
 'num_992',
 'num_993',
 'num_994',
 'num_995',
 'num_996',
 'num_997',
 'num_998',
 'num_999',
 ...]

In [1235]:
#----- カラム名を確認-----

df_Num.columns = new_names
df_Num

,num_0,num_1,num_2,num_3,num_4,num_5,num_6,num_7,num_8,num_9,...,num_9990,num_9991,num_9992,num_9993,num_9994,num_9995,num_9996,num_9997,num_9998,num_9999
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2112,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2113,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2114,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2115,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [1236]:
# 空き

In [1237]:
#039----- Namberのカラム名の変更----初期は直接記載したけど増えたので一括処理に更新

#１万列あるとループ処理で5分必要のため上のcodeで処理のテスト中2026/3/6
###########-----------
# for i in range(10000):
#         name=('num_' + str(i))
   
#         df_Num = df_Num.rename(columns={i: name})
        
# df_Num
###########-----------

# df=df_Num.rename(columns={0:'num_0',1:'num_1',2:'num_2',3:'num_3',4:'num_4',5:'num_5',6:'num_6',7:'num_7',8:'num_8',9:'num_9',10:'num_10',
#                           11:'num_11',12:'num_12',13:'num_13',14:'num_14',15:'num_15',16:'num_16',17:'num_17',18:'num_18',19:'num_19',20:'num_20',
#                           21:'num_21',22:'num_22',23:'num_23',24:'num_24',25:'num_25',26:'num_26',27:'num_27',28:'num_28',29:'num_29',30:'num_30',
#                           31:'num_31',32:'num_32',33:'num_33',34:'num_34',35:'num_34',36:'num_36',37:'num_37',38:'num_38',39:'num_39',40:'num_40',
#                           41:'num_41',42:'num_42',43:'num_43',44:'num_44',45:'num_45',46:'num_46',47:'num_47',48:'num_48',49:'num_49',50:'num_50',
#                           51:'num_51',52:'num_52',53:'num_0',54:'num_0',55:'num_0',56:'num_0',57:'num_0',58:'num_0',59:'num_0',60:'num_60',
#                           61:'num_61',62:'num_62',63:'num_63',64:'num_64',65:'num_65',66:'num_66',67:'num_67',68:'num_68',69:'num_69',70:'num_70',
#                           71:'num_71',72:'num_72',73:'num_0',74:'num_74',75:'num_75',76:'num_76',77:'num_77',78:'num_78',79:'num_79',80:'num_80',
#                           81:'num_81',82:'num_82',83:'num_83',84:'num_84',85:'num_85',86:'num_86',87:'num_87',88:'num_88',89:'num_89',90:'num_90',
#                           91:'num_91',92:'num_92',93:'num_93',94:'num_94',95:'num_95',96:'num_96',97:'num_97',98:'num_98',99:'num_0',100:'num_100',
#                           101:'num_100',102:'num_100',103:'num_100',104:'num_100',105:'num_100',106:'num_100',107:'num_100',108:'num_100',109:'num_100',110:'num_100',
#                           111:'num_111',112:'num_112',113:'num_113',114:'num_114',115:'num_115',116:'num_116',117:'num_117',118:'num_118',119:'num_119',120:'num_120',
#                           121:'num_121',122:'num_122',123:'num_123',124:'num_124',125:'num_125',126:'num_126',127:'num_127',128:'num_128',129:'num_129',130:'num_130',
#                           131:'num_131',132:'num_132',133:'num_133',134:'num_134',135:'num_134',136:'num_136',137:'num_137',138:'num_138',139:'num_139',140:'num_140',
#                           141:'num_141',142:'num_142',143:'num_143',144:'num_144',145:'num_145',146:'num_146',147:'num_147',148:'num_148',149:'num_149',150:'num_150',
#                           151:'num_151',152:'num_152',153:'num_153',154:'num_154',155:'num_155',156:'num_156',157:'num_157',158:'num_158',159:'num_159',160:'num_160',
#                           161:'num_161',162:'num_162',163:'num_163',164:'num_164',165:'num_165',166:'num_166',167:'num_167',168:'num_168',169:'num_169',170:'num_170',
#                           171:'num_171',172:'num_172',173:'num_173',174:'num_714',175:'num_175',176:'num_176',177:'num_177',178:'num_178',179:'num_179',180:'num_180',
#                           181:'num_181',182:'num_182',183:'num_183',84:'num_184',185:'num_185',186:'num_186',187:'num_187',188:'num_188',189:'num_189',190:'num_190',
#                           191:'num_191',192:'num_192',193:'num_193',194:'num_194',195:'num_195',196:'num_196',197:'num_197',198:'num_198',199:'num_199',200:'num_200',
#                           201:'num_201',202:'num_202',203:'num_203',204:'num_204',205:'num_205',206:'num_206',207:'num_207',208:'num_208',209:'num_209',210:'num_210',


#                  991, 992, 993, 994, 995, 996, 997, 998, 999})
# df

In [1238]:
#040----- カラム名を確認
df=df_Num.columns.values
df

array(['num_0', 'num_1', 'num_2', ..., 'num_9997', 'num_9998', 'num_9999'],
      dtype=object)

In [1239]:
#041----- 元データとNumberダミー変数を結合
Num_4_2018_2026 = pd.concat([Num_4_2018_2026, df_Num], axis=1)
Num_4_2018_2026

,No,date,Lottery_result,Thousands,hundreds_place,tens_place,ones_place,Next_result,add_four,day_of_week,...,num_9990,num_9991,num_9992,num_9993,num_9994,num_9995,num_9996,num_9997,num_9998,num_9999
0,1,2018-01-04,5319,5,3,1,9,6489,18,3,...,0,0,0,0,0,0,0,0,0,0
1,2,2018-01-05,6489,6,4,8,9,5346,27,4,...,0,0,0,0,0,0,0,0,0,0
2,3,2018-01-08,5346,5,3,4,6,9751,18,0,...,0,0,0,0,0,0,0,0,0,0
3,4,2018-01-09,9751,9,7,5,1,1523,22,1,...,0,0,0,0,0,0,0,0,0,0
4,5,2018-01-10,1523,1,5,2,3,5820,11,2,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,53,2026-03-18,6449,6,4,4,9,6454,23,2,...,0,0,0,0,0,0,0,0,0,0
2112,54,2026-03-19,6454,6,4,5,4,9781,19,3,...,0,0,0,0,0,0,0,0,0,0
2113,55,2026-03-20,9781,9,7,8,1,3851,25,4,...,0,0,0,0,0,0,0,0,0,0
2114,56,2026-03-23,3851,3,8,5,1,9577,17,0,...,0,0,0,0,0,0,0,0,0,0
2115,57,2026-03-24,9577,9,5,7,7,5452,28,1,...,0,0,0,0,0,0,0,0,0,0

In [1240]:
#000----- Thousandsのダミー変数化
Thousands_list=['0','1','2','3','4','5','6','7','8','9']
enc=OneHotEncoder(categories=[Thousands_list],sparse_output=False)
Thousands_d=enc.fit_transform(Num_4_2018_2026[['Thousands']])
df_Thousands_d=pd.DataFrame(Thousands_d,index=Num_4_2018_2026.index,columns=Thousands_list,dtype='int')
df_Thousands_d

#警告コメントは将来非推奨になるので注意ということ→ 20251231_sparse=False から sparse_output=False に変更

      0  1  2  3  4  5  6  7  8  9
0     0  0  0  0  0  1  0  0  0  0
1     0  0  0  0  0  0  1  0  0  0
2     0  0  0  0  0  1  0  0  0  0
3     0  0  0  0  0  0  0  0  0  1
4     0  1  0  0  0  0  0  0  0  0
...  .. .. .. .. .. .. .. .. .. ..
2111  0  0  0  0  0  0  1  0  0  0
2112  0  0  0  0  0  0  1  0  0  0
2113  0  0  0  0  0  0  0  0  0  1
2114  0  0  0  1  0  0  0  0  0  0
2115  0  0  0  0  0  0  0  0  0  1

[2116 rows x 10 columns]

In [1241]:
#000----- のダミー変数列名の変更
df_Thousands_d=df_Thousands_d.rename(columns={'0':'T_0','1':'T_1','2':'T_2','3':'T_3','4':'T_4','5':'T_5','6':'T_6','7':'T_7','8':'T_8','9':'T_9'})
df_Thousands_d

      T_0  T_1  T_2  T_3  T_4  T_5  T_6  T_7  T_8  T_9
0       0    0    0    0    0    1    0    0    0    0
1       0    0    0    0    0    0    1    0    0    0
2       0    0    0    0    0    1    0    0    0    0
3       0    0    0    0    0    0    0    0    0    1
4       0    1    0    0    0    0    0    0    0    0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
2111    0    0    0    0    0    0    1    0    0    0
2112    0    0    0    0    0    0    1    0    0    0
2113    0    0    0    0    0    0    0    0    0    1
2114    0    0    0    1    0    0    0    0    0    0
2115    0    0    0    0    0    0    0    0    0    1

[2116 rows x 10 columns]

In [1242]:
#042----- hundreds_placeのダミー変数化
hundreds_place_list=['0','1','2','3','4','5','6','7','8','9']
enc=OneHotEncoder(categories=[hundreds_place_list],sparse_output=False)
hundreds_place_d=enc.fit_transform(Num_4_2018_2026[['hundreds_place']])
df_hundreds_place_d=pd.DataFrame(hundreds_place_d,index=Num_4_2018_2026.index,columns=hundreds_place_list,dtype='int')
df_hundreds_place_d

#警告コメントは将来非推奨になるので注意ということ→ 20251231_sparse=False から sparse_output=False に変更

      0  1  2  3  4  5  6  7  8  9
0     0  0  0  1  0  0  0  0  0  0
1     0  0  0  0  1  0  0  0  0  0
2     0  0  0  1  0  0  0  0  0  0
3     0  0  0  0  0  0  0  1  0  0
4     0  0  0  0  0  1  0  0  0  0
...  .. .. .. .. .. .. .. .. .. ..
2111  0  0  0  0  1  0  0  0  0  0
2112  0  0  0  0  1  0  0  0  0  0
2113  0  0  0  0  0  0  0  1  0  0
2114  0  0  0  0  0  0  0  0  1  0
2115  0  0  0  0  0  1  0  0  0  0

[2116 rows x 10 columns]

In [1243]:
#043----- hundreds_placeのダミー変数列名の変更
df_hundreds_place_d=df_hundreds_place_d.rename(columns={'0':'h_0','1':'h_1','2':'h_2','3':'h_3','4':'h_4','5':'h_5','6':'h_6','7':'h_7','8':'h_8','9':'h_9'})
df_hundreds_place_d

      h_0  h_1  h_2  h_3  h_4  h_5  h_6  h_7  h_8  h_9
0       0    0    0    1    0    0    0    0    0    0
1       0    0    0    0    1    0    0    0    0    0
2       0    0    0    1    0    0    0    0    0    0
3       0    0    0    0    0    0    0    1    0    0
4       0    0    0    0    0    1    0    0    0    0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
2111    0    0    0    0    1    0    0    0    0    0
2112    0    0    0    0    1    0    0    0    0    0
2113    0    0    0    0    0    0    0    1    0    0
2114    0    0    0    0    0    0    0    0    1    0
2115    0    0    0    0    0    1    0    0    0    0

[2116 rows x 10 columns]

In [1244]:
#044----- 元データとhundreds_place変数を結合
Num_4_2018_2026 = pd.concat([Num_4_2018_2026, df_hundreds_place_d], axis=1)
Num_4_2018_2026

,No,date,Lottery_result,Thousands,hundreds_place,tens_place,ones_place,Next_result,add_four,day_of_week,...,h_0,h_1,h_2,h_3,h_4,h_5,h_6,h_7,h_8,h_9
0,1,2018-01-04,5319,5,3,1,9,6489,18,3,...,0,0,0,1,0,0,0,0,0,0
1,2,2018-01-05,6489,6,4,8,9,5346,27,4,...,0,0,0,0,1,0,0,0,0,0
2,3,2018-01-08,5346,5,3,4,6,9751,18,0,...,0,0,0,1,0,0,0,0,0,0
3,4,2018-01-09,9751,9,7,5,1,1523,22,1,...,0,0,0,0,0,0,0,1,0,0
4,5,2018-01-10,1523,1,5,2,3,5820,11,2,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,53,2026-03-18,6449,6,4,4,9,6454,23,2,...,0,0,0,0,1,0,0,0,0,0
2112,54,2026-03-19,6454,6,4,5,4,9781,19,3,...,0,0,0,0,1,0,0,0,0,0
2113,55,2026-03-20,9781,9,7,8,1,3851,25,4,...,0,0,0,0,0,0,0,1,0,0
2114,56,2026-03-23,3851,3,8,5,1,9577,17,0,...,0,0,0,0,0,0,0,0,1,0
2115,57,2026-03-24,9577,9,5,7,7,5452,28,1,...,0,0,0,0,0,1,0,0,0,0

In [1245]:
#045----- tens_placeのダミー変数化
tens_place_list=['0','1','2','3','4','5','6','7','8','9']
enc=OneHotEncoder(categories=[tens_place_list],sparse_output=False)
tens_place_d=enc.fit_transform(Num_4_2018_2026[['tens_place']])
df_tens_place_d=pd.DataFrame(tens_place_d,index=Num_4_2018_2026.index,columns=tens_place_list,dtype='int')
df_tens_place_d

#警告コメントは将来非推奨になるので注意ということ→ 20251231_sparse=False から sparse_output=False に変更

      0  1  2  3  4  5  6  7  8  9
0     0  1  0  0  0  0  0  0  0  0
1     0  0  0  0  0  0  0  0  1  0
2     0  0  0  0  1  0  0  0  0  0
3     0  0  0  0  0  1  0  0  0  0
4     0  0  1  0  0  0  0  0  0  0
...  .. .. .. .. .. .. .. .. .. ..
2111  0  0  0  0  1  0  0  0  0  0
2112  0  0  0  0  0  1  0  0  0  0
2113  0  0  0  0  0  0  0  0  1  0
2114  0  0  0  0  0  1  0  0  0  0
2115  0  0  0  0  0  0  0  1  0  0

[2116 rows x 10 columns]

In [1246]:
#046----- tens_placeのダミー変数列名の変更
df_tens_place_d=df_tens_place_d.rename(columns={'0':'t_0','1':'t_1','2':'t_2','3':'t_3','4':'t_4','5':'t_5','6':'t_6','7':'t_7','8':'t_8','9':'t_9'})
df_tens_place_d

      t_0  t_1  t_2  t_3  t_4  t_5  t_6  t_7  t_8  t_9
0       0    1    0    0    0    0    0    0    0    0
1       0    0    0    0    0    0    0    0    1    0
2       0    0    0    0    1    0    0    0    0    0
3       0    0    0    0    0    1    0    0    0    0
4       0    0    1    0    0    0    0    0    0    0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
2111    0    0    0    0    1    0    0    0    0    0
2112    0    0    0    0    0    1    0    0    0    0
2113    0    0    0    0    0    0    0    0    1    0
2114    0    0    0    0    0    1    0    0    0    0
2115    0    0    0    0    0    0    0    1    0    0

[2116 rows x 10 columns]

In [1247]:
#047----- 元データとtens_place変数を結合
Num_4_2018_2026 = pd.concat([Num_4_2018_2026, df_tens_place_d], axis=1)
Num_4_2018_2026

,No,date,Lottery_result,Thousands,hundreds_place,tens_place,ones_place,Next_result,add_four,day_of_week,...,t_0,t_1,t_2,t_3,t_4,t_5,t_6,t_7,t_8,t_9
0,1,2018-01-04,5319,5,3,1,9,6489,18,3,...,0,1,0,0,0,0,0,0,0,0
1,2,2018-01-05,6489,6,4,8,9,5346,27,4,...,0,0,0,0,0,0,0,0,1,0
2,3,2018-01-08,5346,5,3,4,6,9751,18,0,...,0,0,0,0,1,0,0,0,0,0
3,4,2018-01-09,9751,9,7,5,1,1523,22,1,...,0,0,0,0,0,1,0,0,0,0
4,5,2018-01-10,1523,1,5,2,3,5820,11,2,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,53,2026-03-18,6449,6,4,4,9,6454,23,2,...,0,0,0,0,1,0,0,0,0,0
2112,54,2026-03-19,6454,6,4,5,4,9781,19,3,...,0,0,0,0,0,1,0,0,0,0
2113,55,2026-03-20,9781,9,7,8,1,3851,25,4,...,0,0,0,0,0,0,0,0,1,0
2114,56,2026-03-23,3851,3,8,5,1,9577,17,0,...,0,0,0,0,0,1,0,0,0,0
2115,57,2026-03-24,9577,9,5,7,7,5452,28,1,...,0,0,0,0,0,0,0,1,0,0

In [1248]:
#048----- ones_placeのダミー変数化
ones_place_list=['0','1','2','3','4','5','6','7','8','9']
enc=OneHotEncoder(categories=[ones_place_list],sparse_output=False)
ones_place_d=enc.fit_transform(Num_4_2018_2026[['ones_place']])
df_ones_place_d=pd.DataFrame(ones_place_d,index=Num_4_2018_2026.index,columns=ones_place_list,dtype='int')
df_ones_place_d

#警告コメントは将来非推奨になるので注意ということ→ 20251231_sparse=False から sparse_output=False に変更

      0  1  2  3  4  5  6  7  8  9
0     0  0  0  0  0  0  0  0  0  1
1     0  0  0  0  0  0  0  0  0  1
2     0  0  0  0  0  0  1  0  0  0
3     0  1  0  0  0  0  0  0  0  0
4     0  0  0  1  0  0  0  0  0  0
...  .. .. .. .. .. .. .. .. .. ..
2111  0  0  0  0  0  0  0  0  0  1
2112  0  0  0  0  1  0  0  0  0  0
2113  0  1  0  0  0  0  0  0  0  0
2114  0  1  0  0  0  0  0  0  0  0
2115  0  0  0  0  0  0  0  1  0  0

[2116 rows x 10 columns]

In [1249]:
#049----- ones_placeのダミー変数列名の変更
df_ones_place_d=df_ones_place_d.rename(columns={'0':'o_0','1':'o_1','2':'o_2','3':'o_3','4':'o_4','5':'o_5','6':'o_6','7':'o_7','8':'o_8','9':'o_9'})
df_ones_place_d

      o_0  o_1  o_2  o_3  o_4  o_5  o_6  o_7  o_8  o_9
0       0    0    0    0    0    0    0    0    0    1
1       0    0    0    0    0    0    0    0    0    1
2       0    0    0    0    0    0    1    0    0    0
3       0    1    0    0    0    0    0    0    0    0
4       0    0    0    1    0    0    0    0    0    0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
2111    0    0    0    0    0    0    0    0    0    1
2112    0    0    0    0    1    0    0    0    0    0
2113    0    1    0    0    0    0    0    0    0    0
2114    0    1    0    0    0    0    0    0    0    0
2115    0    0    0    0    0    0    0    1    0    0

[2116 rows x 10 columns]

In [1250]:
#050----- 元データとones_place変数を結合
Num_4_2018_2026 = pd.concat([Num_4_2018_2026, df_ones_place_d], axis=1)
Num_4_2018_2026

,No,date,Lottery_result,Thousands,hundreds_place,tens_place,ones_place,Next_result,add_four,day_of_week,...,o_0,o_1,o_2,o_3,o_4,o_5,o_6,o_7,o_8,o_9
0,1,2018-01-04,5319,5,3,1,9,6489,18,3,...,0,0,0,0,0,0,0,0,0,1
1,2,2018-01-05,6489,6,4,8,9,5346,27,4,...,0,0,0,0,0,0,0,0,0,1
2,3,2018-01-08,5346,5,3,4,6,9751,18,0,...,0,0,0,0,0,0,1,0,0,0
3,4,2018-01-09,9751,9,7,5,1,1523,22,1,...,0,1,0,0,0,0,0,0,0,0
4,5,2018-01-10,1523,1,5,2,3,5820,11,2,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,53,2026-03-18,6449,6,4,4,9,6454,23,2,...,0,0,0,0,0,0,0,0,0,1
2112,54,2026-03-19,6454,6,4,5,4,9781,19,3,...,0,0,0,0,1,0,0,0,0,0
2113,55,2026-03-20,9781,9,7,8,1,3851,25,4,...,0,1,0,0,0,0,0,0,0,0
2114,56,2026-03-23,3851,3,8,5,1,9577,17,0,...,0,1,0,0,0,0,0,0,0,0
2115,57,2026-03-24,9577,9,5,7,7,5452,28,1,...,0,0,0,0,0,0,0,1,0,0

In [1251]:
#051----- 曜日のダミー変数化
week_list=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
enc=OneHotEncoder(categories=[week_list],sparse_output=False)
week_d=enc.fit_transform(Num_4_2018_2026[['day_name']])
df_week_d=pd.DataFrame(week_d,index=Num_4_2018_2026.index,columns=week_list,dtype='int')
df_week_d

#警告コメントは将来非推奨になるので注意ということ→ 20251231_sparse=False から sparse_output=False に変更

      Sunday  Monday  Tuesday  Wednesday  Thursday  Friday  Saturday
0          0       0        0          0         1       0         0
1          0       0        0          0         0       1         0
2          0       1        0          0         0       0         0
3          0       0        1          0         0       0         0
4          0       0        0          1         0       0         0
...      ...     ...      ...        ...       ...     ...       ...
2111       0       0        0          1         0       0         0
2112       0       0        0          0         1       0         0
2113       0       0        0          0         0       1         0
2114       0       1        0          0         0       0         0
2115       0       0        1          0         0       0         0

[2116 rows x 7 columns]

In [1252]:
#052------ 元データとday_of_week変数を結合
Num_4_2018_2026 = pd.concat([Num_4_2018_2026, df_week_d], axis=1)
Num_4_2018_2026

,No,date,Lottery_result,Thousands,hundreds_place,tens_place,ones_place,Next_result,add_four,day_of_week,...,o_7,o_8,o_9,Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday
0,1,2018-01-04,5319,5,3,1,9,6489,18,3,...,0,0,1,0,0,0,0,1,0,0
1,2,2018-01-05,6489,6,4,8,9,5346,27,4,...,0,0,1,0,0,0,0,0,1,0
2,3,2018-01-08,5346,5,3,4,6,9751,18,0,...,0,0,0,0,1,0,0,0,0,0
3,4,2018-01-09,9751,9,7,5,1,1523,22,1,...,0,0,0,0,0,1,0,0,0,0
4,5,2018-01-10,1523,1,5,2,3,5820,11,2,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,53,2026-03-18,6449,6,4,4,9,6454,23,2,...,0,0,1,0,0,0,1,0,0,0
2112,54,2026-03-19,6454,6,4,5,4,9781,19,3,...,0,0,0,0,0,0,0,1,0,0
2113,55,2026-03-20,9781,9,7,8,1,3851,25,4,...,0,0,0,0,0,0,0,0,1,0
2114,56,2026-03-23,3851,3,8,5,1,9577,17,0,...,0,0,0,0,1,0,0,0,0,0
2115,57,2026-03-24,9577,9,5,7,7,5452,28,1,...,1,0,0,0,0,1,0,0,0,0

In [1253]:
#053----- yearごとのダミー変数化
year_list=['2018','2019','2020','2021','2022','2023','2024','2025','2026']
enc=OneHotEncoder(categories=[year_list],sparse_output=False)
year_d=enc.fit_transform(Num_4_2018_2026[['year']])
df_year=pd.DataFrame(year_d,index=Num_4_2018_2026.index,columns=year_list,dtype='int')
df_year

#警告コメントは将来非推奨になるので注意ということ→ 20251231_sparse=False から sparse_output=False に変更

      2018  2019  2020  2021  2022  2023  2024  2025  2026
0        1     0     0     0     0     0     0     0     0
1        1     0     0     0     0     0     0     0     0
2        1     0     0     0     0     0     0     0     0
3        1     0     0     0     0     0     0     0     0
4        1     0     0     0     0     0     0     0     0
...    ...   ...   ...   ...   ...   ...   ...   ...   ...
2111     0     0     0     0     0     0     0     0     1
2112     0     0     0     0     0     0     0     0     1
2113     0     0     0     0     0     0     0     0     1
2114     0     0     0     0     0     0     0     0     1
2115     0     0     0     0     0     0     0     0     1

[2116 rows x 9 columns]

In [1254]:
#054----- 元データとyear変数を結合
Num_4_2018_2026 = pd.concat([Num_4_2018_2026, df_year], axis=1)
Num_4_2018_2026

,No,date,Lottery_result,Thousands,hundreds_place,tens_place,ones_place,Next_result,add_four,day_of_week,...,Saturday,2018,2019,2020,2021,2022,2023,2024,2025,2026
0,1,2018-01-04,5319,5,3,1,9,6489,18,3,...,0,1,0,0,0,0,0,0,0,0
1,2,2018-01-05,6489,6,4,8,9,5346,27,4,...,0,1,0,0,0,0,0,0,0,0
2,3,2018-01-08,5346,5,3,4,6,9751,18,0,...,0,1,0,0,0,0,0,0,0,0
3,4,2018-01-09,9751,9,7,5,1,1523,22,1,...,0,1,0,0,0,0,0,0,0,0
4,5,2018-01-10,1523,1,5,2,3,5820,11,2,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,53,2026-03-18,6449,6,4,4,9,6454,23,2,...,0,0,0,0,0,0,0,0,0,1
2112,54,2026-03-19,6454,6,4,5,4,9781,19,3,...,0,0,0,0,0,0,0,0,0,1
2113,55,2026-03-20,9781,9,7,8,1,3851,25,4,...,0,0,0,0,0,0,0,0,0,1
2114,56,2026-03-23,3851,3,8,5,1,9577,17,0,...,0,0,0,0,0,0,0,0,0,1
2115,57,2026-03-24,9577,9,5,7,7,5452,28,1,...,0,0,0,0,0,0,0,0,0,1

In [1255]:
#055----- 3桁のSUMダミー変数化
add_four_list=['0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33','34','35','36']
enc=OneHotEncoder(categories=[add_four_list],sparse_output=False)
add_four_d=enc.fit_transform(Num_4_2018_2026[['add_four']])
df_add_four=pd.DataFrame(add_four_d,index=Num_4_2018_2026.index,columns=add_four_list,dtype='int')
df_add_four

#警告コメントは将来非推奨になるので注意ということ→ 20251231_sparse=False から sparse_output=False に変更

,0,1,2,3,4,5,6,7,8,9,...,27,28,29,30,31,32,33,34,35,36
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2112,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2113,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2114,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2115,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [1256]:
#056----- 3桁のSUMダミー変数列名の変更
df_add_four_new=df_add_four.rename(columns={'0':'add_0','1':'add_1','2':'add_2','3':'add_3','4':'add_4','5':'add_5','6':'add_6','7':'add_7','8':'add_8','9':'add_9',
                                              '10':'add_10','11':'add_11','12':'add_12','13':'add_13','14':'add_14','15':'add_15','16':'add_16','17':'add_17','18':'add_18','19':'add_19',
                                              '20':'add_20','21':'add_21','22':'add_22','23':'add_23','24':'add_24','25':'add_25','26':'add_26','27':'add_27','28':'add_28','29':'add_29','30':'add_30','31':'add_31','32':'add_32','33':'add_33','34':'add_34','35':'add_35','36':'add_36'})
df_add_four_new

,add_0,add_1,add_2,add_3,add_4,add_5,add_6,add_7,add_8,add_9,...,add_27,add_28,add_29,add_30,add_31,add_32,add_33,add_34,add_35,add_36
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2112,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2113,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2114,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2115,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [1257]:
#057----- 元データとadd_three変数を結合
Num_4_2018_2026 = pd.concat([Num_4_2018_2026, df_add_four_new], axis=1)
Num_4_2018_2026

,No,date,Lottery_result,Thousands,hundreds_place,tens_place,ones_place,Next_result,add_four,day_of_week,...,add_27,add_28,add_29,add_30,add_31,add_32,add_33,add_34,add_35,add_36
0,1,2018-01-04,5319,5,3,1,9,6489,18,3,...,0,0,0,0,0,0,0,0,0,0
1,2,2018-01-05,6489,6,4,8,9,5346,27,4,...,1,0,0,0,0,0,0,0,0,0
2,3,2018-01-08,5346,5,3,4,6,9751,18,0,...,0,0,0,0,0,0,0,0,0,0
3,4,2018-01-09,9751,9,7,5,1,1523,22,1,...,0,0,0,0,0,0,0,0,0,0
4,5,2018-01-10,1523,1,5,2,3,5820,11,2,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,53,2026-03-18,6449,6,4,4,9,6454,23,2,...,0,0,0,0,0,0,0,0,0,0
2112,54,2026-03-19,6454,6,4,5,4,9781,19,3,...,0,0,0,0,0,0,0,0,0,0
2113,55,2026-03-20,9781,9,7,8,1,3851,25,4,...,0,0,0,0,0,0,0,0,0,0
2114,56,2026-03-23,3851,3,8,5,1,9577,17,0,...,0,0,0,0,0,0,0,0,0,0
2115,57,2026-03-24,9577,9,5,7,7,5452,28,1,...,0,1,0,0,0,0,0,0,0,0

In [1258]:
#058----- データ確認
Num_4_2018_2026

,No,date,Lottery_result,Thousands,hundreds_place,tens_place,ones_place,Next_result,add_four,day_of_week,...,add_27,add_28,add_29,add_30,add_31,add_32,add_33,add_34,add_35,add_36
0,1,2018-01-04,5319,5,3,1,9,6489,18,3,...,0,0,0,0,0,0,0,0,0,0
1,2,2018-01-05,6489,6,4,8,9,5346,27,4,...,1,0,0,0,0,0,0,0,0,0
2,3,2018-01-08,5346,5,3,4,6,9751,18,0,...,0,0,0,0,0,0,0,0,0,0
3,4,2018-01-09,9751,9,7,5,1,1523,22,1,...,0,0,0,0,0,0,0,0,0,0
4,5,2018-01-10,1523,1,5,2,3,5820,11,2,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,53,2026-03-18,6449,6,4,4,9,6454,23,2,...,0,0,0,0,0,0,0,0,0,0
2112,54,2026-03-19,6454,6,4,5,4,9781,19,3,...,0,0,0,0,0,0,0,0,0,0
2113,55,2026-03-20,9781,9,7,8,1,3851,25,4,...,0,0,0,0,0,0,0,0,0,0
2114,56,2026-03-23,3851,3,8,5,1,9577,17,0,...,0,0,0,0,0,0,0,0,0,0
2115,57,2026-03-24,9577,9,5,7,7,5452,28,1,...,0,1,0,0,0,0,0,0,0,0

In [1259]:
#059----- counter_dataを取得して新しい出現回数列追加_#25の出現回数以上であることね_→#33の7年間の出現回数のこと
#20231115_Reo_アドバイス_counter

import collections
list_num = Num_4_2018_2026['Lottery_result']
df1=collections.Counter(list_num)

new_column = [df1[item] for item in Num_4_2018_2026['Lottery_result'].tolist()]
Num_4_2018_2026['counter'] = new_column
Num_4_2018_2026

,No,date,Lottery_result,Thousands,hundreds_place,tens_place,ones_place,Next_result,add_four,day_of_week,...,add_28,add_29,add_30,add_31,add_32,add_33,add_34,add_35,add_36,counter
0,1,2018-01-04,5319,5,3,1,9,6489,18,3,...,0,0,0,0,0,0,0,0,0,1
1,2,2018-01-05,6489,6,4,8,9,5346,27,4,...,0,0,0,0,0,0,0,0,0,1
2,3,2018-01-08,5346,5,3,4,6,9751,18,0,...,0,0,0,0,0,0,0,0,0,2
3,4,2018-01-09,9751,9,7,5,1,1523,22,1,...,0,0,0,0,0,0,0,0,0,1
4,5,2018-01-10,1523,1,5,2,3,5820,11,2,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,53,2026-03-18,6449,6,4,4,9,6454,23,2,...,0,0,0,0,0,0,0,0,0,1
2112,54,2026-03-19,6454,6,4,5,4,9781,19,3,...,0,0,0,0,0,0,0,0,0,1
2113,55,2026-03-20,9781,9,7,8,1,3851,25,4,...,0,0,0,0,0,0,0,0,0,1
2114,56,2026-03-23,3851,3,8,5,1,9577,17,0,...,0,0,0,0,0,0,0,0,0,1
2115,57,2026-03-24,9577,9,5,7,7,5452,28,1,...,1,0,0,0,0,0,0,0,0,1

In [1260]:
#060----- dataのcounterをダミー変数化（10回で)
import os
import pandas as pd # type: ignore
import numpy as np # type: ignore
from sklearn.preprocessing import OneHotEncoder # type: ignore

df_n=range(0,11,1)

counter_list=df_n
enc=OneHotEncoder(categories=[counter_list],sparse_output=False)
counter_d=enc.fit_transform(Num_4_2018_2026[['counter']])
df_counter=pd.DataFrame(counter_d,index=Num_4_2018_2026.index,columns=counter_list,dtype='int')

df_counter

#警告コメントは将来非推奨になるので注意ということ→ 20251231_sparse=False から sparse_output=False に変更

      0   1   2   3   4   5   6   7   8   9   10
0      0   1   0   0   0   0   0   0   0   0   0
1      0   1   0   0   0   0   0   0   0   0   0
2      0   0   1   0   0   0   0   0   0   0   0
3      0   1   0   0   0   0   0   0   0   0   0
4      0   1   0   0   0   0   0   0   0   0   0
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
2111   0   1   0   0   0   0   0   0   0   0   0
2112   0   1   0   0   0   0   0   0   0   0   0
2113   0   1   0   0   0   0   0   0   0   0   0
2114   0   1   0   0   0   0   0   0   0   0   0
2115   0   1   0   0   0   0   0   0   0   0   0

[2116 rows x 11 columns]

In [1261]:
#061----- columns名の変更
for i in range(11):
        name=('counter_' + str(i))
        df_counter=df_counter.rename(columns={i: name})
        
df_counter

,counter_0,counter_1,counter_2,counter_3,counter_4,counter_5,counter_6,counter_7,counter_8,counter_9,counter_10
0,0,1,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
2111,0,1,0,0,0,0,0,0,0,0,0
2112,0,1,0,0,0,0,0,0,0,0,0
2113,0,1,0,0,0,0,0,0,0,0,0
2114,0,1,0,0,0,0,0,0,0,0,0
2115,0,1,0,0,0,0,0,0,0,0,0

In [1262]:
#062----- 元データとcounter変数を結合
Num_4_2018_2026 = pd.concat([Num_4_2018_2026, df_counter], axis=1)
Num_4_2018_2026

,No,date,Lottery_result,Thousands,hundreds_place,tens_place,ones_place,Next_result,add_four,day_of_week,...,counter_1,counter_2,counter_3,counter_4,counter_5,counter_6,counter_7,counter_8,counter_9,counter_10
0,1,2018-01-04,5319,5,3,1,9,6489,18,3,...,1,0,0,0,0,0,0,0,0,0
1,2,2018-01-05,6489,6,4,8,9,5346,27,4,...,1,0,0,0,0,0,0,0,0,0
2,3,2018-01-08,5346,5,3,4,6,9751,18,0,...,0,1,0,0,0,0,0,0,0,0
3,4,2018-01-09,9751,9,7,5,1,1523,22,1,...,1,0,0,0,0,0,0,0,0,0
4,5,2018-01-10,1523,1,5,2,3,5820,11,2,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,53,2026-03-18,6449,6,4,4,9,6454,23,2,...,1,0,0,0,0,0,0,0,0,0
2112,54,2026-03-19,6454,6,4,5,4,9781,19,3,...,1,0,0,0,0,0,0,0,0,0
2113,55,2026-03-20,9781,9,7,8,1,3851,25,4,...,1,0,0,0,0,0,0,0,0,0
2114,56,2026-03-23,3851,3,8,5,1,9577,17,0,...,1,0,0,0,0,0,0,0,0,0
2115,57,2026-03-24,9577,9,5,7,7,5452,28,1,...,1,0,0,0,0,0,0,0,0,0

In [1263]:
#空き

In [1264]:
#063-----参考---hundreds_place counter テストして_2024/3/9_参考になるので、最後で消しておいて影響しないようにしておこう

import collections
list_num = Num_4_2018_2026['Thousands']
df1 = collections.Counter(list_num)

new_column = [df1[item] for item in Num_4_2018_2026['Thousands'].tolist()]
Num_4_2018_2026['counter_h'] = new_column
Num_4_2018_2026

,No,date,Lottery_result,Thousands,hundreds_place,tens_place,ones_place,Next_result,add_four,day_of_week,...,counter_2,counter_3,counter_4,counter_5,counter_6,counter_7,counter_8,counter_9,counter_10,counter_h
0,1,2018-01-04,5319,5,3,1,9,6489,18,3,...,0,0,0,0,0,0,0,0,0,212
1,2,2018-01-05,6489,6,4,8,9,5346,27,4,...,0,0,0,0,0,0,0,0,0,210
2,3,2018-01-08,5346,5,3,4,6,9751,18,0,...,1,0,0,0,0,0,0,0,0,212
3,4,2018-01-09,9751,9,7,5,1,1523,22,1,...,0,0,0,0,0,0,0,0,0,197
4,5,2018-01-10,1523,1,5,2,3,5820,11,2,...,0,0,0,0,0,0,0,0,0,217
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,53,2026-03-18,6449,6,4,4,9,6454,23,2,...,0,0,0,0,0,0,0,0,0,210
2112,54,2026-03-19,6454,6,4,5,4,9781,19,3,...,0,0,0,0,0,0,0,0,0,210
2113,55,2026-03-20,9781,9,7,8,1,3851,25,4,...,0,0,0,0,0,0,0,0,0,197
2114,56,2026-03-23,3851,3,8,5,1,9577,17,0,...,0,0,0,0,0,0,0,0,0,207
2115,57,2026-03-24,9577,9,5,7,7,5452,28,1,...,0,0,0,0,0,0,0,0,0,197

In [1265]:
#064----- 不要な列を削除_Noは削除してLottery_resultは残す_20231118_
Num_4_2018_2026=Num_4_2018_2026.drop(columns=['No','date','add_four','day_of_week','day_name','year','hundreds_place','tens_place','ones_place','counter','counter_h','Thousands+year','Thousands','td_ct'])
Num_4_2018_2026

,Lottery_result,Next_result,td_ct0,td_ct1,td_ct2,td_ct3,td_ct4,td_ct5,td_ct6,td_ct7,...,counter_1,counter_2,counter_3,counter_4,counter_5,counter_6,counter_7,counter_8,counter_9,counter_10
0,5319,6489,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,6489,5346,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,5346,9751,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,9751,1523,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,1523,5820,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,6449,6454,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2112,6454,9781,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2113,9781,3851,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2114,3851,9577,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2115,9577,5452,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [1266]:
#065----- 予測列データを取得
df_new=pd.DataFrame({'Next_result': Num_4_2018_2026.loc[:, 'Next_result']})
df_new

      Next_result
0            6489
1            5346
2            9751
3            1523
4            5820
...           ...
2111         6454
2112         9781
2113         3851
2114         9577
2115         5452

[2116 rows x 1 columns]

In [1267]:
#066----- 予測列を先にを削除
Num_4_2018_2026=Num_4_2018_2026.drop(columns=['Next_result'])
Num_4_2018_2026

,Lottery_result,td_ct0,td_ct1,td_ct2,td_ct3,td_ct4,td_ct5,td_ct6,td_ct7,td_ct8,...,counter_1,counter_2,counter_3,counter_4,counter_5,counter_6,counter_7,counter_8,counter_9,counter_10
0,5319,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,6489,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,5346,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,9751,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,1523,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,6449,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2112,6454,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2113,9781,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2114,3851,0,0,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
2115,9577,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [1268]:
#067----- 元データとNext_resultを結合して右端へいれる
df = pd.concat([Num_4_2018_2026, df_new], axis=1)
df

,Lottery_result,td_ct0,td_ct1,td_ct2,td_ct3,td_ct4,td_ct5,td_ct6,td_ct7,td_ct8,...,counter_2,counter_3,counter_4,counter_5,counter_6,counter_7,counter_8,counter_9,counter_10,Next_result
0,5319,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6489
1,6489,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5346
2,5346,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,9751
3,9751,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1523
4,1523,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5820
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2111,6449,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6454
2112,6454,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,9781
2113,9781,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3851
2114,3851,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,9577
2115,9577,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5452

In [1269]:
#068----- data type 確認-----int32に変換しているからint32になっていたね20260322
df.dtypes

Lottery_result    int32
td_ct0            int32
td_ct1            int32
td_ct2            int32
td_ct3            int32
                  ...
counter_7         int32
counter_8         int32
counter_9         int32
counter_10        int32
Next_result       int32
Length: 10137, dtype: object

In [1270]:
#069----- ここまでのデータをcsvで出力、保管_ホルダー名前更新

#data_file='df_2018_2024.csv'
data_file='df_2018_2026.csv'
df.to_csv(os.path.join(challenge_1_data,data_file),index=False)

In [1271]:
#ここまでがデータ準備でここから分析開始よ----dfにデータ格納

In [1272]:
#001 説明変数と目的変数に分割_ここから繰り返し
X=df.iloc[:, :-1]
y=df.iloc[:, -1]

In [1273]:
#002 data_check
print(X)

      Lottery_result  td_ct0  td_ct1  td_ct2  td_ct3  td_ct4  td_ct5  td_ct6  \
0               5319       0       0       0       0       0       0       0
1               6489       0       0       0       0       0       0       0
2               5346       0       0       0       0       0       0       0
3               9751       0       0       0       0       0       0       0
4               1523       0       0       0       0       0       0       0
...              ...     ...     ...     ...     ...     ...     ...     ...
2111            6449       0       0       0       0       0       0       0
2112            6454       0       0       0       0       0       0       0
2113            9781       0       0       0       0       0       0       0
2114            3851       0       0       0       0       0       0       0
2115            9577       0       0       0       0       0       0       0

      td_ct7  td_ct8  ...  counter_1  counter_2  counter_3  counter_4  \
0          0       0  ...          1          0          0          0
1          0       0  ...          1          0          0          0
2          0       0  ...          0          1          0          0
3          0       0  ...          1          0          0          0
4          0       0  ...          1          0          0          0
...      ...     ...  ...        ...        ...        ...        ...
2111       0       0  ...          1          0          0          0
2112       0       0  ...          1          0          0          0
2113       0       0  ...          1          0          0          0
2114       0       1  ...          1          0          0          0
2115       0       0  ...          1          0          0          0

      counter_5  counter_6  counter_7  counter_8  counter_9  counter_10
0             0          0          0          0          0           0
1             0          0          0          0          0           0
2             0          0          0          0          0           0
3             0          0          0          0          0           0
4             0          0          0          0          0           0
...         ...        ...        ...        ...        ...         ...
2111          0          0          0          0          0           0
2112          0          0          0          0          0           0
2113          0          0          0          0          0           0
2114          0          0          0          0          0           0
2115          0          0          0          0          0           0

[2116 rows x 10136 columns]

In [1274]:
#003 data_check
print(y)

0       6489
1       5346
2       9751
3       1523
4       5820
        ...
2111    6454
2112    9781
2113    3851
2114    9577
2115    5452
Name: Next_result, Length: 2116, dtype: int32

In [1275]:
#004 最終行数を取得
last_row = df.shape[0] - 1#最終行番号
print(last_row)

last_row1 = df.shape[0]#0～最終までの行数
print(last_row1)

2115
2116

In [1276]:
#005 モデルの構築と検証---"1"に近いと良い
from sklearn.linear_model import LinearRegression # type: ignore
model=LinearRegression()
model.fit(X,y)
model.score(X,y)
#重回帰の場合50%(0.5)が精度の目安と言われている

0.9303050842362346

In [1277]:
#006 学習
from sklearn.model_selection import train_test_split # type: ignore
# X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=20)#初期 size=0.4 state=1---state=20→30→40 "本では42推奨しているけどここで調整するところ"
#-----警告処置-----

#微調整が必要かなsize=0.2→0.25→0.3　random_state= は20が基本で30→40で調整---42---
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=0)
X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=20)
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=30)
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=42)

model.fit(X_train,y_train)
model.fit(X_test,y_test)

LinearRegression()

In [1278]:
#007 検証---value test_size=0.2のとき---重回帰は"1"に近いと良い---マイナスになることもある。"-1"に近いのもOK---　webでは数値が高いほど学習効果あると研究段階ともある難しいみたいね-----
model.score(X_train,y_train)

# k = model.score(X_train,y_train)
# k = abs(k)
# print(k)

-0.3784535202471664

In [1279]:
#008 予測-----先頭だけ確認してみる→20251011_最終行表示へ更新-----
import math
# x=x.iloc[0,:]
# y_pred=model.predict([x])[0]
# i=0 #先頭行
m=last_row #最終行
x=X.iloc[m,:] #予測する行番号-----#003で列数確認
y_pred20=model.predict([x])[0]
#y_pred=round(y_pred)

print(m,':',y_pred20)
print(m,':',math.ceil(y_pred20),':','切り上げ')#切り上げ
print(m,':',math.floor(y_pred20),':','切り捨て')#切り捨て
print(m,':',round(y_pred20),':','四捨五入')#四捨五入

#毎日ここで数値を確認してから

2115 : 5992.387488683525
2115 : 5993 : 切り上げ
2115 : 5992 : 切り捨て
2115 : 5992 : 四捨五入

In [1280]:
#009 先頭の25行くらいで予測値の補正が必要か分かるからやってみよう

for i in range(0,50):  #0～最終までの行数 25→50
    
    x=X.iloc[i,:] #予測する行番号-----#003で列数確認
    y_pred20=model.predict([x])[0]
    
    # y_pred=round(y_pred)#四捨五入
    y_pred20=math.floor(y_pred20)#切り下げ
    print(i,y_pred20)

0 6327
1 3026
2 6197
3 1363
4 7438
5 6002
6 1920
7 4568
8 7054
9 6109
10 4954
11 2834
12 2650
13 6442
14 5547
15 4894
16 5074
17 4945
18 4147
19 7187
20 8905
21 3587
22 5826
23 3632
24 8310
25 5039
26 4230
27 3827
28 4946
29 6511
30 4500
31 8622
32 4687
33 6952
34 6102
35 3276
36 4162
37 7820
38 1440
39 3467
40 1107
41 4679
42 6142
43 2078
44 7475
45 3159
46 4559
47 5819
48 5131
49 7827

In [1281]:
#010 最終行から25行までをみれば補正が必要かわかる

#最終行番号確認　→　行数あると予測値Textコピペできないので個別に表示_20240816
k=last_row 
# print(k)

for k in range(k-50,k+1):  #0～最終までの行数 25→50
    
    x=X.iloc[k,:] #予測する行番号-----#003で列数確認
    y_pred20=model.predict([x])[0]
    
    # y_pred=round(y_pred)#四捨五入

    y_pred20=math.floor(y_pred20)#切り下げ
    print(k,y_pred20)

2065 2403
2066 6969
2067 4048
2068 1996
2069 5971
2070 4892
2071 6021
2072 514
2073 5723
2074 2889
2075 5359
2076 6472
2077 1911
2078 3718
2079 3692
2080 1955
2081 5972
2082 3643
2083 3731
2084 1401
2085 2303
2086 4654
2087 5120
2088 1554
2089 4927
2090 4057
2091 5348
2092 3071
2093 3723
2094 4341
2095 3157
2096 4911
2097 643
2098 7625
2099 2479
2100 2840
2101 6092
2102 7591
2103 4818
2104 2191
2105 4784
2106 2571
2107 3439
2108 3420
2109 2212
2110 4467
2111 6453
2112 4552
2113 4693
2114 3930
2115 5992

In [1282]:
#011 予測

i=last_row #最終行番号
x=X.iloc[i,:] #予測する行番号-----#004で列数確認
y_pred20=model.predict([x])[0]

# y_pred=round(y_pred) #四捨五入
y_pred20=math.floor(y_pred20)#切り下げ

print(i,':',y_pred20)

2115 : 5992

In [1283]:
#012 最終行番号確認　→　行数あると予測値Textコピペできないので個別に表示_20240816_
k=last_row 
print(k)

2115

In [1284]:
#2026/2/25  今日はここまで

In [1285]:
#012 負の値と異常値のときの処理-----20251011_追加して経過を観察してみる-----
if -10000 < y_pred20 < 0:
    # y_pred_num1 = y_pred * 100 #100倍してから桁ごとの数値を取得
    y_pred20 = format(y_pred20, '05.0f') #format関数で5桁の文字列に変換（負の符号も含む）0F=小数点なし
    
    n1 = int(str(y_pred20)[-4]) #千の位
    n2 = int(str(y_pred20)[-3]) #百の位
    n3 = int(str(y_pred20)[-2]) #十の位
    n4 = int(str(y_pred20)[-1]) #一の位

    print(i,':',n1,n2,n3,n4,n5,':','負の値を補正',y_pred20)

elif y_pred20 > 9999:
    
    n1 = int(str(y_pred20)[-4]) #千の位
    n2 = int(str(y_pred20)[-3]) #百の位
    n3 = int(str(y_pred20)[-2]) #十の位
    n4 = int(str(y_pred20)[-1]) #一の位

    print(i,':',n1,n2,n3,n4,n5,':','異常値を補正',y_pred20)

elif y_pred20 < -9999:
    print(i,':','負の異常値',y_pred20)

else:
    print(i,':',y_pred20,':','正常値です')

2115 : 5992 : 正常値です

In [1286]:
#ここまでで予測はできることを確認20230922
#Next_resultで予測できたけど精度が低いので補正方法を調べる
#ダミー変数を追加していく

In [1287]:
#-----簡単に作業できるかまとめてみた-----

In [1288]:
#一回で全部みてみましょう

In [1289]:
#001 説明変数と目的変数に分割-----まとめて出力できないか-----
X=df.iloc[:, :-1]
y=df.iloc[:, -1]

#モデルの構築と検証---"1"に近いと良い
from sklearn.linear_model import LinearRegression # type: ignore
model=LinearRegression()
model.fit(X,y)
# model.score(x,y)

#学習
from sklearn.model_selection import train_test_split # type: ignore
# X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=20)#初期 size=0.4 state=1→20→30→40 "本では42推奨しているけどここで調整するところ"
#-----警告処置-----

#微調整が必要かなsize=0.2→0.25→0.3 random_state= は20が基本で30→40で調整　---42---
X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=0)
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=20)
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=30)
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=42)


model.fit(X_train,y_train)
model.fit(X_test,y_test)

LinearRegression()

In [1290]:
#002 検証---value test_size=0.2のとき---重回帰は"1"に近いと良い---マイナスになることもある。"-1"に近いのもOK---　webでは数値が高いほど学習効果あると研究段階ともある難しいみたいね-----
model.score(X_train,y_train)

# k = model.score(X_train,y_train)
# k = abs(k)
# print(k)

-1.4790449491641873

In [1291]:
#003 先頭の25行くらいで予測値の補正が必要か分かるからやってみよう

for i in range(0,50):  #0～最終までの行数 25→50
    
    x=X.iloc[i,:] #予測する行番号-----#003で列数確認
    y_pred00=model.predict([x])[0]
   
    # y_pred=round(y_pred) #四捨五入
    y_pred00=math.floor(y_pred00)#切り下げ

    print(i,y_pred00)

0 12274
1 5345
2 11046
3 5992
4 3181
5 6409
6 6605
7 3621
8 10031
9 6109
10 1181
11 4229
12 7851
13 5153
14 570
15 5816
16 10774
17 4945
18 4148
19 -1451
20 7717
21 7343
22 9730
23 6286
24 8045
25 6110
26 5242
27 1508
28 4933
29 5076
30 1539
31 5549
32 9242
33 -402
34 2978
35 7388
36 5752
37 7336
38 12118
39 3774
40 6722
41 1887
42 3071
43 8253
44 11288
45 11431
46 9500
47 5192
48 5563
49 11631

In [1292]:
#004 最終行から25行までをみれば補正が必要かわかる

#最終行番号確認　→　行数あると予測値Textコピペできないので個別に表示_20240816_
k=last_row 
# print(k)

for k in range(k-50,k+1):  #0～最終までの行数 25→50
    
    x=X.iloc[k,:] #予測する行番号-----#003で列数確認
    y_pred00=model.predict([x])[0]
   
    # y_pred=round(y_pred) #四捨五入
    y_pred00=math.floor(y_pred00)#切り下げ

    print(k,y_pred00)

2065 5535
2066 7565
2067 4291
2068 8966
2069 7361
2070 7573
2071 4940
2072 514
2073 4390
2074 3511
2075 7000
2076 7534
2077 2107
2078 1670
2079 3399
2080 3286
2081 9280
2082 6402
2083 7523
2084 3395
2085 4177
2086 5366
2087 5227
2088 5371
2089 8344
2090 4752
2091 9166
2092 3114
2093 3247
2094 7330
2095 1917
2096 9154
2097 5199
2098 7625
2099 5296
2100 5693
2101 10598
2102 2378
2103 4391
2104 8009
2105 3218
2106 9419
2107 2902
2108 2883
2109 4847
2110 4318
2111 9870
2112 10606
2113 2540
2114 3972
2115 3105

In [1293]:
#005 予測

i=last_row #最終行番号
x=X.iloc[i,:] #予測する行番号-----#004で列数確認
y_pred00=model.predict([x])[0]

# y_pred=round(y_pred) #四捨五入
y_pred00=math.floor(y_pred00)#切り下げ

print(i,':',y_pred00)

2115 : 3105

In [1294]:
#006 負の値と異常値のときの処理-----20251011_追加して経過を観察してみる-----
if -10000 < y_pred00 < 0:
    # y_pred_num1 = y_pred * 100 #100倍してから桁ごとの数値を取得
    y_pred00 = format(y_pred00, '05.0f') #format関数で5桁の文字列に変換（負の符号も含む）
   
    n1 = int(str(y_pred00)[-4]) #千の位
    n2 = int(str(y_pred00)[-3]) #百の位
    n3 = int(str(y_pred00)[-2]) #十の位
    n4 = int(str(y_pred00)[-1]) #一の位

    print(i,':',n1,n2,n3,n4,n5,':','負の値を補正',y_pred00)

elif y_pred00 > 9999:
    
    n1 = int(str(y_pred00)[-4]) #千の位
    n2 = int(str(y_pred00)[-3]) #百の位
    n3 = int(str(y_pred00)[-2]) #十の位
    n4 = int(str(y_pred00)[-1]) #一の位

    print(i,':',n1,n2,n3,n4,n5,':','異常値を補正',y_pred00)

elif y_pred00 < -9999:
    print(i,':','負の異常値',y_pred00)    

else:
    print(i,':',y_pred00,':','正常値です')

2115 : 3105 : 正常値です

In [1295]:
#001 説明変数と目的変数に分割-----まとめて出力できないか-----
X=df.iloc[:, :-1]
y=df.iloc[:, -1]

#モデルの構築と検証---"1"に近いと良い
from sklearn.linear_model import LinearRegression # type: ignore
model=LinearRegression()
model.fit(X,y)
# model.score(x,y)

#学習
from sklearn.model_selection import train_test_split # type: ignore
# X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=20)#初期 size=0.4 state=1→20→30→40 "本では42推奨しているけどここで調整するところ"
#-----警告処置-----

#微調整が必要かなsize=0.2→0.25→0.3 random_state= は20が基本で30→40で調整　---42---
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=0)
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=20)
X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=30)
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=42)


model.fit(X_train,y_train)
model.fit(X_test,y_test)

LinearRegression()

In [1296]:
#002 検証---value test_size=0.2のとき---重回帰は"1"に近いと良い---マイナスになることもある。"-1"に近いのもOK---　webでは数値が高いほど学習効果あると研究段階ともある難しいみたいね-----
model.score(X_train,y_train)

# k = model.score(X_train,y_train)
# k = abs(k)
# print(k)

-0.7163237994625096

In [1297]:
#003 先頭の25行くらいで予測値の補正が必要か分かるからやってみよう

for i in range(0,50):  #0～最終までの行数 25→50
    
    x=X.iloc[i,:] #予測する行番号-----#003で列数確認
    y_pred30=model.predict([x])[0]
    
    # y_pred=round(y_pred) #四捨五入
    y_pred30=math.floor(y_pred30)#切り下げ

    print(i,y_pred30)

0 5611
1 9323
2 6040
3 7485
4 3502
5 5802
6 6605
7 5563
8 6147
9 2347
10 4510
11 5386
12 4907
13 5647
14 2529
15 2409
16 6014
17 5240
18 4148
19 -2044
20 8905
21 2859
22 6205
23 7411
24 5265
25 5544
26 7728
27 6514
28 5708
29 2295
30 1540
31 5550
32 5421
33 3252
34 4755
35 7914
36 5277
37 5087
38 6826
39 5061
40 6285
41 7365
42 6381
43 5414
44 3965
45 5021
46 6552
47 6073
48 6994
49 3269

In [1298]:
#004 最終行から25行までをみれば補正が必要かわかる

#最終行番号確認　→　行数あると予測値Textコピペできないので個別に表示_20240816_
k=last_row 
# print(k)

for k in range(k-50,k+1):  #0～最終までの行数 25→50
    
    x=X.iloc[k,:] #予測する行番号-----#003で列数確認
    y_pred30=model.predict([x])[0]

    # y_pred=round(y_pred) #四捨五入
    y_pred30=math.floor(y_pred30)#切り下げ

    print(k,y_pred30)

2065 7805
2066 5307
2067 5149
2068 3835
2069 9919
2070 4727
2071 4134
2072 2115
2073 5592
2074 4797
2075 9744
2076 6120
2077 2956
2078 9945
2079 7754
2080 3833
2081 3399
2082 3485
2083 2823
2084 5194
2085 6423
2086 6390
2087 6408
2088 2530
2089 505
2090 6216
2091 1543
2092 5344
2093 4999
2094 5531
2095 3170
2096 3740
2097 4245
2098 5999
2099 9086
2100 8404
2101 1446
2102 7592
2103 8888
2104 2631
2105 6092
2106 427
2107 247
2108 5030
2109 2295
2110 7583
2111 542
2112 3188
2113 4931
2114 3454
2115 4921

In [1299]:
#005 予測

i=last_row #最終行番号
x=X.iloc[i,:] #予測する行番号-----#004で列数確認
y_pred30=model.predict([x])[0]

# y_pred=round(y_pred) #四捨五入
y_pred30=math.floor(y_pred30)#切り下げ

print(i,':',y_pred30)

2115 : 4921

In [1300]:
#006 負の値と異常値のときの処理-----20251011_追加して経過を観察してみる-----
if -10000 < y_pred30 < 0:
    # y_pred_num1 = y_pred * 100 #100倍してから桁ごとの数値を取得
    y_pred30 = format(y_pred30, '05.0f') #format関数で5桁の文字列に変換（負の符号も含む）
    
    
    n1 = int(str(y_pred30)[-4]) #千の位
    n2 = int(str(y_pred30)[-3]) #百の位
    n3 = int(str(y_pred30)[-2]) #十の位
    n4 = int(str(y_pred30)[-1]) #一の位

    print(i,':',n1,n2,n3,n4,n5,':','負の値を補正',y_pred30)
    # print('formatted_result :',formatted_result)

elif y_pred30 > 9999:
    
    n1 = int(str(y_pred30)[-4]) #千の位
    n2 = int(str(y_pred30)[-3]) #百の位
    n3 = int(str(y_pred30)[-2]) #十の位
    n4 = int(str(y_pred30)[-1]) #一の位
    
    print(i,':',n1,n2,n3,n4,n5,':','異常値を補正',y_pred30)

elif y_pred30 < -9999:
    print(i,':','負の異常値',y_pred30)

else:
    print(i,':',y_pred30,':','正常値です')

2115 : 4921 : 正常値です

In [1301]:
#001 説明変数と目的変数に分割-----まとめて出力できないか-----
X=df.iloc[:, :-1]
y=df.iloc[:, -1]

#モデルの構築と検証---"1"に近いと良い
from sklearn.linear_model import LinearRegression # type: ignore
model=LinearRegression()
model.fit(X,y)
# model.score(x,y)

#学習
from sklearn.model_selection import train_test_split # type: ignore
# X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=20)#初期 size=0.4 state=1→20→30→40 "本では42推奨しているけどここで調整するところ"
#-----警告処置-----

#微調整が必要かなsize=0.2→0.25→0.3 random_state= は20が基本で30→40で調整　---42---
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=0)
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=20)
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=30)
X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=42)


model.fit(X_train,y_train)
model.fit(X_test,y_test)

LinearRegression()

In [1302]:
#002 検証---value test_size=0.2のとき---重回帰は"1"に近いと良い---マイナスになることもある。"-1"に近いのもOK---　webでは数値が高いほど学習効果あると研究段階ともある難しいみたいね-----
model.score(X_train,y_train)

# k = model.score(X_train,y_train)
# k = abs(k)
# print(k)

-0.644907330026002

In [1303]:
#003 先頭の25行くらいで予測値の補正が必要か分かるからやってみよう

for i in range(0,50):  #0～最終までの行数 25→50
    
    x=X.iloc[i,:] #予測する行番号-----#003で列数確認
    y_pred42=model.predict([x])[0]
    
    # y_pred=round(y_pred) #四捨五入
    y_pred42=math.floor(y_pred42)#切り下げ

    print(i,y_pred42)

0 8314
1 6317
2 9005
3 5729
4 5340
5 7742
6 6363
7 6695
8 8883
9 5219
10 5327
11 4105
12 7003
13 6443
14 5646
15 3164
16 1982
17 5413
18 1558
19 4221
20 8904
21 1113
22 4738
23 2863
24 4105
25 9600
26 6124
27 7543
28 5487
29 3274
30 7014
31 3095
32 4687
33 2374
34 -877
35 3556
36 2838
37 7303
38 4135
39 4744
40 9654
41 4832
42 5788
43 4472
44 1452
45 5085
46 7549
47 6740
48 8137
49 6565

In [1304]:
#004 最終行から25行までをみれば補正が必要かわかる

#最終行番号確認　→　行数あると予測値Textコピペできないので個別に表示_20240816_
k=last_row 
# print(k)

for k in range(k-50,k+1):  #0～最終までの行数 25→50
    
    x=X.iloc[k,:] #予測する行番号-----#003で列数確認
    y_pred42=model.predict([x])[0]
    
    # y_pred=round(y_pred) #四捨五入
    y_pred42=math.floor(y_pred42)#切り下げ

    print(k,y_pred42)

2065 3825
2066 3812
2067 5272
2068 1925
2069 9534
2070 554
2071 6213
2072 3354
2073 3075
2074 4068
2075 4345
2076 3902
2077 2968
2078 -291
2079 3397
2080 3834
2081 5517
2082 3969
2083 2737
2084 3395
2085 4106
2086 4862
2087 4028
2088 1745
2089 4236
2090 3604
2091 5142
2092 2348
2093 3930
2094 1526
2095 -185
2096 3865
2097 4109
2098 7625
2099 3803
2100 442
2101 2851
2102 4139
2103 1714
2104 4113
2105 3537
2106 3987
2107 400
2108 3420
2109 3410
2110 3781
2111 4221
2112 3803
2113 1966
2114 5110
2115 -1190

In [1305]:
#005 予測

i=last_row #最終行番号
x=X.iloc[i,:] #予測する行番号-----#004で列数確認
y_pred42=model.predict([x])[0]

# y_pred=round(y_pred) #四捨五入
y_pred42=math.floor(y_pred42)#切り下げ

print(i,':',y_pred42)

2115 : -1190

In [1306]:
#006 負の値と異常値のときの処理-----20251011_追加して経過を観察してみる-----
if -10000 < y_pred42 < 0:
    # y_pred_num1 = y_pred * 100 #100倍してから桁ごとの数値を取得
    y_pred42 = format(y_pred42, '05.0f') #format関数で5桁の文字列に変換（負の符号も含む）
    n1 = int(str(y_pred42)[-4]) #万の位
    n2 = int(str(y_pred42)[-3]) #千の位
    n3 = int(str(y_pred42)[-2]) #百の位
    n4 = int(str(y_pred42)[-1]) #十の位
    

    print(i,':',n1,n2,n3,n4,':','負の値を補正',y_pred42)

elif y_pred42 > 9999:
    n1 = int(str(y_pred42)[-4]) #万の位
    n2 = int(str(y_pred42)[-3]) #千の位
    n3 = int(str(y_pred42)[-2]) #百の位
    n4 = int(str(y_pred42)[-1]) #十の位

    print(i,':',n1,n2,n3,n4,':','異常値を補正',y_pred42)

elif y_pred42 < -9999:
    print(i,':','負の異常値',y_pred42)

else:
    print(i,':',y_pred42,':','正常値です')

2115 : 1 1 9 0 : 負の値を補正 -1190

In [1307]:
#ここでおわり

In [1308]:
#ここで並べて確認して購入判定しようかな_20260316_
print('00:',y_pred00, ',', '20:',y_pred20, ',', '30:',y_pred30, ',', '42:',y_pred42)

#-----購入判定の条件-----
# y_pred00が1000未満で0以上
# y_pred20が1000未満で0以上
# y_pred30が2000未満で0以上
# y_pred42が1000未満で0以上

#int型に変換してから判定_20260324_
y_pred00=int(y_pred00)
y_pred20=int(y_pred20)
y_pred30=int(y_pred30)
y_pred42=int(y_pred42)

if 10000 > y_pred00 >= 0 and 10000 > y_pred20 >= 0 and 10000 > y_pred30 >= 0 and 10000 > y_pred42 >= 0:
    print('購入判定：購入')
else:
    print('購入判定：見送り')

00: 3105 , 20: 5992 , 30: 4921 , 42: -1190
購入判定：見送り

In [1309]:
#学習ルールを考えた-----2024/8/16-----
#1_全体の予測(Num_3_challenge_6.jpynb)はPC負担軽減のため今後中止にする。2024/8/16～
#2_random_state=(20)で揃える。予測値が異常なときは(42)で行う。
#3_#007 検証のとき、出力値が"1"に近いとよい。#2の(20)で異常値のときはここも異常値である。(42)のときで比較して判断する。

In [1310]:
# #逆換算__エラーでるのでキャンセルする
# result=model.score(x_train,y_train)
# model.inverse_transform(model.predict(result))

In [1311]:
#全体をcheckすると学習時間が長いのでNum_3_challenge_6で行う　→　PC負担大きいため中止

In [1312]:
# #000 ここから回帰分析開始して時間短縮-----20231001-----
# import os
# import pandas as pd
# import numpy as np
# from sklearn.preprocessing import OneHotEncoder

# #docker のときは/workdir/ を追記する
# New_data_dir='/workdir/Num_3_predict/01_output/challenge_5'

# import glob
# Num_3_file=os.path.join(New_data_dir,'/workdir/Num_3_predict/01_output/challenge_5/df_2018_2023.csv')
# Num_3_paths=glob.glob(Num_3_file)
# display(Num_3_paths)

In [1313]:
# #001 csv_data 呼び出して確認
# New_data_dir='/workdir/Num_3_predict/01_output/challenge_5'
# Num_3_predict_dir=os.path.join(New_data_dir)
# Num_3_file='df_2018_2023.csv' #西暦ごとに出力 + #005欠損値も確認
# df=pd.read_csv(os.path.join(Num_3_predict_dir,Num_3_file))
# display(df)

In [1314]:
# #002 説明変数と目的変数に分割-----まとめて出力できないか-----

# for i in range(0,1484): #スタートが0からで1つめ2つめ3つめ、ひとつの数値でもOK、rows行番号でOk
# # for i in range(1482,1483):    
    
#     X=df.iloc[:, :-1]
#     y=df.iloc[:, -1]

#     #モデルの構築と検証---"1"に近いと良い
#     from sklearn.linear_model import LinearRegression
#     model=LinearRegression()
#     model.fit(X,y)
#     # model.score(x,y)

#     #学習
#     from sklearn.model_selection import train_test_split
#     # X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=20)#初期 size=0.4 state=1
#     #-----警告処置-----
#     X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.25,random_state=20)#初期 size=0.4 state=1　#微調整が必要かなsize=0.2→0.25→0.3
#     model.fit(X_train,y_train)
#     model.fit(X_test,y_test)


#     x=X.iloc[i,:] #予測する行番号-----#003で列数確認
#     y_pred=model.predict([x])[0]
#     # y_pred

#     y_pred=round(y_pred)
#     print(i,y_pred)



#     #予測値と比較
#     # from sklearn.metrics import mean_squared_error
#     # y=y.iloc[i,:]
#     # score=mean_squared_error(y_pred,y)
#     # print(score) 



#     #100個で8分
#     #1000個で95分
#     #1482個で133分、211分

# #-----警告処置-----

In [1315]:
# #003 完全一致率を算出----これで楽になるね
# import pandas as pd
# import numpy as np
# from sklearn.metrics import mean_squared_error

# count=0
# score=0
# num=0

# for i in range(0,1484): #スタートが0からで1つめ2つめ3つめ、rows行番号
    
#     y=df.iloc[i, -1]
#     x=X.iloc[i,:] #予測する行番号-----#003で列数確認
#     y_pred=model.predict([x])[0]
#     y_pred=round(y_pred)
#     y_pred

#     if y == y_pred:
#         score += 1
    
#         num = str(i)
#     if num != '':
#         count += 1
       
#     # print(y,y_pred,num)
# print('Total', score, count)

# if count >= score:
#     print(f'Perfect_matching = {score}/{count} ({score/count *100:.1f}%)')