In [119]:
#回帰分析で予測してみるよ_20230909_
#データを作ってみよう

# import pandas as pd
# import numpy as np

#データ編集

# class Num3:
#     def __init__(self):
#         pass
        
        
#     def show(self):
#         pass
        
        
#     if __name__ == '__main__':
#         dataset='/workdir/Num_3_predict/01_output/Num_3_2018_2022.csv'
#         df=pd.read_csv(dataset)
#         print(df)

In [120]:
#重回帰分析で予測してみるよ_20230909_
#001 フォルダー作成
import os
import pandas as pd # type: ignore
import numpy as np # type: ignore
from sklearn.preprocessing import OneHotEncoder # type: ignore

#docker のときは/workdir/ を追記する
data_dir="Num_3_predict"

input_dir=os.path.join(data_dir,"00_input")
output_dir=os.path.join(data_dir,"01_output")
output_results_dir=os.path.join(data_dir,"02_output_results")
master_dir=os.path.join(data_dir,"03_master")

data_dir_2="Num_3_predict/00_input"
data_dir_3="Num_3_predict/01_output"
all_data_dir=os.path.join(data_dir_2,"001_all_data")
all_data_inital_dir=os.path.join(data_dir_2,"001_all_data_inital")
challenge_5_data=os.path.join(data_dir_3,"Challenge_5")
display(input_dir)

'Num_3_predict\\00_input'

In [121]:
#002　フォルダー出力
os.makedirs(input_dir,exist_ok=True)
os.makedirs(output_dir,exist_ok=True)
os.makedirs(output_results_dir,exist_ok=True)
os.makedirs(master_dir,exist_ok=True)

os.makedirs(all_data_dir,exist_ok=True)
os.makedirs(all_data_inital_dir,exist_ok=True)

In [122]:
#003　csv_取得
import glob
# Num_3_file=os.path.join(input_dir,'Num_3_predict/00_input/Num_3_*.csv')
Num_3_file=os.path.join(input_dir,'Num_3_*.csv')
Num_3_paths=glob.glob(Num_3_file)
Num_3_paths=sorted(Num_3_paths)
display(Num_3_paths)

['Num_3_predict\\00_input\\Num_3_2018.csv',
 'Num_3_predict\\00_input\\Num_3_2019.csv',
 'Num_3_predict\\00_input\\Num_3_2020.csv',
 'Num_3_predict\\00_input\\Num_3_2021.csv',
 'Num_3_predict\\00_input\\Num_3_2022.csv',
 'Num_3_predict\\00_input\\Num_3_2023.csv',
 'Num_3_predict\\00_input\\Num_3_2024.csv',
 'Num_3_predict\\00_input\\Num_3_2025.csv',
 'Num_3_predict\\00_input\\Num_3_2026.csv']

In [123]:
#004 csv_data 呼び出して確認
Num_3_predict_dir=os.path.join(data_dir,'00_input')
Num_3_file='Num_3_2026.csv' #西暦ごとに出力 + #005欠損値も確認
Num_3=pd.read_csv(os.path.join(Num_3_predict_dir,Num_3_file))
display(Num_3.head())

   No      date  Lottery_result  hundreds_place  tens_place  ones_place
0   1  2026/1/5             622               6           2           2
1   2  2026/1/6             696               6           9           6
2   3  2026/1/7             620               6           2           0
3   4  2026/1/8             649               6           4           9
4   5  2026/1/9             673               6           7           3

In [124]:
#005 欠損値の確認---どちらでもOK--- 
Num_3.isnull().sum #Falseは欠損なし

<bound method NDFrame._add_numeric_operations.<locals>.sum of        No   date  Lottery_result  hundreds_place  tens_place  ones_place
0   False  False           False           False       False       False
1   False  False           False           False       False       False
2   False  False           False           False       False       False
3   False  False           False           False       False       False
4   False  False           False           False       False       False
5   False  False           False           False       False       False
6   False  False           False           False       False       False
7   False  False           False           False       False       False
8   False  False           False           False       False       False
9   False  False           False           False       False       False
10  False  False           False           False       False       False
11  False  False           False           False       False       False
12  False  False           False           False       False       False
13  False  False           False           False       False       False
14  False  False           False           False       False       False
15  False  False           False           False       False       False
16  False  False           False           False       False       False
17  False  False           False           False       False       False
18  False  False           False           False       False       False
19  False  False           False           False       False       False
20  False  False           False           False       False       False
21  False  False           False           False       False       False
22  False  False           False           False       False       False
23  False  False           False           False       False       False
24  False  False           False           False       False       False
25  False  False           False           False       False       False
26  False  False           False           False       False       False
27  False  False           False           False       False       False
28  False  False           False           False       False       False
29  False  False           False           False       False       False
30  False  False           False           False       False       False
31  False  False           False           False       False       False
32  False  False           False           False       False       False
33  False  False           False           False       False       False
34  False  False           False           False       False       False
35  False  False           False           False       False       False
36  False  False           False           False       False       False
37  False  False           False           False       False       False
38  False  False           False           False       False       False
39  False  False           False           False       False       False
40  False  False           False           False       False       False
41  False  False           False           False       False       False
42  False  False           False           False       False       False
43  False  False           False           False       False       False
44  False  False           False           False       False       False
45  False  False           False           False       False       False
46  False  False           False           False       False       False
47  False  False           False           False       False       False
48  False  False           False           False       False       False
49  False  False           False           False       False       False
50  False  False           False           False       False       False
51  False  False           False           False       False       False
52  False  False           False           False       False       False
53  False  False           False           False       False       False
54  False  False           False           False       False       False
55  False  False           False           False       False       False
56  False  False           False           False       False       False
57  False  False           False           False       False       False>

In [125]:
#006 2018_2023 csvの結合 9年分
import pandas as pd # type: ignore
Num_3_2018_2026=pd.DataFrame()

for file in Num_3_paths:
    Num_3_data=pd.read_csv(file)
    display(f'{file}:{len(Num_3_data)}')
    Num_3_2018_2026=pd.concat([Num_3_2018_2026,Num_3_data],ignore_index=True)

'Num_3_predict\\00_input\\Num_3_2018.csv:257'

'Num_3_predict\\00_input\\Num_3_2019.csv:257'

'Num_3_predict\\00_input\\Num_3_2020.csv:258'

'Num_3_predict\\00_input\\Num_3_2021.csv:259'

'Num_3_predict\\00_input\\Num_3_2022.csv:259'

'Num_3_predict\\00_input\\Num_3_2023.csv:258'

'Num_3_predict\\00_input\\Num_3_2024.csv:259'

'Num_3_predict\\00_input\\Num_3_2025.csv:257'

'Num_3_predict\\00_input\\Num_3_2026.csv:58'

In [126]:
#007 csvファイル確認
Num_3_2018_2026

      No       date  Lottery_result  hundreds_place  tens_place  ones_place
0      1   2018/1/4             858               8           5           8
1      2   2018/1/5             384               3           8           4
2      3   2018/1/8             976               9           7           6
3      4   2018/1/9             930               9           3           0
4      5  2018/1/10             634               6           3           4
...   ..        ...             ...             ...         ...         ...
2117  54  2026/3/19             690               6           9           0
2118  55  2026/3/20             319               3           1           9
2119  56  2026/3/23             191               1           9           1
2120  57  2026/3/24             619               6           1           9
2121  58  2026/3/25             522               5           2           2

[2122 rows x 6 columns]

In [127]:
#008 ファイルの欠損値確認
Num_3_2018_2026.isnull().sum() #0はなし

No                0
date              0
Lottery_result    0
hundreds_place    0
tens_place        0
ones_place        0
dtype: int64

In [128]:
#009 data type 確認
Num_3_2018_2026.dtypes

No                 int64
date              object
Lottery_result     int64
hundreds_place     int64
tens_place         int64
ones_place         int64
dtype: object

In [129]:
#010 dateのobject を datetime に変換
import pandas as pd

Num_3_2018_2026['date']=pd.to_datetime(Num_3_2018_2026['date'])

In [130]:
#011 data type 確認
Num_3_2018_2026.dtypes

No                         int64
date              datetime64[ns]
Lottery_result             int64
hundreds_place             int64
tens_place                 int64
ones_place                 int64
dtype: object

In [131]:
#ここで"Lottery_result" をint型の変換-----20260322機械側メモリー使用を抑えるため-----
Num_3_2018_2026=Num_3_2018_2026.astype({'Lottery_result': 'int32'})

#ほかの列もint型に変換してみる
Num_3_2018_2026=Num_3_2018_2026.astype({'No': 'int32', 'hundreds_place': 'int32', 'tens_place': 'int32', 'ones_place': 'int32'})
print(Num_3_2018_2026.dtypes)

No                         int32
date              datetime64[ns]
Lottery_result             int32
hundreds_place             int32
tens_place                 int32
ones_place                 int32
dtype: object

In [132]:
#012 次回の結果の列を作成 Next_result
#df_add=pd.DataFrame({'Next_result':Num_3_2018_2022.loc[1:1488,'Lottery_result']})#都度、rows=入力する
df_add=pd.DataFrame({'Next_result':Num_3_2018_2026.loc[1::,'Lottery_result']})#2行目から最終行まで
df_add

      Next_result
1             384
2             976
3             930
4             634
5             223
...           ...
2117          690
2118          319
2119          191
2120          619
2121          522

[2121 rows x 1 columns]

In [133]:
#ここでの'Next_result'のint型の確認----先にLottery_resultのint型に変換しているので、Next_resultもint型になっているはず-----
print(df_add.dtypes)

#int型をint64からint32へ変換-----20260322機械側メモリー使用を抑えるため-----
# df_add = df_add.astype({'Next_result': 'int32'})
# print(df_add.dtypes)

Next_result    int32
dtype: object

In [134]:
#013 indexを0から振り直す
df_add=df_add.reset_index()
df_add

      index  Next_result
0         1          384
1         2          976
2         3          930
3         4          634
4         5          223
...     ...          ...
2116   2117          690
2117   2118          319
2118   2119          191
2119   2120          619
2120   2121          522

[2121 rows x 2 columns]

In [135]:
#014 不要な列を削除
drop_col=['index']
df_add_1=df_add.drop(drop_col,axis=1)
df_add_1

      Next_result
0             384
1             976
2             930
3             634
4             223
...           ...
2116          690
2117          319
2118          191
2119          619
2120          522

[2121 rows x 1 columns]

In [136]:
#015 元データの最後の行を削除
Num_3_2018_2026=Num_3_2018_2026.drop(Num_3_2018_2026.index[-1])#初期_index=[1289]---[-1]は最終行
Num_3_2018_2026

      No       date  Lottery_result  hundreds_place  tens_place  ones_place
0      1 2018-01-04             858               8           5           8
1      2 2018-01-05             384               3           8           4
2      3 2018-01-08             976               9           7           6
3      4 2018-01-09             930               9           3           0
4      5 2018-01-10             634               6           3           4
...   ..        ...             ...             ...         ...         ...
2116  53 2026-03-18             128               1           2           8
2117  54 2026-03-19             690               6           9           0
2118  55 2026-03-20             319               3           1           9
2119  56 2026-03-23             191               1           9           1
2120  57 2026-03-24             619               6           1           9

[2121 rows x 6 columns]

In [137]:
#016 元データとNext_result結合
Num_3_2018_2026 = pd.concat([Num_3_2018_2026, df_add_1], axis=1)
Num_3_2018_2026

,No,date,Lottery_result,hundreds_place,tens_place,ones_place,Next_result
0,1,2018-01-04,858,8,5,8,384
1,2,2018-01-05,384,3,8,4,976
2,3,2018-01-08,976,9,7,6,930
3,4,2018-01-09,930,9,3,0,634
4,5,2018-01-10,634,6,3,4,223
...,...,...,...,...,...,...,...
2116,53,2026-03-18,128,1,2,8,690
2117,54,2026-03-19,690,6,9,0,319
2118,55,2026-03-20,319,3,1,9,191
2119,56,2026-03-23,191,1,9,1,619
2120,57,2026-03-24,619,6,1,9,522

In [138]:
#017 作成したファイルをcsvで出力
#data_file='Num_3_2018_2024.csv'
data_file='Num_3_2018_2026.csv'
Num_3_2018_2026.to_csv(os.path.join(challenge_5_data,data_file),index=False)

In [139]:
#018 add three を作成
df_add=pd.DataFrame({'add_three':Num_3_2018_2026[['hundreds_place','tens_place','ones_place']].sum(axis=1)})
df_add

      add_three
0            21
1            15
2            22
3            12
4            13
...         ...
2116         11
2117         15
2118         13
2119         11
2120         16

[2121 rows x 1 columns]

In [140]:
#019 元データとadd_three結合
Num_3_2018_2026 = pd.concat([Num_3_2018_2026, df_add], axis=1)
Num_3_2018_2026

,No,date,Lottery_result,hundreds_place,tens_place,ones_place,Next_result,add_three
0,1,2018-01-04,858,8,5,8,384,21
1,2,2018-01-05,384,3,8,4,976,15
2,3,2018-01-08,976,9,7,6,930,22
3,4,2018-01-09,930,9,3,0,634,12
4,5,2018-01-10,634,6,3,4,223,13
...,...,...,...,...,...,...,...,...
2116,53,2026-03-18,128,1,2,8,690,11
2117,54,2026-03-19,690,6,9,0,319,15
2118,55,2026-03-20,319,3,1,9,191,13
2119,56,2026-03-23,191,1,9,1,619,11
2120,57,2026-03-24,619,6,1,9,522,16

In [141]:
#020 曜日変数を取得
Num_3_2018_2026['day_of_week']=Num_3_2018_2026['date'].dt.day_of_week
Num_3_2018_2026

,No,date,Lottery_result,hundreds_place,tens_place,ones_place,Next_result,add_three,day_of_week
0,1,2018-01-04,858,8,5,8,384,21,3
1,2,2018-01-05,384,3,8,4,976,15,4
2,3,2018-01-08,976,9,7,6,930,22,0
3,4,2018-01-09,930,9,3,0,634,12,1
4,5,2018-01-10,634,6,3,4,223,13,2
...,...,...,...,...,...,...,...,...,...
2116,53,2026-03-18,128,1,2,8,690,11,2
2117,54,2026-03-19,690,6,9,0,319,15,3
2118,55,2026-03-20,319,3,1,9,191,13,4
2119,56,2026-03-23,191,1,9,1,619,11,0
2120,57,2026-03-24,619,6,1,9,522,16,1

In [142]:
#021 統計量の算出
Num_3_2018_2026.describe()

,No,Lottery_result,hundreds_place,tens_place,ones_place,Next_result,add_three,day_of_week
count,2121.000000,2121.000000,2121.000000,2121.000000,2121.000000,2121.000000,2121.000000,2121.000000
mean,126.750589,501.658180,4.522395,4.492692,4.491749,501.499764,13.506836,1.999529
std,75.262124,290.975608,2.899348,2.858959,2.928721,290.872959,4.897446,1.416380
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,60.000000,247.000000,2.000000,2.000000,2.000000,247.000000,10.000000,1.000000
50%,126.000000,495.000000,4.000000,4.000000,4.000000,495.000000,14.000000,2.000000
75%,192.000000,752.000000,7.000000,7.000000,7.000000,751.000000,17.000000,3.000000
max,259.000000,998.000000,9.000000,9.000000,9.000000,998.000000,26.000000,5.000000

In [143]:
#022 分布グラフの確認__時間かかるからコメントアウト
# import seaborn as sns
# sns.displot(Num_3_2018_2022['Lottery_result'],bins=20,kde=True)
# sns.displot(Num_3_2018_2022['hundreds_place'],bins=10,kde=True)
# sns.displot(Num_3_2018_2022['tens_place'],bins=10,kde=True)
# sns.displot(Num_3_2018_2022['ones_place'],bins=10,kde=True)
# sns.displot(Num_3_2018_2022['day_of_week'],bins=10,kde=True)
# sns.displot(Num_3_2018_2022['add_three'],bins=20,kde=True)#傾向あり

In [144]:
#023 相関をグラフ確認__時間かかるからコメントアウト
# sns.pairplot(Num_3_2018_2022)

In [145]:
#024 曜日と曜日の変数と年を取得
Num_3_2018_2026['day_name']=Num_3_2018_2026['date'].dt.day_name() #曜日名
Num_3_2018_2026['year']=Num_3_2018_2026['date'].dt.year
Num_3_2018_2026

,No,date,Lottery_result,hundreds_place,tens_place,ones_place,Next_result,add_three,day_of_week,day_name,year
0,1,2018-01-04,858,8,5,8,384,21,3,Thursday,2018
1,2,2018-01-05,384,3,8,4,976,15,4,Friday,2018
2,3,2018-01-08,976,9,7,6,930,22,0,Monday,2018
3,4,2018-01-09,930,9,3,0,634,12,1,Tuesday,2018
4,5,2018-01-10,634,6,3,4,223,13,2,Wednesday,2018
...,...,...,...,...,...,...,...,...,...,...,...
2116,53,2026-03-18,128,1,2,8,690,11,2,Wednesday,2026
2117,54,2026-03-19,690,6,9,0,319,15,3,Thursday,2026
2118,55,2026-03-20,319,3,1,9,191,13,4,Friday,2026
2119,56,2026-03-23,191,1,9,1,619,11,0,Monday,2026
2120,57,2026-03-24,619,6,1,9,522,16,1,Tuesday,2026

In [146]:
#025 ここで「百+十」結合の列をいれる-----20240506 初期は年も結合して年毎でカウントする作戦を変更-----最後で列は消す-----「+」の列を追加20240713---20240803---
#hundreds+tenの6年のとき異常な数値が頻繁に発生したので戻し検討中-----20240828----- なので年ごとの百の位の出現回数に戻す

Num_3_2018_2026 = pd.DataFrame(Num_3_2018_2026)
t1 = Num_3_2018_2026['hundreds_place']
t2 = Num_3_2018_2026['year']
# t3 = Num_3_2018_2023['tens_place']

# df_test['hp_year_join'] = t1.astype(str) + t3.astype(str) + t2.astype(str)
# df_test = pd.DataFrame(t1.astype(str) + t3.astype(str), columns=['hundreds+ten'])#カラム名追加
df_test = pd.DataFrame(t1.astype(str) + t2.astype(str), columns=['hundreds+year'])#カラム名追加

df_test

     hundreds+year
0            82018
1            32018
2            92018
3            92018
4            62018
...            ...
2116         12026
2117         62026
2118         32026
2119         12026
2120         62026

[2121 rows x 1 columns]

In [147]:
#026-----文字型からint型に変更する----
df_test = df_test.astype(int)
df_test

      hundreds+year
0             82018
1             32018
2             92018
3             92018
4             62018
...             ...
2116          12026
2117          62026
2118          32026
2119          12026
2120          62026

[2121 rows x 1 columns]

In [148]:
#027-----参考で8年間の2桁の出現頻度をカウント--- Max38回だから40回で変数化でいこう-----   20240831--出現回数だけを変数化でいこう-----
# df_test_count = pd.DataFrame({'6year_count': df_test.loc[:,'hundreds+ten'].value_counts()})
df_test_count = pd.DataFrame({'8year_count': df_test.loc[:,'hundreds+year'].value_counts()})

df_test_count

       8year_count
72021           38
92022           37
62019           35
72019           34
12023           34
...            ...
52026            4
72026            3
22026            3
82026            3
2026             2

[90 rows x 1 columns]

In [149]:
#Test-----ここでhundreds_placeの8年間の出現頻度をカウントを確認-----Max204回だからこのままの数値を変数化、なんだか百の位の出現頻度を同じ変数のようなので保留-----2024/8/31-----
df_test_count_next = pd.DataFrame({'8year_count_next': Num_3_2018_2026.loc[:,'hundreds_place'].value_counts()})

df_test_count_next

   8year_count_next
9               237
6               228
3               221
4               219
1               214
0               214
7               202
2               201
8               199
5               186

In [150]:
#028----ここで元データとhundreds+tenを結合-----  20240831----ここで元データとhundreds+yearを結合に更新-----
Num_3_2018_2026 = pd.concat([Num_3_2018_2026, df_test], axis=1)
Num_3_2018_2026

,No,date,Lottery_result,hundreds_place,tens_place,ones_place,Next_result,add_three,day_of_week,day_name,year,hundreds+year
0,1,2018-01-04,858,8,5,8,384,21,3,Thursday,2018,82018
1,2,2018-01-05,384,3,8,4,976,15,4,Friday,2018,32018
2,3,2018-01-08,976,9,7,6,930,22,0,Monday,2018,92018
3,4,2018-01-09,930,9,3,0,634,12,1,Tuesday,2018,92018
4,5,2018-01-10,634,6,3,4,223,13,2,Wednesday,2018,62018
...,...,...,...,...,...,...,...,...,...,...,...,...
2116,53,2026-03-18,128,1,2,8,690,11,2,Wednesday,2026,12026
2117,54,2026-03-19,690,6,9,0,319,15,3,Thursday,2026,62026
2118,55,2026-03-20,319,3,1,9,191,13,4,Friday,2026,32026
2119,56,2026-03-23,191,1,9,1,619,11,0,Monday,2026,12026
2120,57,2026-03-24,619,6,1,9,522,16,1,Tuesday,2026,62026

In [151]:
#029-----hundreds+ten　を取得して新しい出現回数列追加_2桁(twodigits)のカウンターを追加20240803-----　20240831-----hundreds+yearの出現回数へ戻す-----

import collections
# list_num = Num_3_2018_2023['hundreds+ten']
list_num = Num_3_2018_2026['hundreds+year']

df1=collections.Counter(list_num)

# new_column = [df1[item] for item in Num_3_2018_2023['hundreds+ten'].tolist()]
new_column = [df1[item] for item in Num_3_2018_2026['hundreds+year'].tolist()]
Num_3_2018_2026['td_ct'] = new_column
Num_3_2018_2026

,No,date,Lottery_result,hundreds_place,tens_place,ones_place,Next_result,add_three,day_of_week,day_name,year,hundreds+year,td_ct
0,1,2018-01-04,858,8,5,8,384,21,3,Thursday,2018,82018,16
1,2,2018-01-05,384,3,8,4,976,15,4,Friday,2018,32018,33
2,3,2018-01-08,976,9,7,6,930,22,0,Monday,2018,92018,31
3,4,2018-01-09,930,9,3,0,634,12,1,Tuesday,2018,92018,31
4,5,2018-01-10,634,6,3,4,223,13,2,Wednesday,2018,62018,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,53,2026-03-18,128,1,2,8,690,11,2,Wednesday,2026,12026,6
2117,54,2026-03-19,690,6,9,0,319,15,3,Thursday,2026,62026,11
2118,55,2026-03-20,319,3,1,9,191,13,4,Friday,2026,32026,7
2119,56,2026-03-23,191,1,9,1,619,11,0,Monday,2026,12026,6
2120,57,2026-03-24,619,6,1,9,522,16,1,Tuesday,2026,62026,11

In [152]:
#030-----td_ctをダミー変数化35回で-----40回へ更新

import os
import pandas as pd # type: ignore
import numpy as np # type: ignore
from sklearn.preprocessing import OneHotEncoder # type: ignore

df_n=range(0,41,1)

counter_list=df_n
enc=OneHotEncoder(categories=[counter_list],sparse_output=False)
counter_d=enc.fit_transform(Num_3_2018_2026[['td_ct']])
df_counter_td=pd.DataFrame(counter_d,index=Num_3_2018_2026.index,columns=counter_list,dtype='int')

df_counter_td

#警告コメントは将来非推奨になるので注意ということ→ 20251231_sparse=False から sparse_output=False に変更

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2117,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2118,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2119,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2120,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [153]:
#031-----Namberのカラム名の変更twodigit_count----初期は直接記載したけど増えたので一括処理に更新-----hundreds+yearに更新

for i in range(41):
        name=('td_ct' + str(i))
   
        df_counter_td = df_counter_td.rename(columns={i: name})
        
df_counter_td

,td_ct0,td_ct1,td_ct2,td_ct3,td_ct4,td_ct5,td_ct6,td_ct7,td_ct8,td_ct9,...,td_ct31,td_ct32,td_ct33,td_ct34,td_ct35,td_ct36,td_ct37,td_ct38,td_ct39,td_ct40
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2117,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2118,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2119,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2120,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [154]:
#032-----元データとhundred+ten の　td_ct　ダミー変数を結合-----
Num_3_2018_2026 = pd.concat([Num_3_2018_2026, df_counter_td], axis=1)
Num_3_2018_2026

,No,date,Lottery_result,hundreds_place,tens_place,ones_place,Next_result,add_three,day_of_week,day_name,...,td_ct31,td_ct32,td_ct33,td_ct34,td_ct35,td_ct36,td_ct37,td_ct38,td_ct39,td_ct40
0,1,2018-01-04,858,8,5,8,384,21,3,Thursday,...,0,0,0,0,0,0,0,0,0,0
1,2,2018-01-05,384,3,8,4,976,15,4,Friday,...,0,0,1,0,0,0,0,0,0,0
2,3,2018-01-08,976,9,7,6,930,22,0,Monday,...,1,0,0,0,0,0,0,0,0,0
3,4,2018-01-09,930,9,3,0,634,12,1,Tuesday,...,1,0,0,0,0,0,0,0,0,0
4,5,2018-01-10,634,6,3,4,223,13,2,Wednesday,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,53,2026-03-18,128,1,2,8,690,11,2,Wednesday,...,0,0,0,0,0,0,0,0,0,0
2117,54,2026-03-19,690,6,9,0,319,15,3,Thursday,...,0,0,0,0,0,0,0,0,0,0
2118,55,2026-03-20,319,3,1,9,191,13,4,Friday,...,0,0,0,0,0,0,0,0,0,0
2119,56,2026-03-23,191,1,9,1,619,11,0,Monday,...,0,0,0,0,0,0,0,0,0,0
2120,57,2026-03-24,619,6,1,9,522,16,1,Tuesday,...,0,0,0,0,0,0,0,0,0,0

In [155]:
#033 8年間の出現頻度をカウント-----Namberの数を知る
df_add=pd.DataFrame({'8year_ago':Num_3_2018_2026.loc[:,'Lottery_result'].value_counts()})
df_add

     8year_ago
684          8
118          8
355          7
60           7
461          7
..         ...
662          1
402          1
851          1
34           1
690          1

[876 rows x 1 columns]

In [156]:
#034 8年間のdataをカウント
df_add=pd.DataFrame({'year_data':Num_3_2018_2026.loc[:,'year'].value_counts()})
df_add

      year_data
2021        259
2022        259
2024        259
2025        259
2020        258
2023        258
2018        257
2019        257
2026         55

In [157]:
#035 8年間の3桁数字の頻度をカウント__Namberの数を知る
df_add_0=pd.DataFrame({'2018_ago':Num_3_2018_2026.loc[0:257,'Lottery_result'].value_counts()})#+257
df_add_1=pd.DataFrame({'2019_ago':Num_3_2018_2026.loc[258:514,'Lottery_result'].value_counts()})#258+256=514
df_add_2=pd.DataFrame({'2020_ago':Num_3_2018_2026.loc[515:772,'Lottery_result'].value_counts()})#515+25=772
df_add_3=pd.DataFrame({'2021_ago':Num_3_2018_2026.loc[773:1031,'Lottery_result'].value_counts()})#773+258=1031
df_add_4=pd.DataFrame({'2022_ago':Num_3_2018_2026.loc[1032:1289,'Lottery_result'].value_counts()})#1032+258=1290
df_add_5=pd.DataFrame({'2023_ago':Num_3_2018_2026.loc[1291:1548,'Lottery_result'].value_counts()})#1291+257=1548

# df_add_5=pd.DataFrame({'2023_ago':Num_3_2018_2022.loc[1290:1487,'Lottery_result'].value_counts()})#行数を更新する
df_add_6=pd.DataFrame({'2024_ago':Num_3_2018_2026.loc[1549:1807,'Lottery_result'].value_counts()})#1290行～最終行までに更新　→1549+258=1807
df_add_7=pd.DataFrame({'2025_ago':Num_3_2018_2026.loc[1808:2065,'Lottery_result'].value_counts()})#1808行～最終行までに更新 →1808+257=2065
df_add_8=pd.DataFrame({'2026_ago':Num_3_2018_2026.loc[2066::,'Lottery_result'].value_counts()})#2066行～最終行までに更新

print(df_add_0)
print(df_add_1)
print(df_add_2)
print(df_add_3)
print(df_add_4)
print(df_add_5)
print(df_add_6)
print(df_add_7)
print(df_add_8)

     2018_ago
46          3
234         3
223         3
271         3
589         3
..        ...
851         1
934         1
109         1
531         1
804         1

[222 rows x 1 columns]
     2019_ago
856         3
79          3
755         2
814         2
626         2
..        ...
314         1
129         1
25          1
193         1
721         1

[226 rows x 1 columns]
     2020_ago
445         2
998         2
697         2
461         2
996         2
..        ...
325         1
803         1
406         1
663         1
13          1

[233 rows x 1 columns]
     2021_ago
398         3
931         3
53          3
240         3
635         3
..        ...
270         1
855         1
130         1
151         1
394         1

[226 rows x 1 columns]
     2022_ago
394         3
988         3
529         3
947         2
274         2
..        ...
408         1
713         1
264         1
612         1
958         1

[224 rows x 1 columns]
     2023_ago
484         3
840         2
928         2
41          2
60          2
..        ...
746         1
218         1
140         1
464         1
13          1

[230 rows x 1 columns]
     2024_ago
91          3
834         2
495         2
546         2
810         2
..        ...
186         1
219         1
943         1
872         1
188         1

[230 rows x 1 columns]
     2025_ago
249         3
652         3
990         3
157         3
238         2
..        ...
263         1
680         1
902         1
564         1
696         1

[230 rows x 1 columns]
     2026_ago
388         2
620         1
903         1
135         1
918         1
843         1
490         1
99          1
123         1
682         1
132         1
731         1
971         1
314         1
269         1
413         1
917         1
540         1
614         1
670         1
423         1
834         1
128         1
690         1
319         1
191         1
979         1
758         1
649         1
493         1
673         1
982         1
784         1
325         1
345         1
597         1
590         1
932         1
949         1
527         1
443         1
643         1
73          1
447         1
461         1
37          1
105         1
160         1
470         1
316         1
293         1
224         1
827         1
619         1

In [158]:
#036-----参考_8年間の百位の頻度をカウント__hundreds_placeの数を知る_2024/3/9
df_add_h0=pd.DataFrame({'2018_ago':Num_3_2018_2026.loc[0:257,'hundreds_place'].value_counts()})
df_add_h1=pd.DataFrame({'2019_ago':Num_3_2018_2026.loc[258:514,'hundreds_place'].value_counts()})
df_add_h2=pd.DataFrame({'2020_ago':Num_3_2018_2026.loc[515:772,'hundreds_place'].value_counts()})
df_add_h3=pd.DataFrame({'2021_ago':Num_3_2018_2026.loc[773:1031,'hundreds_place'].value_counts()})
df_add_h4=pd.DataFrame({'2022_ago':Num_3_2018_2026.loc[1032:1289,'hundreds_place'].value_counts()})
df_add_h5=pd.DataFrame({'2023_ago':Num_3_2018_2026.loc[1290:1548,'hundreds_place'].value_counts()})

# df_add_5=pd.DataFrame({'2023_ago':Num_3_2018_2022.loc[1290:1487,'Lottery_result'].value_counts()})#行数を更新する
df_add_h6=pd.DataFrame({'2024_ago':Num_3_2018_2026.loc[1549:1807,'hundreds_place'].value_counts()})#1290行～最終行までに更新　→1549+258=1807
df_add_h7=pd.DataFrame({'2025_ago':Num_3_2018_2026.loc[1808:2065,'hundreds_place'].value_counts()})#1808行～最終行までに更新 →1808+257=2065
df_add_h8=pd.DataFrame({'2026_ago':Num_3_2018_2026.loc[2066::,'hundreds_place'].value_counts()})#2066行～最終行までに更新

print(df_add_h0)
print(df_add_h1)
print(df_add_h2)
print(df_add_h3)
print(df_add_h4)
print(df_add_h5)
print(df_add_h6)
print(df_add_h7)
print(df_add_h8)

   2018_ago
3        33
2        32
9        31
0        31
4        28
1        27
6        21
5        19
7        19
8        17
   2019_ago
6        35
7        34
9        29
8        28
0        25
3        25
1        22
2        21
5        19
4        19
   2020_ago
9        32
4        31
3        30
8        29
1        25
6        25
5        23
0        22
7        21
2        20
   2021_ago
7        38
0        31
9        27
2        25
6        25
5        24
3        23
1        23
4        22
8        21
   2022_ago
9        37
6        30
4        28
0        26
5        25
3        24
7        23
2        22
8        22
1        21
   2023_ago
1        34
0        30
4        28
2        27
5        27
6        26
9        24
3        23
8        21
7        19
   2024_ago
3        31
4        30
9        30
8        30
0        25
7        23
6        23
1        23
5        22
2        22
   2025_ago
6        34
1        32
2        29
8        28
4        25
3        25
5        23
7        22
0        21
9        19
   2026_ago
6         9
9         8
4         8
3         7
1         7
5         4
7         3
0         3
2         3
8         3

In [159]:
#037----- Nambarの出現をダミー変数化する基本的な構文
df=range(0,1000,1)
# Num_list=pd.DataFrame(columns=df,dtype='int')
Num_list=df
enc=OneHotEncoder(categories=[Num_list],sparse_output=False)
Num_d=enc.fit_transform(Num_3_2018_2026[['Lottery_result']])
df_Num=pd.DataFrame(Num_d,index=Num_3_2018_2026.index,columns=Num_list,dtype='int')
df_Num

#警告コメントは将来非推奨になるので注意ということ→ 20251231_sparse=False から sparse_output=False に変更

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2117,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2118,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2119,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2120,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [160]:
#038----- Numberのカラム名取得
df=df_Num.columns.values
df

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558,
       559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571,
       572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584,
       585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610,
       611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623,
       624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
       637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
       650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662,
       663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675,
       676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688,
       689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701,
       702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714,
       715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727,
       728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740,
       741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753,
       754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766,
       767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779,
       780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792,
       793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805,
       806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818,
       819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831,
       832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844,
       845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857,
       858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870,
       871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883,
       884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896,
       897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909,
       910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922,
       923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935,
       936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948,
       949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961,
       962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974,
       975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987,
       988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999],
      dtype=int64)

In [161]:
#039----- Namberのカラム名の変更----初期は直接記載したけど増えたので一括処理に更新

for i in range(1000):
        name=('num_' + str(i))
   
        df_Num=df_Num.rename(columns={i: name})
        
df_Num

# df=df_Num.rename(columns={0:'num_0',1:'num_1',2:'num_2',3:'num_3',4:'num_4',5:'num_5',6:'num_6',7:'num_7',8:'num_8',9:'num_9',10:'num_10',
#                           11:'num_11',12:'num_12',13:'num_13',14:'num_14',15:'num_15',16:'num_16',17:'num_17',18:'num_18',19:'num_19',20:'num_20',
#                           21:'num_21',22:'num_22',23:'num_23',24:'num_24',25:'num_25',26:'num_26',27:'num_27',28:'num_28',29:'num_29',30:'num_30',
#                           31:'num_31',32:'num_32',33:'num_33',34:'num_34',35:'num_34',36:'num_36',37:'num_37',38:'num_38',39:'num_39',40:'num_40',
#                           41:'num_41',42:'num_42',43:'num_43',44:'num_44',45:'num_45',46:'num_46',47:'num_47',48:'num_48',49:'num_49',50:'num_50',
#                           51:'num_51',52:'num_52',53:'num_0',54:'num_0',55:'num_0',56:'num_0',57:'num_0',58:'num_0',59:'num_0',60:'num_60',
#                           61:'num_61',62:'num_62',63:'num_63',64:'num_64',65:'num_65',66:'num_66',67:'num_67',68:'num_68',69:'num_69',70:'num_70',
#                           71:'num_71',72:'num_72',73:'num_0',74:'num_74',75:'num_75',76:'num_76',77:'num_77',78:'num_78',79:'num_79',80:'num_80',
#                           81:'num_81',82:'num_82',83:'num_83',84:'num_84',85:'num_85',86:'num_86',87:'num_87',88:'num_88',89:'num_89',90:'num_90',
#                           91:'num_91',92:'num_92',93:'num_93',94:'num_94',95:'num_95',96:'num_96',97:'num_97',98:'num_98',99:'num_0',100:'num_100',
#                           101:'num_100',102:'num_100',103:'num_100',104:'num_100',105:'num_100',106:'num_100',107:'num_100',108:'num_100',109:'num_100',110:'num_100',
#                           111:'num_111',112:'num_112',113:'num_113',114:'num_114',115:'num_115',116:'num_116',117:'num_117',118:'num_118',119:'num_119',120:'num_120',
#                           121:'num_121',122:'num_122',123:'num_123',124:'num_124',125:'num_125',126:'num_126',127:'num_127',128:'num_128',129:'num_129',130:'num_130',
#                           131:'num_131',132:'num_132',133:'num_133',134:'num_134',135:'num_134',136:'num_136',137:'num_137',138:'num_138',139:'num_139',140:'num_140',
#                           141:'num_141',142:'num_142',143:'num_143',144:'num_144',145:'num_145',146:'num_146',147:'num_147',148:'num_148',149:'num_149',150:'num_150',
#                           151:'num_151',152:'num_152',153:'num_153',154:'num_154',155:'num_155',156:'num_156',157:'num_157',158:'num_158',159:'num_159',160:'num_160',
#                           161:'num_161',162:'num_162',163:'num_163',164:'num_164',165:'num_165',166:'num_166',167:'num_167',168:'num_168',169:'num_169',170:'num_170',
#                           171:'num_171',172:'num_172',173:'num_173',174:'num_714',175:'num_175',176:'num_176',177:'num_177',178:'num_178',179:'num_179',180:'num_180',
#                           181:'num_181',182:'num_182',183:'num_183',84:'num_184',185:'num_185',186:'num_186',187:'num_187',188:'num_188',189:'num_189',190:'num_190',
#                           191:'num_191',192:'num_192',193:'num_193',194:'num_194',195:'num_195',196:'num_196',197:'num_197',198:'num_198',199:'num_199',200:'num_200',
#                           201:'num_201',202:'num_202',203:'num_203',204:'num_204',205:'num_205',206:'num_206',207:'num_207',208:'num_208',209:'num_209',210:'num_210',


#                  991, 992, 993, 994, 995, 996, 997, 998, 999})
# df

,num_0,num_1,num_2,num_3,num_4,num_5,num_6,num_7,num_8,num_9,...,num_990,num_991,num_992,num_993,num_994,num_995,num_996,num_997,num_998,num_999
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2117,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2118,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2119,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2120,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [162]:
#040----- カラム名を確認
df=df_Num.columns.values
df

array(['num_0', 'num_1', 'num_2', 'num_3', 'num_4', 'num_5', 'num_6',
       'num_7', 'num_8', 'num_9', 'num_10', 'num_11', 'num_12', 'num_13',
       'num_14', 'num_15', 'num_16', 'num_17', 'num_18', 'num_19',
       'num_20', 'num_21', 'num_22', 'num_23', 'num_24', 'num_25',
       'num_26', 'num_27', 'num_28', 'num_29', 'num_30', 'num_31',
       'num_32', 'num_33', 'num_34', 'num_35', 'num_36', 'num_37',
       'num_38', 'num_39', 'num_40', 'num_41', 'num_42', 'num_43',
       'num_44', 'num_45', 'num_46', 'num_47', 'num_48', 'num_49',
       'num_50', 'num_51', 'num_52', 'num_53', 'num_54', 'num_55',
       'num_56', 'num_57', 'num_58', 'num_59', 'num_60', 'num_61',
       'num_62', 'num_63', 'num_64', 'num_65', 'num_66', 'num_67',
       'num_68', 'num_69', 'num_70', 'num_71', 'num_72', 'num_73',
       'num_74', 'num_75', 'num_76', 'num_77', 'num_78', 'num_79',
       'num_80', 'num_81', 'num_82', 'num_83', 'num_84', 'num_85',
       'num_86', 'num_87', 'num_88', 'num_89', 'num_90', 'num_91',
       'num_92', 'num_93', 'num_94', 'num_95', 'num_96', 'num_97',
       'num_98', 'num_99', 'num_100', 'num_101', 'num_102', 'num_103',
       'num_104', 'num_105', 'num_106', 'num_107', 'num_108', 'num_109',
       'num_110', 'num_111', 'num_112', 'num_113', 'num_114', 'num_115',
       'num_116', 'num_117', 'num_118', 'num_119', 'num_120', 'num_121',
       'num_122', 'num_123', 'num_124', 'num_125', 'num_126', 'num_127',
       'num_128', 'num_129', 'num_130', 'num_131', 'num_132', 'num_133',
       'num_134', 'num_135', 'num_136', 'num_137', 'num_138', 'num_139',
       'num_140', 'num_141', 'num_142', 'num_143', 'num_144', 'num_145',
       'num_146', 'num_147', 'num_148', 'num_149', 'num_150', 'num_151',
       'num_152', 'num_153', 'num_154', 'num_155', 'num_156', 'num_157',
       'num_158', 'num_159', 'num_160', 'num_161', 'num_162', 'num_163',
       'num_164', 'num_165', 'num_166', 'num_167', 'num_168', 'num_169',
       'num_170', 'num_171', 'num_172', 'num_173', 'num_174', 'num_175',
       'num_176', 'num_177', 'num_178', 'num_179', 'num_180', 'num_181',
       'num_182', 'num_183', 'num_184', 'num_185', 'num_186', 'num_187',
       'num_188', 'num_189', 'num_190', 'num_191', 'num_192', 'num_193',
       'num_194', 'num_195', 'num_196', 'num_197', 'num_198', 'num_199',
       'num_200', 'num_201', 'num_202', 'num_203', 'num_204', 'num_205',
       'num_206', 'num_207', 'num_208', 'num_209', 'num_210', 'num_211',
       'num_212', 'num_213', 'num_214', 'num_215', 'num_216', 'num_217',
       'num_218', 'num_219', 'num_220', 'num_221', 'num_222', 'num_223',
       'num_224', 'num_225', 'num_226', 'num_227', 'num_228', 'num_229',
       'num_230', 'num_231', 'num_232', 'num_233', 'num_234', 'num_235',
       'num_236', 'num_237', 'num_238', 'num_239', 'num_240', 'num_241',
       'num_242', 'num_243', 'num_244', 'num_245', 'num_246', 'num_247',
       'num_248', 'num_249', 'num_250', 'num_251', 'num_252', 'num_253',
       'num_254', 'num_255', 'num_256', 'num_257', 'num_258', 'num_259',
       'num_260', 'num_261', 'num_262', 'num_263', 'num_264', 'num_265',
       'num_266', 'num_267', 'num_268', 'num_269', 'num_270', 'num_271',
       'num_272', 'num_273', 'num_274', 'num_275', 'num_276', 'num_277',
       'num_278', 'num_279', 'num_280', 'num_281', 'num_282', 'num_283',
       'num_284', 'num_285', 'num_286', 'num_287', 'num_288', 'num_289',
       'num_290', 'num_291', 'num_292', 'num_293', 'num_294', 'num_295',
       'num_296', 'num_297', 'num_298', 'num_299', 'num_300', 'num_301',
       'num_302', 'num_303', 'num_304', 'num_305', 'num_306', 'num_307',
       'num_308', 'num_309', 'num_310', 'num_311', 'num_312', 'num_313',
       'num_314', 'num_315', 'num_316', 'num_317', 'num_318', 'num_319',
       'num_320', 'num_321', 'num_322', 'num_323', 'num_324', 'num_325',
       'num_326', 'num_327', 'num_328', 'num_329', 'num_330', 'num_331',
       'num_332', 'num_333', 'num_334', 'num_335', 'num_336', 'num_337',
       'num_338', 'num_339', 'num_340', 'num_341', 'num_342', 'num_343',
       'num_344', 'num_345', 'num_346', 'num_347', 'num_348', 'num_349',
       'num_350', 'num_351', 'num_352', 'num_353', 'num_354', 'num_355',
       'num_356', 'num_357', 'num_358', 'num_359', 'num_360', 'num_361',
       'num_362', 'num_363', 'num_364', 'num_365', 'num_366', 'num_367',
       'num_368', 'num_369', 'num_370', 'num_371', 'num_372', 'num_373',
       'num_374', 'num_375', 'num_376', 'num_377', 'num_378', 'num_379',
       'num_380', 'num_381', 'num_382', 'num_383', 'num_384', 'num_385',
       'num_386', 'num_387', 'num_388', 'num_389', 'num_390', 'num_391',
       'num_392', 'num_393', 'num_394', 'num_395', 'num_396', 'num_397',
       'num_398', 'num_399', 'num_400', 'num_401', 'num_402', 'num_403',
       'num_404', 'num_405', 'num_406', 'num_407', 'num_408', 'num_409',
       'num_410', 'num_411', 'num_412', 'num_413', 'num_414', 'num_415',
       'num_416', 'num_417', 'num_418', 'num_419', 'num_420', 'num_421',
       'num_422', 'num_423', 'num_424', 'num_425', 'num_426', 'num_427',
       'num_428', 'num_429', 'num_430', 'num_431', 'num_432', 'num_433',
       'num_434', 'num_435', 'num_436', 'num_437', 'num_438', 'num_439',
       'num_440', 'num_441', 'num_442', 'num_443', 'num_444', 'num_445',
       'num_446', 'num_447', 'num_448', 'num_449', 'num_450', 'num_451',
       'num_452', 'num_453', 'num_454', 'num_455', 'num_456', 'num_457',
       'num_458', 'num_459', 'num_460', 'num_461', 'num_462', 'num_463',
       'num_464', 'num_465', 'num_466', 'num_467', 'num_468', 'num_469',
       'num_470', 'num_471', 'num_472', 'num_473', 'num_474', 'num_475',
       'num_476', 'num_477', 'num_478', 'num_479', 'num_480', 'num_481',
       'num_482', 'num_483', 'num_484', 'num_485', 'num_486', 'num_487',
       'num_488', 'num_489', 'num_490', 'num_491', 'num_492', 'num_493',
       'num_494', 'num_495', 'num_496', 'num_497', 'num_498', 'num_499',
       'num_500', 'num_501', 'num_502', 'num_503', 'num_504', 'num_505',
       'num_506', 'num_507', 'num_508', 'num_509', 'num_510', 'num_511',
       'num_512', 'num_513', 'num_514', 'num_515', 'num_516', 'num_517',
       'num_518', 'num_519', 'num_520', 'num_521', 'num_522', 'num_523',
       'num_524', 'num_525', 'num_526', 'num_527', 'num_528', 'num_529',
       'num_530', 'num_531', 'num_532', 'num_533', 'num_534', 'num_535',
       'num_536', 'num_537', 'num_538', 'num_539', 'num_540', 'num_541',
       'num_542', 'num_543', 'num_544', 'num_545', 'num_546', 'num_547',
       'num_548', 'num_549', 'num_550', 'num_551', 'num_552', 'num_553',
       'num_554', 'num_555', 'num_556', 'num_557', 'num_558', 'num_559',
       'num_560', 'num_561', 'num_562', 'num_563', 'num_564', 'num_565',
       'num_566', 'num_567', 'num_568', 'num_569', 'num_570', 'num_571',
       'num_572', 'num_573', 'num_574', 'num_575', 'num_576', 'num_577',
       'num_578', 'num_579', 'num_580', 'num_581', 'num_582', 'num_583',
       'num_584', 'num_585', 'num_586', 'num_587', 'num_588', 'num_589',
       'num_590', 'num_591', 'num_592', 'num_593', 'num_594', 'num_595',
       'num_596', 'num_597', 'num_598', 'num_599', 'num_600', 'num_601',
       'num_602', 'num_603', 'num_604', 'num_605', 'num_606', 'num_607',
       'num_608', 'num_609', 'num_610', 'num_611', 'num_612', 'num_613',
       'num_614', 'num_615', 'num_616', 'num_617', 'num_618', 'num_619',
       'num_620', 'num_621', 'num_622', 'num_623', 'num_624', 'num_625',
       'num_626', 'num_627', 'num_628', 'num_629', 'num_630', 'num_631',
       'num_632', 'num_633', 'num_634', 'num_635', 'num_636', 'num_637',
       'num_638', 'num_639', 'num_640', 'num_641', 'num_642', 'num_643',
       'num_644', 'num_645', 'num_646', 'num_647', 'num_648', 'num_649',
       'num_650', 'num_651', 'num_652', 'num_653', 'num_654', 'num_655',
       'num_656', 'num_657', 'num_658', 'num_659', 'num_660', 'num_661',
       'num_662', 'num_663', 'num_664', 'num_665', 'num_666', 'num_667',
       'num_668', 'num_669', 'num_670', 'num_671', 'num_672', 'num_673',
       'num_674', 'num_675', 'num_676', 'num_677', 'num_678', 'num_679',
       'num_680', 'num_681', 'num_682', 'num_683', 'num_684', 'num_685',
       'num_686', 'num_687', 'num_688', 'num_689', 'num_690', 'num_691',
       'num_692', 'num_693', 'num_694', 'num_695', 'num_696', 'num_697',
       'num_698', 'num_699', 'num_700', 'num_701', 'num_702', 'num_703',
       'num_704', 'num_705', 'num_706', 'num_707', 'num_708', 'num_709',
       'num_710', 'num_711', 'num_712', 'num_713', 'num_714', 'num_715',
       'num_716', 'num_717', 'num_718', 'num_719', 'num_720', 'num_721',
       'num_722', 'num_723', 'num_724', 'num_725', 'num_726', 'num_727',
       'num_728', 'num_729', 'num_730', 'num_731', 'num_732', 'num_733',
       'num_734', 'num_735', 'num_736', 'num_737', 'num_738', 'num_739',
       'num_740', 'num_741', 'num_742', 'num_743', 'num_744', 'num_745',
       'num_746', 'num_747', 'num_748', 'num_749', 'num_750', 'num_751',
       'num_752', 'num_753', 'num_754', 'num_755', 'num_756', 'num_757',
       'num_758', 'num_759', 'num_760', 'num_761', 'num_762', 'num_763',
       'num_764', 'num_765', 'num_766', 'num_767', 'num_768', 'num_769',
       'num_770', 'num_771', 'num_772', 'num_773', 'num_774', 'num_775',
       'num_776', 'num_777', 'num_778', 'num_779', 'num_780', 'num_781',
       'num_782', 'num_783', 'num_784', 'num_785', 'num_786', 'num_787',
       'num_788', 'num_789', 'num_790', 'num_791', 'num_792', 'num_793',
       'num_794', 'num_795', 'num_796', 'num_797', 'num_798', 'num_799',
       'num_800', 'num_801', 'num_802', 'num_803', 'num_804', 'num_805',
       'num_806', 'num_807', 'num_808', 'num_809', 'num_810', 'num_811',
       'num_812', 'num_813', 'num_814', 'num_815', 'num_816', 'num_817',
       'num_818', 'num_819', 'num_820', 'num_821', 'num_822', 'num_823',
       'num_824', 'num_825', 'num_826', 'num_827', 'num_828', 'num_829',
       'num_830', 'num_831', 'num_832', 'num_833', 'num_834', 'num_835',
       'num_836', 'num_837', 'num_838', 'num_839', 'num_840', 'num_841',
       'num_842', 'num_843', 'num_844', 'num_845', 'num_846', 'num_847',
       'num_848', 'num_849', 'num_850', 'num_851', 'num_852', 'num_853',
       'num_854', 'num_855', 'num_856', 'num_857', 'num_858', 'num_859',
       'num_860', 'num_861', 'num_862', 'num_863', 'num_864', 'num_865',
       'num_866', 'num_867', 'num_868', 'num_869', 'num_870', 'num_871',
       'num_872', 'num_873', 'num_874', 'num_875', 'num_876', 'num_877',
       'num_878', 'num_879', 'num_880', 'num_881', 'num_882', 'num_883',
       'num_884', 'num_885', 'num_886', 'num_887', 'num_888', 'num_889',
       'num_890', 'num_891', 'num_892', 'num_893', 'num_894', 'num_895',
       'num_896', 'num_897', 'num_898', 'num_899', 'num_900', 'num_901',
       'num_902', 'num_903', 'num_904', 'num_905', 'num_906', 'num_907',
       'num_908', 'num_909', 'num_910', 'num_911', 'num_912', 'num_913',
       'num_914', 'num_915', 'num_916', 'num_917', 'num_918', 'num_919',
       'num_920', 'num_921', 'num_922', 'num_923', 'num_924', 'num_925',
       'num_926', 'num_927', 'num_928', 'num_929', 'num_930', 'num_931',
       'num_932', 'num_933', 'num_934', 'num_935', 'num_936', 'num_937',
       'num_938', 'num_939', 'num_940', 'num_941', 'num_942', 'num_943',
       'num_944', 'num_945', 'num_946', 'num_947', 'num_948', 'num_949',
       'num_950', 'num_951', 'num_952', 'num_953', 'num_954', 'num_955',
       'num_956', 'num_957', 'num_958', 'num_959', 'num_960', 'num_961',
       'num_962', 'num_963', 'num_964', 'num_965', 'num_966', 'num_967',
       'num_968', 'num_969', 'num_970', 'num_971', 'num_972', 'num_973',
       'num_974', 'num_975', 'num_976', 'num_977', 'num_978', 'num_979',
       'num_980', 'num_981', 'num_982', 'num_983', 'num_984', 'num_985',
       'num_986', 'num_987', 'num_988', 'num_989', 'num_990', 'num_991',
       'num_992', 'num_993', 'num_994', 'num_995', 'num_996', 'num_997',
       'num_998', 'num_999'], dtype=object)

In [163]:
#041----- 元データとNumberダミー変数を結合
Num_3_2018_2026 = pd.concat([Num_3_2018_2026, df_Num], axis=1)
Num_3_2018_2026

,No,date,Lottery_result,hundreds_place,tens_place,ones_place,Next_result,add_three,day_of_week,day_name,...,num_990,num_991,num_992,num_993,num_994,num_995,num_996,num_997,num_998,num_999
0,1,2018-01-04,858,8,5,8,384,21,3,Thursday,...,0,0,0,0,0,0,0,0,0,0
1,2,2018-01-05,384,3,8,4,976,15,4,Friday,...,0,0,0,0,0,0,0,0,0,0
2,3,2018-01-08,976,9,7,6,930,22,0,Monday,...,0,0,0,0,0,0,0,0,0,0
3,4,2018-01-09,930,9,3,0,634,12,1,Tuesday,...,0,0,0,0,0,0,0,0,0,0
4,5,2018-01-10,634,6,3,4,223,13,2,Wednesday,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,53,2026-03-18,128,1,2,8,690,11,2,Wednesday,...,0,0,0,0,0,0,0,0,0,0
2117,54,2026-03-19,690,6,9,0,319,15,3,Thursday,...,0,0,0,0,0,0,0,0,0,0
2118,55,2026-03-20,319,3,1,9,191,13,4,Friday,...,0,0,0,0,0,0,0,0,0,0
2119,56,2026-03-23,191,1,9,1,619,11,0,Monday,...,0,0,0,0,0,0,0,0,0,0
2120,57,2026-03-24,619,6,1,9,522,16,1,Tuesday,...,0,0,0,0,0,0,0,0,0,0

In [164]:
#042----- hundreds_placeのダミー変数化
hundreds_place_list=['0','1','2','3','4','5','6','7','8','9']
enc=OneHotEncoder(categories=[hundreds_place_list],sparse_output=False)
hundreds_place_d=enc.fit_transform(Num_3_2018_2026[['hundreds_place']])
df_hundreds_place_d=pd.DataFrame(hundreds_place_d,index=Num_3_2018_2026.index,columns=hundreds_place_list,dtype='int')
df_hundreds_place_d

#警告コメントは将来非推奨になるので注意ということ→ 20251231_sparse=False から sparse_output=False に変更

      0  1  2  3  4  5  6  7  8  9
0     0  0  0  0  0  0  0  0  1  0
1     0  0  0  1  0  0  0  0  0  0
2     0  0  0  0  0  0  0  0  0  1
3     0  0  0  0  0  0  0  0  0  1
4     0  0  0  0  0  0  1  0  0  0
...  .. .. .. .. .. .. .. .. .. ..
2116  0  1  0  0  0  0  0  0  0  0
2117  0  0  0  0  0  0  1  0  0  0
2118  0  0  0  1  0  0  0  0  0  0
2119  0  1  0  0  0  0  0  0  0  0
2120  0  0  0  0  0  0  1  0  0  0

[2121 rows x 10 columns]

In [165]:
#043----- hundreds_placeのダミー変数列名の変更
df_hundreds_place_d=df_hundreds_place_d.rename(columns={'0':'h_0','1':'h_1','2':'h_2','3':'h_3','4':'h_4','5':'h_5','6':'h_6','7':'h_7','8':'h_8','9':'h_9'})
df_hundreds_place_d

      h_0  h_1  h_2  h_3  h_4  h_5  h_6  h_7  h_8  h_9
0       0    0    0    0    0    0    0    0    1    0
1       0    0    0    1    0    0    0    0    0    0
2       0    0    0    0    0    0    0    0    0    1
3       0    0    0    0    0    0    0    0    0    1
4       0    0    0    0    0    0    1    0    0    0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
2116    0    1    0    0    0    0    0    0    0    0
2117    0    0    0    0    0    0    1    0    0    0
2118    0    0    0    1    0    0    0    0    0    0
2119    0    1    0    0    0    0    0    0    0    0
2120    0    0    0    0    0    0    1    0    0    0

[2121 rows x 10 columns]

In [166]:
#044----- 元データとhundreds_place変数を結合
Num_3_2018_2026 = pd.concat([Num_3_2018_2026, df_hundreds_place_d], axis=1)
Num_3_2018_2026

,No,date,Lottery_result,hundreds_place,tens_place,ones_place,Next_result,add_three,day_of_week,day_name,...,h_0,h_1,h_2,h_3,h_4,h_5,h_6,h_7,h_8,h_9
0,1,2018-01-04,858,8,5,8,384,21,3,Thursday,...,0,0,0,0,0,0,0,0,1,0
1,2,2018-01-05,384,3,8,4,976,15,4,Friday,...,0,0,0,1,0,0,0,0,0,0
2,3,2018-01-08,976,9,7,6,930,22,0,Monday,...,0,0,0,0,0,0,0,0,0,1
3,4,2018-01-09,930,9,3,0,634,12,1,Tuesday,...,0,0,0,0,0,0,0,0,0,1
4,5,2018-01-10,634,6,3,4,223,13,2,Wednesday,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,53,2026-03-18,128,1,2,8,690,11,2,Wednesday,...,0,1,0,0,0,0,0,0,0,0
2117,54,2026-03-19,690,6,9,0,319,15,3,Thursday,...,0,0,0,0,0,0,1,0,0,0
2118,55,2026-03-20,319,3,1,9,191,13,4,Friday,...,0,0,0,1,0,0,0,0,0,0
2119,56,2026-03-23,191,1,9,1,619,11,0,Monday,...,0,1,0,0,0,0,0,0,0,0
2120,57,2026-03-24,619,6,1,9,522,16,1,Tuesday,...,0,0,0,0,0,0,1,0,0,0

In [167]:
#045----- tens_placeのダミー変数化
tens_place_list=['0','1','2','3','4','5','6','7','8','9']
enc=OneHotEncoder(categories=[tens_place_list],sparse_output=False)
tens_place_d=enc.fit_transform(Num_3_2018_2026[['tens_place']])
df_tens_place_d=pd.DataFrame(tens_place_d,index=Num_3_2018_2026.index,columns=tens_place_list,dtype='int')
df_tens_place_d

#警告コメントは将来非推奨になるので注意ということ→ 20251231_sparse=False から sparse_output=False に変更

      0  1  2  3  4  5  6  7  8  9
0     0  0  0  0  0  1  0  0  0  0
1     0  0  0  0  0  0  0  0  1  0
2     0  0  0  0  0  0  0  1  0  0
3     0  0  0  1  0  0  0  0  0  0
4     0  0  0  1  0  0  0  0  0  0
...  .. .. .. .. .. .. .. .. .. ..
2116  0  0  1  0  0  0  0  0  0  0
2117  0  0  0  0  0  0  0  0  0  1
2118  0  1  0  0  0  0  0  0  0  0
2119  0  0  0  0  0  0  0  0  0  1
2120  0  1  0  0  0  0  0  0  0  0

[2121 rows x 10 columns]

In [168]:
#046----- tens_placeのダミー変数列名の変更
df_tens_place_d=df_tens_place_d.rename(columns={'0':'t_0','1':'t_1','2':'t_2','3':'t_3','4':'t_4','5':'t_5','6':'t_6','7':'t_7','8':'t_8','9':'t_9'})
df_tens_place_d

      t_0  t_1  t_2  t_3  t_4  t_5  t_6  t_7  t_8  t_9
0       0    0    0    0    0    1    0    0    0    0
1       0    0    0    0    0    0    0    0    1    0
2       0    0    0    0    0    0    0    1    0    0
3       0    0    0    1    0    0    0    0    0    0
4       0    0    0    1    0    0    0    0    0    0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
2116    0    0    1    0    0    0    0    0    0    0
2117    0    0    0    0    0    0    0    0    0    1
2118    0    1    0    0    0    0    0    0    0    0
2119    0    0    0    0    0    0    0    0    0    1
2120    0    1    0    0    0    0    0    0    0    0

[2121 rows x 10 columns]

In [169]:
#047----- 元データとtens_place変数を結合
Num_3_2018_2026 = pd.concat([Num_3_2018_2026, df_tens_place_d], axis=1)
Num_3_2018_2026

,No,date,Lottery_result,hundreds_place,tens_place,ones_place,Next_result,add_three,day_of_week,day_name,...,t_0,t_1,t_2,t_3,t_4,t_5,t_6,t_7,t_8,t_9
0,1,2018-01-04,858,8,5,8,384,21,3,Thursday,...,0,0,0,0,0,1,0,0,0,0
1,2,2018-01-05,384,3,8,4,976,15,4,Friday,...,0,0,0,0,0,0,0,0,1,0
2,3,2018-01-08,976,9,7,6,930,22,0,Monday,...,0,0,0,0,0,0,0,1,0,0
3,4,2018-01-09,930,9,3,0,634,12,1,Tuesday,...,0,0,0,1,0,0,0,0,0,0
4,5,2018-01-10,634,6,3,4,223,13,2,Wednesday,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,53,2026-03-18,128,1,2,8,690,11,2,Wednesday,...,0,0,1,0,0,0,0,0,0,0
2117,54,2026-03-19,690,6,9,0,319,15,3,Thursday,...,0,0,0,0,0,0,0,0,0,1
2118,55,2026-03-20,319,3,1,9,191,13,4,Friday,...,0,1,0,0,0,0,0,0,0,0
2119,56,2026-03-23,191,1,9,1,619,11,0,Monday,...,0,0,0,0,0,0,0,0,0,1
2120,57,2026-03-24,619,6,1,9,522,16,1,Tuesday,...,0,1,0,0,0,0,0,0,0,0

In [170]:
#048----- ones_placeのダミー変数化
ones_place_list=['0','1','2','3','4','5','6','7','8','9']
enc=OneHotEncoder(categories=[ones_place_list],sparse_output=False)
ones_place_d=enc.fit_transform(Num_3_2018_2026[['ones_place']])
df_ones_place_d=pd.DataFrame(ones_place_d,index=Num_3_2018_2026.index,columns=ones_place_list,dtype='int')
df_ones_place_d

#警告コメントは将来非推奨になるので注意ということ→ 20251231_sparse=False から sparse_output=False に変更

      0  1  2  3  4  5  6  7  8  9
0     0  0  0  0  0  0  0  0  1  0
1     0  0  0  0  1  0  0  0  0  0
2     0  0  0  0  0  0  1  0  0  0
3     1  0  0  0  0  0  0  0  0  0
4     0  0  0  0  1  0  0  0  0  0
...  .. .. .. .. .. .. .. .. .. ..
2116  0  0  0  0  0  0  0  0  1  0
2117  1  0  0  0  0  0  0  0  0  0
2118  0  0  0  0  0  0  0  0  0  1
2119  0  1  0  0  0  0  0  0  0  0
2120  0  0  0  0  0  0  0  0  0  1

[2121 rows x 10 columns]

In [171]:
#049----- ones_placeのダミー変数列名の変更
df_ones_place_d=df_ones_place_d.rename(columns={'0':'o_0','1':'o_1','2':'o_2','3':'o_3','4':'o_4','5':'o_5','6':'o_6','7':'o_7','8':'o_8','9':'o_9'})
df_ones_place_d

      o_0  o_1  o_2  o_3  o_4  o_5  o_6  o_7  o_8  o_9
0       0    0    0    0    0    0    0    0    1    0
1       0    0    0    0    1    0    0    0    0    0
2       0    0    0    0    0    0    1    0    0    0
3       1    0    0    0    0    0    0    0    0    0
4       0    0    0    0    1    0    0    0    0    0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
2116    0    0    0    0    0    0    0    0    1    0
2117    1    0    0    0    0    0    0    0    0    0
2118    0    0    0    0    0    0    0    0    0    1
2119    0    1    0    0    0    0    0    0    0    0
2120    0    0    0    0    0    0    0    0    0    1

[2121 rows x 10 columns]

In [172]:
#050----- 元データとones_place変数を結合
Num_3_2018_2026 = pd.concat([Num_3_2018_2026, df_ones_place_d], axis=1)
Num_3_2018_2026

,No,date,Lottery_result,hundreds_place,tens_place,ones_place,Next_result,add_three,day_of_week,day_name,...,o_0,o_1,o_2,o_3,o_4,o_5,o_6,o_7,o_8,o_9
0,1,2018-01-04,858,8,5,8,384,21,3,Thursday,...,0,0,0,0,0,0,0,0,1,0
1,2,2018-01-05,384,3,8,4,976,15,4,Friday,...,0,0,0,0,1,0,0,0,0,0
2,3,2018-01-08,976,9,7,6,930,22,0,Monday,...,0,0,0,0,0,0,1,0,0,0
3,4,2018-01-09,930,9,3,0,634,12,1,Tuesday,...,1,0,0,0,0,0,0,0,0,0
4,5,2018-01-10,634,6,3,4,223,13,2,Wednesday,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,53,2026-03-18,128,1,2,8,690,11,2,Wednesday,...,0,0,0,0,0,0,0,0,1,0
2117,54,2026-03-19,690,6,9,0,319,15,3,Thursday,...,1,0,0,0,0,0,0,0,0,0
2118,55,2026-03-20,319,3,1,9,191,13,4,Friday,...,0,0,0,0,0,0,0,0,0,1
2119,56,2026-03-23,191,1,9,1,619,11,0,Monday,...,0,1,0,0,0,0,0,0,0,0
2120,57,2026-03-24,619,6,1,9,522,16,1,Tuesday,...,0,0,0,0,0,0,0,0,0,1

In [173]:
#051----- 曜日のダミー変数化
week_list=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
enc=OneHotEncoder(categories=[week_list],sparse_output=False)
week_d=enc.fit_transform(Num_3_2018_2026[['day_name']])
df_week_d=pd.DataFrame(week_d,index=Num_3_2018_2026.index,columns=week_list,dtype='int')
df_week_d

#警告コメントは将来非推奨になるので注意ということ→ 20251231_sparse=False から sparse_output=False に変更

      Sunday  Monday  Tuesday  Wednesday  Thursday  Friday  Saturday
0          0       0        0          0         1       0         0
1          0       0        0          0         0       1         0
2          0       1        0          0         0       0         0
3          0       0        1          0         0       0         0
4          0       0        0          1         0       0         0
...      ...     ...      ...        ...       ...     ...       ...
2116       0       0        0          1         0       0         0
2117       0       0        0          0         1       0         0
2118       0       0        0          0         0       1         0
2119       0       1        0          0         0       0         0
2120       0       0        1          0         0       0         0

[2121 rows x 7 columns]

In [174]:
#052------ 元データとday_of_week変数を結合
Num_3_2018_2026 = pd.concat([Num_3_2018_2026, df_week_d], axis=1)
Num_3_2018_2026

,No,date,Lottery_result,hundreds_place,tens_place,ones_place,Next_result,add_three,day_of_week,day_name,...,o_7,o_8,o_9,Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday
0,1,2018-01-04,858,8,5,8,384,21,3,Thursday,...,0,1,0,0,0,0,0,1,0,0
1,2,2018-01-05,384,3,8,4,976,15,4,Friday,...,0,0,0,0,0,0,0,0,1,0
2,3,2018-01-08,976,9,7,6,930,22,0,Monday,...,0,0,0,0,1,0,0,0,0,0
3,4,2018-01-09,930,9,3,0,634,12,1,Tuesday,...,0,0,0,0,0,1,0,0,0,0
4,5,2018-01-10,634,6,3,4,223,13,2,Wednesday,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,53,2026-03-18,128,1,2,8,690,11,2,Wednesday,...,0,1,0,0,0,0,1,0,0,0
2117,54,2026-03-19,690,6,9,0,319,15,3,Thursday,...,0,0,0,0,0,0,0,1,0,0
2118,55,2026-03-20,319,3,1,9,191,13,4,Friday,...,0,0,1,0,0,0,0,0,1,0
2119,56,2026-03-23,191,1,9,1,619,11,0,Monday,...,0,0,0,0,1,0,0,0,0,0
2120,57,2026-03-24,619,6,1,9,522,16,1,Tuesday,...,0,0,1,0,0,1,0,0,0,0

In [175]:
#053----- yearごとのダミー変数化
year_list=['2018','2019','2020','2021','2022','2023','2024','2025','2026']
enc=OneHotEncoder(categories=[year_list],sparse_output=False)
year_d=enc.fit_transform(Num_3_2018_2026[['year']])
df_year=pd.DataFrame(year_d,index=Num_3_2018_2026.index,columns=year_list,dtype='int')
df_year

#警告コメントは将来非推奨になるので注意ということ→ 20251231_sparse=False から sparse_output=False に変更

      2018  2019  2020  2021  2022  2023  2024  2025  2026
0        1     0     0     0     0     0     0     0     0
1        1     0     0     0     0     0     0     0     0
2        1     0     0     0     0     0     0     0     0
3        1     0     0     0     0     0     0     0     0
4        1     0     0     0     0     0     0     0     0
...    ...   ...   ...   ...   ...   ...   ...   ...   ...
2116     0     0     0     0     0     0     0     0     1
2117     0     0     0     0     0     0     0     0     1
2118     0     0     0     0     0     0     0     0     1
2119     0     0     0     0     0     0     0     0     1
2120     0     0     0     0     0     0     0     0     1

[2121 rows x 9 columns]

In [176]:
#054----- 元データとyear変数を結合
Num_3_2018_2026 = pd.concat([Num_3_2018_2026, df_year], axis=1)
Num_3_2018_2026

,No,date,Lottery_result,hundreds_place,tens_place,ones_place,Next_result,add_three,day_of_week,day_name,...,Saturday,2018,2019,2020,2021,2022,2023,2024,2025,2026
0,1,2018-01-04,858,8,5,8,384,21,3,Thursday,...,0,1,0,0,0,0,0,0,0,0
1,2,2018-01-05,384,3,8,4,976,15,4,Friday,...,0,1,0,0,0,0,0,0,0,0
2,3,2018-01-08,976,9,7,6,930,22,0,Monday,...,0,1,0,0,0,0,0,0,0,0
3,4,2018-01-09,930,9,3,0,634,12,1,Tuesday,...,0,1,0,0,0,0,0,0,0,0
4,5,2018-01-10,634,6,3,4,223,13,2,Wednesday,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,53,2026-03-18,128,1,2,8,690,11,2,Wednesday,...,0,0,0,0,0,0,0,0,0,1
2117,54,2026-03-19,690,6,9,0,319,15,3,Thursday,...,0,0,0,0,0,0,0,0,0,1
2118,55,2026-03-20,319,3,1,9,191,13,4,Friday,...,0,0,0,0,0,0,0,0,0,1
2119,56,2026-03-23,191,1,9,1,619,11,0,Monday,...,0,0,0,0,0,0,0,0,0,1
2120,57,2026-03-24,619,6,1,9,522,16,1,Tuesday,...,0,0,0,0,0,0,0,0,0,1

In [177]:
#055----- 3桁のSUMダミー変数化
add_three_list=['0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27']
enc=OneHotEncoder(categories=[add_three_list],sparse_output=False)
add_three_d=enc.fit_transform(Num_3_2018_2026[['add_three']])
df_add_three=pd.DataFrame(add_three_d,index=Num_3_2018_2026.index,columns=add_three_list,dtype='int')
df_add_three

#警告コメントは将来非推奨になるので注意ということ→ 20251231_sparse=False から sparse_output=False に変更

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2117,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2118,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2119,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2120,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [178]:
#056----- 3桁のSUMダミー変数列名の変更
df_add_three_new=df_add_three.rename(columns={'0':'add_0','1':'add_1','2':'add_2','3':'add_3','4':'add_4','5':'add_5','6':'add_6','7':'add_7','8':'add_8','9':'add_9',
                                              '10':'add_10','11':'add_11','12':'add_12','13':'add_13','14':'add_14','15':'add_15','16':'add_16','17':'add_17','18':'add_18','19':'add_19',
                                              '20':'add_20','21':'add_21','22':'add_22','23':'add_23','24':'add_24','25':'add_25','26':'add_26','27':'add_27'})
df_add_three_new

,add_0,add_1,add_2,add_3,add_4,add_5,add_6,add_7,add_8,add_9,...,add_18,add_19,add_20,add_21,add_22,add_23,add_24,add_25,add_26,add_27
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2117,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2118,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2119,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2120,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [179]:
#057----- 元データとadd_three変数を結合
Num_3_2018_2026 = pd.concat([Num_3_2018_2026, df_add_three_new], axis=1)
Num_3_2018_2026

,No,date,Lottery_result,hundreds_place,tens_place,ones_place,Next_result,add_three,day_of_week,day_name,...,add_18,add_19,add_20,add_21,add_22,add_23,add_24,add_25,add_26,add_27
0,1,2018-01-04,858,8,5,8,384,21,3,Thursday,...,0,0,0,1,0,0,0,0,0,0
1,2,2018-01-05,384,3,8,4,976,15,4,Friday,...,0,0,0,0,0,0,0,0,0,0
2,3,2018-01-08,976,9,7,6,930,22,0,Monday,...,0,0,0,0,1,0,0,0,0,0
3,4,2018-01-09,930,9,3,0,634,12,1,Tuesday,...,0,0,0,0,0,0,0,0,0,0
4,5,2018-01-10,634,6,3,4,223,13,2,Wednesday,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,53,2026-03-18,128,1,2,8,690,11,2,Wednesday,...,0,0,0,0,0,0,0,0,0,0
2117,54,2026-03-19,690,6,9,0,319,15,3,Thursday,...,0,0,0,0,0,0,0,0,0,0
2118,55,2026-03-20,319,3,1,9,191,13,4,Friday,...,0,0,0,0,0,0,0,0,0,0
2119,56,2026-03-23,191,1,9,1,619,11,0,Monday,...,0,0,0,0,0,0,0,0,0,0
2120,57,2026-03-24,619,6,1,9,522,16,1,Tuesday,...,0,0,0,0,0,0,0,0,0,0

In [180]:
#058----- データ確認
Num_3_2018_2026

,No,date,Lottery_result,hundreds_place,tens_place,ones_place,Next_result,add_three,day_of_week,day_name,...,add_18,add_19,add_20,add_21,add_22,add_23,add_24,add_25,add_26,add_27
0,1,2018-01-04,858,8,5,8,384,21,3,Thursday,...,0,0,0,1,0,0,0,0,0,0
1,2,2018-01-05,384,3,8,4,976,15,4,Friday,...,0,0,0,0,0,0,0,0,0,0
2,3,2018-01-08,976,9,7,6,930,22,0,Monday,...,0,0,0,0,1,0,0,0,0,0
3,4,2018-01-09,930,9,3,0,634,12,1,Tuesday,...,0,0,0,0,0,0,0,0,0,0
4,5,2018-01-10,634,6,3,4,223,13,2,Wednesday,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,53,2026-03-18,128,1,2,8,690,11,2,Wednesday,...,0,0,0,0,0,0,0,0,0,0
2117,54,2026-03-19,690,6,9,0,319,15,3,Thursday,...,0,0,0,0,0,0,0,0,0,0
2118,55,2026-03-20,319,3,1,9,191,13,4,Friday,...,0,0,0,0,0,0,0,0,0,0
2119,56,2026-03-23,191,1,9,1,619,11,0,Monday,...,0,0,0,0,0,0,0,0,0,0
2120,57,2026-03-24,619,6,1,9,522,16,1,Tuesday,...,0,0,0,0,0,0,0,0,0,0

In [181]:
#059----- counter_dataを取得して新しい出現回数列追加_#25の出現回数以上であることね_→#33の7年間の出現回数のこと
#20231115_Reo_アドバイス_counter

import collections
list_num = Num_3_2018_2026['Lottery_result']
df1=collections.Counter(list_num)

new_column = [df1[item] for item in Num_3_2018_2026['Lottery_result'].tolist()]
Num_3_2018_2026['counter'] = new_column
Num_3_2018_2026

,No,date,Lottery_result,hundreds_place,tens_place,ones_place,Next_result,add_three,day_of_week,day_name,...,add_19,add_20,add_21,add_22,add_23,add_24,add_25,add_26,add_27,counter
0,1,2018-01-04,858,8,5,8,384,21,3,Thursday,...,0,0,1,0,0,0,0,0,0,3
1,2,2018-01-05,384,3,8,4,976,15,4,Friday,...,0,0,0,0,0,0,0,0,0,2
2,3,2018-01-08,976,9,7,6,930,22,0,Monday,...,0,0,0,1,0,0,0,0,0,1
3,4,2018-01-09,930,9,3,0,634,12,1,Tuesday,...,0,0,0,0,0,0,0,0,0,5
4,5,2018-01-10,634,6,3,4,223,13,2,Wednesday,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,53,2026-03-18,128,1,2,8,690,11,2,Wednesday,...,0,0,0,0,0,0,0,0,0,3
2117,54,2026-03-19,690,6,9,0,319,15,3,Thursday,...,0,0,0,0,0,0,0,0,0,1
2118,55,2026-03-20,319,3,1,9,191,13,4,Friday,...,0,0,0,0,0,0,0,0,0,5
2119,56,2026-03-23,191,1,9,1,619,11,0,Monday,...,0,0,0,0,0,0,0,0,0,2
2120,57,2026-03-24,619,6,1,9,522,16,1,Tuesday,...,0,0,0,0,0,0,0,0,0,3

In [182]:
#060----- dataのcounterをダミー変数化（10回で)
import os
import pandas as pd # type: ignore
import numpy as np # type: ignore
from sklearn.preprocessing import OneHotEncoder # type: ignore

df_n=range(0,11,1)

counter_list=df_n
enc=OneHotEncoder(categories=[counter_list],sparse_output=False)
counter_d=enc.fit_transform(Num_3_2018_2026[['counter']])
df_counter=pd.DataFrame(counter_d,index=Num_3_2018_2026.index,columns=counter_list,dtype='int')

df_counter

#警告コメントは将来非推奨になるので注意ということ→ 20251231_sparse=False から sparse_output=False に変更

      0   1   2   3   4   5   6   7   8   9   10
0      0   0   0   1   0   0   0   0   0   0   0
1      0   0   1   0   0   0   0   0   0   0   0
2      0   1   0   0   0   0   0   0   0   0   0
3      0   0   0   0   0   1   0   0   0   0   0
4      0   1   0   0   0   0   0   0   0   0   0
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
2116   0   0   0   1   0   0   0   0   0   0   0
2117   0   1   0   0   0   0   0   0   0   0   0
2118   0   0   0   0   0   1   0   0   0   0   0
2119   0   0   1   0   0   0   0   0   0   0   0
2120   0   0   0   1   0   0   0   0   0   0   0

[2121 rows x 11 columns]

In [183]:
#061----- columns名の変更
for i in range(11):
        name=('counter_' + str(i))
        df_counter=df_counter.rename(columns={i: name})
        
df_counter

,counter_0,counter_1,counter_2,counter_3,counter_4,counter_5,counter_6,counter_7,counter_8,counter_9,counter_10
0,0,0,0,1,0,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0,0,0,0
4,0,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
2116,0,0,0,1,0,0,0,0,0,0,0
2117,0,1,0,0,0,0,0,0,0,0,0
2118,0,0,0,0,0,1,0,0,0,0,0
2119,0,0,1,0,0,0,0,0,0,0,0
2120,0,0,0,1,0,0,0,0,0,0,0

In [184]:
#062----- 元データとcounter変数を結合
Num_3_2018_2026 = pd.concat([Num_3_2018_2026, df_counter], axis=1)
Num_3_2018_2026

,No,date,Lottery_result,hundreds_place,tens_place,ones_place,Next_result,add_three,day_of_week,day_name,...,counter_1,counter_2,counter_3,counter_4,counter_5,counter_6,counter_7,counter_8,counter_9,counter_10
0,1,2018-01-04,858,8,5,8,384,21,3,Thursday,...,0,0,1,0,0,0,0,0,0,0
1,2,2018-01-05,384,3,8,4,976,15,4,Friday,...,0,1,0,0,0,0,0,0,0,0
2,3,2018-01-08,976,9,7,6,930,22,0,Monday,...,1,0,0,0,0,0,0,0,0,0
3,4,2018-01-09,930,9,3,0,634,12,1,Tuesday,...,0,0,0,0,1,0,0,0,0,0
4,5,2018-01-10,634,6,3,4,223,13,2,Wednesday,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,53,2026-03-18,128,1,2,8,690,11,2,Wednesday,...,0,0,1,0,0,0,0,0,0,0
2117,54,2026-03-19,690,6,9,0,319,15,3,Thursday,...,1,0,0,0,0,0,0,0,0,0
2118,55,2026-03-20,319,3,1,9,191,13,4,Friday,...,0,0,0,0,1,0,0,0,0,0
2119,56,2026-03-23,191,1,9,1,619,11,0,Monday,...,0,1,0,0,0,0,0,0,0,0
2120,57,2026-03-24,619,6,1,9,522,16,1,Tuesday,...,0,0,1,0,0,0,0,0,0,0

In [185]:
#空き

In [186]:
#063-----参考---hundreds_place counter テストして_2024/3/9_参考になるので、最後で消しておいて影響しないようにしておこう

import collections
list_num = Num_3_2018_2026['hundreds_place']
df1 = collections.Counter(list_num)

new_column = [df1[item] for item in Num_3_2018_2026['hundreds_place'].tolist()]
Num_3_2018_2026['counter_h'] = new_column
Num_3_2018_2026

,No,date,Lottery_result,hundreds_place,tens_place,ones_place,Next_result,add_three,day_of_week,day_name,...,counter_2,counter_3,counter_4,counter_5,counter_6,counter_7,counter_8,counter_9,counter_10,counter_h
0,1,2018-01-04,858,8,5,8,384,21,3,Thursday,...,0,1,0,0,0,0,0,0,0,199
1,2,2018-01-05,384,3,8,4,976,15,4,Friday,...,1,0,0,0,0,0,0,0,0,221
2,3,2018-01-08,976,9,7,6,930,22,0,Monday,...,0,0,0,0,0,0,0,0,0,237
3,4,2018-01-09,930,9,3,0,634,12,1,Tuesday,...,0,0,0,1,0,0,0,0,0,237
4,5,2018-01-10,634,6,3,4,223,13,2,Wednesday,...,0,0,0,0,0,0,0,0,0,228
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,53,2026-03-18,128,1,2,8,690,11,2,Wednesday,...,0,1,0,0,0,0,0,0,0,214
2117,54,2026-03-19,690,6,9,0,319,15,3,Thursday,...,0,0,0,0,0,0,0,0,0,228
2118,55,2026-03-20,319,3,1,9,191,13,4,Friday,...,0,0,0,1,0,0,0,0,0,221
2119,56,2026-03-23,191,1,9,1,619,11,0,Monday,...,1,0,0,0,0,0,0,0,0,214
2120,57,2026-03-24,619,6,1,9,522,16,1,Tuesday,...,0,1,0,0,0,0,0,0,0,228

In [187]:
#064----- 不要な列を削除_Noは削除してLottery_resultは残す_20231118_
Num_3_2018_2026=Num_3_2018_2026.drop(columns=['No','date','add_three','day_of_week','day_name','year','hundreds_place','tens_place','ones_place','counter','counter_h','hundreds+year','td_ct'])
Num_3_2018_2026

,Lottery_result,Next_result,td_ct0,td_ct1,td_ct2,td_ct3,td_ct4,td_ct5,td_ct6,td_ct7,...,counter_1,counter_2,counter_3,counter_4,counter_5,counter_6,counter_7,counter_8,counter_9,counter_10
0,858,384,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,384,976,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,976,930,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,930,634,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,634,223,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,128,690,0,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
2117,690,319,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2118,319,191,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
2119,191,619,0,0,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
2120,619,522,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [188]:
#065----- 予測列データを取得
df_new=pd.DataFrame({'Next_result': Num_3_2018_2026.loc[:, 'Next_result']})
df_new

      Next_result
0             384
1             976
2             930
3             634
4             223
...           ...
2116          690
2117          319
2118          191
2119          619
2120          522

[2121 rows x 1 columns]

In [189]:
#066----- 予測列を先にを削除
Num_3_2018_2026=Num_3_2018_2026.drop(columns=['Next_result'])
Num_3_2018_2026

,Lottery_result,td_ct0,td_ct1,td_ct2,td_ct3,td_ct4,td_ct5,td_ct6,td_ct7,td_ct8,...,counter_1,counter_2,counter_3,counter_4,counter_5,counter_6,counter_7,counter_8,counter_9,counter_10
0,858,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,384,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,976,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,930,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,634,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,128,0,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
2117,690,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2118,319,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
2119,191,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
2120,619,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [190]:
#067----- 元データとNext_resultを結合して右端へいれる
df = pd.concat([Num_3_2018_2026, df_new], axis=1)
df

,Lottery_result,td_ct0,td_ct1,td_ct2,td_ct3,td_ct4,td_ct5,td_ct6,td_ct7,td_ct8,...,counter_2,counter_3,counter_4,counter_5,counter_6,counter_7,counter_8,counter_9,counter_10,Next_result
0,858,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,384
1,384,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,976
2,976,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,930
3,930,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,634
4,634,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,223
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,128,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,690
2117,690,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,319
2118,319,0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,191
2119,191,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,619
2120,619,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,522

In [191]:
#068----- data type 確認
df.dtypes

Lottery_result    int32
td_ct0            int32
td_ct1            int32
td_ct2            int32
td_ct3            int32
                  ...
counter_7         int32
counter_8         int32
counter_9         int32
counter_10        int32
Next_result       int32
Length: 1128, dtype: object

In [192]:
#069----- ここまでのデータをcsvで出力、保管_ホルダー名前更新

#data_file='df_2018_2024.csv'
data_file='df_2018_2026.csv'
df.to_csv(os.path.join(challenge_5_data,data_file),index=False)

In [193]:
#ここまでがデータ準備でここから分析開始よ----dfにデータ格納

In [194]:
#001 説明変数と目的変数に分割_ここから繰り返し
X=df.iloc[:, :-1]
y=df.iloc[:, -1]

In [195]:
#002 data_check
print(X)

      Lottery_result  td_ct0  td_ct1  td_ct2  td_ct3  td_ct4  td_ct5  td_ct6  \
0                858       0       0       0       0       0       0       0
1                384       0       0       0       0       0       0       0
2                976       0       0       0       0       0       0       0
3                930       0       0       0       0       0       0       0
4                634       0       0       0       0       0       0       0
...              ...     ...     ...     ...     ...     ...     ...     ...
2116             128       0       0       0       0       0       0       1
2117             690       0       0       0       0       0       0       0
2118             319       0       0       0       0       0       0       0
2119             191       0       0       0       0       0       0       1
2120             619       0       0       0       0       0       0       0

      td_ct7  td_ct8  ...  counter_1  counter_2  counter_3  counter_4  \
0          0       0  ...          0          0          1          0
1          0       0  ...          0          1          0          0
2          0       0  ...          1          0          0          0
3          0       0  ...          0          0          0          0
4          0       0  ...          1          0          0          0
...      ...     ...  ...        ...        ...        ...        ...
2116       0       0  ...          0          0          1          0
2117       0       0  ...          1          0          0          0
2118       1       0  ...          0          0          0          0
2119       0       0  ...          0          1          0          0
2120       0       0  ...          0          0          1          0

      counter_5  counter_6  counter_7  counter_8  counter_9  counter_10
0             0          0          0          0          0           0
1             0          0          0          0          0           0
2             0          0          0          0          0           0
3             1          0          0          0          0           0
4             0          0          0          0          0           0
...         ...        ...        ...        ...        ...         ...
2116          0          0          0          0          0           0
2117          0          0          0          0          0           0
2118          1          0          0          0          0           0
2119          0          0          0          0          0           0
2120          0          0          0          0          0           0

[2121 rows x 1127 columns]

In [196]:
#003 data_check
print(y)

0       384
1       976
2       930
3       634
4       223
       ...
2116    690
2117    319
2118    191
2119    619
2120    522
Name: Next_result, Length: 2121, dtype: int32

In [197]:
#004 最終行数を取得
last_row = df.shape[0] - 1#最終行番号
print(last_row)

last_row1 = df.shape[0]#0～最終までの行数
print(last_row1)

2120
2121

In [198]:
#005 モデルの構築と検証---"1"に近いと良い
from sklearn.linear_model import LinearRegression # type: ignore
model=LinearRegression()
model.fit(X,y)
model.score(X,y)
#重回帰の場合50%(0.5)が精度の目安と言われている

0.42038042078737814

In [199]:
#006 学習
from sklearn.model_selection import train_test_split # type: ignore
# X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=20)#初期 size=0.4 state=1---state=20→30→40 "本では42推奨しているけどここで調整するところ"
#-----警告処置-----

#微調整が必要かなsize=0.2→0.25→0.3　random_state= は20が基本で30→40で調整---42---
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=0)
X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=20)
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=30)
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=42)

model.fit(X_train,y_train)
model.fit(X_test,y_test)

LinearRegression()

In [200]:
#007 検証---value test_size=0.2のとき---重回帰は"1"に近いと良い---マイナスになることもある。"-1"に近いのもOK---　webでは数値が高いほど学習効果あると研究段階ともある難しいみたいね-----
model.score(X_train,y_train)

# k = model.score(X_train,y_train)
# k = abs(k)
# print(k)

-0.8244925713617051

In [201]:
#008 予測-----先頭だけ確認してみる→20251011_最終行表示へ更新-----
import math
# x=x.iloc[0,:]
# y_pred=model.predict([x])[0]
# i=0 #先頭行
m=last_row #最終行
x=X.iloc[m,:] #予測する行番号-----#003で列数確認

#y_predを識別するためy_pred20とする20260316
y_pred20=model.predict([x])[0]
#y_pred=round(y_pred)

print(m,':',y_pred20)
print(m,':',math.ceil(y_pred20),':','切り上げ')#切り上げ
print(m,':',math.floor(y_pred20),':','切り捨て')#切り捨て
print(m,':',round(y_pred20),':','四捨五入')#四捨五入

#毎日ここで数値を確認してから

2120 : 574.0427095498007
2120 : 575 : 切り上げ
2120 : 574 : 切り捨て
2120 : 574 : 四捨五入

In [202]:
#009 先頭の25行くらいで予測値の補正が必要か分かるからやってみよう

for i in range(0,50):  #0～最終までの行数 25→50
    
    x=X.iloc[i,:] #予測する行番号-----#003で列数確認
    y_pred20=model.predict([x])[0]
    
    # y_pred=round(y_pred)#四捨五入
    y_pred20=math.floor(y_pred20)#切り下げ
    print(i,y_pred20)

0 508
1 422
2 622
3 482
4 509
5 738
6 422
7 407
8 573
9 916
10 496
11 56
12 562
13 92
14 521
15 699
16 279
17 530
18 440
19 651
20 252
21 516
22 758
23 586
24 599
25 797
26 710
27 640
28 263
29 757
30 298
31 352
32 321
33 103
34 202
35 347
36 716
37 1007
38 333
39 -50
40 776
41 210
42 1165
43 184
44 123
45 719
46 442
47 1123
48 675
49 261

In [203]:
#010 最終行から25行までをみれば補正が必要かわかる

#最終行番号確認　→　行数あると予測値Textコピペできないので個別に表示_20240816
k=last_row 
# print(k)

for k in range(k-50,k+1):  #0～最終までの行数 25→50
    
    x=X.iloc[k,:] #予測する行番号-----#003で列数確認
    y_pred20=model.predict([x])[0]
    
    # y_pred=round(y_pred)#四捨五入

    y_pred20=math.floor(y_pred20)#切り下げ
    print(k,y_pred20)

2070 478
2071 520
2072 79
2073 640
2074 952
2075 902
2076 476
2077 443
2078 869
2079 871
2080 -215
2081 460
2082 936
2083 248
2084 105
2085 261
2086 217
2087 999
2088 248
2089 842
2090 561
2091 72
2092 628
2093 883
2094 798
2095 432
2096 185
2097 534
2098 997
2099 748
2100 420
2101 122
2102 629
2103 515
2104 314
2105 567
2106 519
2107 313
2108 480
2109 1049
2110 703
2111 676
2112 670
2113 423
2114 1678
2115 617
2116 1073
2117 554
2118 524
2119 619
2120 574

In [204]:
#011 予測

i=last_row #最終行番号
x=X.iloc[i,:] #予測する行番号-----#004で列数確認
y_pred20=model.predict([x])[0]

# y_pred=round(y_pred) #四捨五入
y_pred20=math.floor(y_pred20)#切り下げ

print(i,':',y_pred20)

2120 : 574

In [205]:
#012 最終行番号確認　→　行数あると予測値Textコピペできないので個別に表示_20240816_
k=last_row 
print(k)

2120

In [206]:
#012 負の値と異常値のときの処理-----20251011_追加して経過を観察してみる-----
if -1000 < y_pred20 < 0:
    # y_pred_num1 = y_pred * 100 #100倍してから桁ごとの数値を取得
    y_pred20 = format(y_pred20, '04.0f') #format関数で4桁の文字列に変換（負の符号も含む）0F=小数点なし
    n1 = int(str(y_pred20)[-3]) #百の位
    n2 = int(str(y_pred20)[-2]) #十の位
    n3 = int(str(y_pred20)[-1]) #一の位

    print(i,':',n1,n2,n3,':','負の値を補正',y_pred20)

elif y_pred20 > 999:
    n1 = int(str(y_pred20)[-3]) #百の位
    n2 = int(str(y_pred20)[-2]) #十の位
    n3 = int(str(y_pred20)[-1]) #一の位

    print(i,':',n1,n2,n3,':','異常値を補正',y_pred20)

elif y_pred20 < -999:
    print(i,':','負の異常値',y_pred20)    

else:
    print(i,':',y_pred20,':','正常値です')

2120 : 574 : 正常値です

In [207]:
#ここまでで予測はできることを確認20230922
#Next_resultで予測できたけど精度が低いので補正方法を調べる
#ダミー変数を追加していく

In [208]:
#-----簡単に作業できるかまとめてみた-----

In [209]:
#一回で全部みてみましょう

In [210]:
#001 説明変数と目的変数に分割-----まとめて出力できないか-----
X=df.iloc[:, :-1]
y=df.iloc[:, -1]

#モデルの構築と検証---"1"に近いと良い
from sklearn.linear_model import LinearRegression # type: ignore
model=LinearRegression()
model.fit(X,y)
# model.score(x,y)

#学習
from sklearn.model_selection import train_test_split # type: ignore
# X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=20)#初期 size=0.4 state=1→20→30→40 "本では42推奨しているけどここで調整するところ"
#-----警告処置-----

#微調整が必要かなsize=0.2→0.25→0.3 random_state= は20が基本で30→40で調整　---42---
X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=0)
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=20)
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=30)
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=42)


model.fit(X_train,y_train)
model.fit(X_test,y_test)

LinearRegression()

In [211]:
#002 検証---value test_size=0.2のとき---重回帰は"1"に近いと良い---マイナスになることもある。"-1"に近いのもOK---　webでは数値が高いほど学習効果あると研究段階ともある難しいみたいね-----
model.score(X_train,y_train)

# k = model.score(X_train,y_train)
# k = abs(k)
# print(k)

-1.2994439439783494

In [212]:
#003 先頭の25行くらいで予測値の補正が必要か分かるからやってみよう

for i in range(0,50):  #0～最終までの行数 25→50
    
    x=X.iloc[i,:] #予測する行番号-----#003で列数確認

    #y_predを識別するためy_pred00とする20260316
    y_pred00=model.predict([x])[0]
   
    # y_pred=round(y_pred) #四捨五入
    y_pred00=math.floor(y_pred00)#切り下げ

    print(i,y_pred00)

0 793
1 976
2 389
3 419
4 915
5 244
6 880
7 458
8 856
9 867
10 812
11 716
12 313
13 616
14 282
15 481
16 481
17 236
18 436
19 459
20 904
21 668
22 324
23 250
24 -48
25 563
26 683
27 876
28 886
29 673
30 755
31 949
32 71
33 202
34 320
35 809
36 392
37 349
38 626
39 673
40 796
41 837
42 574
43 1187
44 373
45 328
46 821
47 243
48 427
49 436

In [213]:
#004 最終行から25行までをみれば補正が必要かわかる

#最終行番号確認　→　行数あると予測値Textコピペできないので個別に表示_20240816_
k=last_row 
# print(k)

for k in range(k-50,k+1):  #0～最終までの行数 25→50
    
    x=X.iloc[k,:] #予測する行番号-----#003で列数確認
    y_pred00=model.predict([x])[0]
   
    # y_pred=round(y_pred) #四捨五入
    y_pred00=math.floor(y_pred00)#切り下げ

    print(k,y_pred00)

2070 563
2071 425
2072 -140
2073 703
2074 931
2075 426
2076 246
2077 443
2078 751
2079 841
2080 -166
2081 381
2082 412
2083 385
2084 104
2085 159
2086 573
2087 387
2088 385
2089 292
2090 736
2091 343
2092 501
2093 801
2094 -212
2095 378
2096 135
2097 451
2098 860
2099 637
2100 862
2101 283
2102 681
2103 746
2104 286
2105 971
2106 448
2107 548
2108 353
2109 917
2110 540
2111 745
2112 1434
2113 872
2114 1083
2115 1047
2116 689
2117 766
2118 502
2119 423
2120 880

In [214]:
#005 予測

i=last_row #最終行番号
x=X.iloc[i,:] #予測する行番号-----#004で列数確認

y_pred00=model.predict([x])[0]

# y_pred=round(y_pred) #四捨五入
y_pred00=math.floor(y_pred00)#切り下げ

print(i,':',y_pred00)

2120 : 880

In [215]:
#006 負の値と異常値のときの処理-----20251011_追加して経過を観察してみる-----
if -1000 < y_pred00 < 0:
    # y_pred_num1 = y_pred * 100 #100倍してから桁ごとの数値を取得
    y_pred00 = format(y_pred00, '04.0f') #format関数で4桁の文字列に変換（負の符号も含む）
    n1 = int(str(y_pred00)[-3]) #百の位
    n2 = int(str(y_pred00)[-2]) #十の位
    n3 = int(str(y_pred00)[-1]) #一の位

    print(i,':',n1,n2,n3,':','負の値を補正',y_pred00)

elif y_pred00 > 999:
    n1 = int(str(y_pred00)[-3]) #百の位
    n2 = int(str(y_pred00)[-2]) #十の位
    n3 = int(str(y_pred00)[-1]) #一の位

    print(i,':',n1,n2,n3,':','異常値を補正',y_pred00)

elif y_pred00 < -999:
    print(i,':','負の異常値',y_pred00)    

else:
    print(i,':',y_pred00,':','正常値です')

2120 : 880 : 正常値です

In [216]:
#001 説明変数と目的変数に分割-----まとめて出力できないか-----
X=df.iloc[:, :-1]
y=df.iloc[:, -1]

#モデルの構築と検証---"1"に近いと良い
from sklearn.linear_model import LinearRegression # type: ignore
model=LinearRegression()
model.fit(X,y)
# model.score(x,y)

#学習
from sklearn.model_selection import train_test_split # type: ignore
# X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=20)#初期 size=0.4 state=1→20→30→40 "本では42推奨しているけどここで調整するところ"
#-----警告処置-----

#微調整が必要かなsize=0.2→0.25→0.3 random_state= は20が基本で30→40で調整　---42---
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=0)
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=20)
X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=30)
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=42)


model.fit(X_train,y_train)
model.fit(X_test,y_test)

LinearRegression()

In [217]:
#002 検証---value test_size=0.2のとき---重回帰は"1"に近いと良い---マイナスになることもある。"-1"に近いのもOK---　webでは数値が高いほど学習効果あると研究段階ともある難しいみたいね-----
model.score(X_train,y_train)

# k = model.score(X_train,y_train)
# k = abs(k)
# print(k)

-1.443748859079407

In [218]:
#003 先頭の25行くらいで予測値の補正が必要か分かるからやってみよう

for i in range(0,50):  #0～最終までの行数 25→50
    
    x=X.iloc[i,:] #予測する行番号-----#003で列数確認
    
    #y_predを識別するためy_pred30とする20260316
    y_pred30=model.predict([x])[0]
    
    # y_pred=round(y_pred) #四捨五入
    y_pred30=math.floor(y_pred30)#切り下げ

    print(i,y_pred30)

0 879
1 63
2 148
3 579
4 113
5 536
6 716
7 368
8 32
9 931
10 1273
11 148
12 327
13 57
14 838
15 901
16 261
17 472
18 467
19 484
20 314
21 461
22 229
23 35
24 -279
25 253
26 721
27 537
28 1009
29 125
30 655
31 949
32 -395
33 488
34 491
35 139
36 232
37 86
38 55
39 382
40 296
41 216
42 391
43 210
44 474
45 -14
46 273
47 38
48 441
49 334

In [219]:
#004 最終行から25行までをみれば補正が必要かわかる

#最終行番号確認　→　行数あると予測値Textコピペできないので個別に表示_20240816_
k=last_row 
# print(k)

for k in range(k-50,k+1):  #0～最終までの行数 25→50
    
    x=X.iloc[k,:] #予測する行番号-----#003で列数確認
    y_pred30=model.predict([x])[0]

    # y_pred=round(y_pred) #四捨五入
    y_pred30=math.floor(y_pred30)#切り下げ

    print(k,y_pred30)

2070 263
2071 345
2072 596
2073 589
2074 932
2075 722
2076 -24
2077 687
2078 382
2079 304
2080 584
2081 701
2082 537
2083 36
2084 632
2085 159
2086 403
2087 519
2088 36
2089 776
2090 860
2091 625
2092 775
2093 564
2094 269
2095 651
2096 435
2097 394
2098 704
2099 692
2100 60
2101 909
2102 1074
2103 687
2104 765
2105 825
2106 430
2107 497
2108 412
2109 703
2110 603
2111 740
2112 645
2113 423
2114 833
2115 1112
2116 549
2117 572
2118 1044
2119 433
2120 564

In [220]:
#005 予測

i=last_row #最終行番号
x=X.iloc[i,:] #予測する行番号-----#004で列数確認
y_pred30=model.predict([x])[0]

# y_pred30=round(y_pred30) #四捨五入
y_pred30=math.floor(y_pred30)#切り下げ

print(i,':',y_pred30)

2120 : 564

In [221]:
#006 負の値と異常値のときの処理-----20251011_追加して経過を観察してみる-----
if -1000 < y_pred30 < 0:
    # y_pred_num1 = y_pred30 * 100 #100倍してから桁ごとの数値を取得
    y_pred30 = format(y_pred30, '04.0f') #format関数で4桁の文字列に変換（負の符号も含む）
    n1 = int(str(y_pred30)[-3]) #百の位
    n2 = int(str(y_pred30)[-2]) #十の位
    n3 = int(str(y_pred30)[-1]) #一の位
    
    print(i,':',n1,n2,n3,':','負の値を補正',y_pred30)
    # print('formatted_result :',formatted_result)

elif y_pred30 > 999:
    n1 = int(str(y_pred30)[-3]) #百の位
    n2 = int(str(y_pred30)[-2]) #十の位
    n3 = int(str(y_pred30)[-1]) #一の位

    print(i,':',n1,n2,n3,':','異常値を補正',y_pred30)

elif y_pred30 < -999:
    print(i,':','負の異常値',y_pred30)

else:
    print(i,':',y_pred30,':','正常値です')

2120 : 564 : 正常値です

In [222]:
#001 説明変数と目的変数に分割-----まとめて出力できないか-----
X=df.iloc[:, :-1]
y=df.iloc[:, -1]

#モデルの構築と検証---"1"に近いと良い
from sklearn.linear_model import LinearRegression # type: ignore
model=LinearRegression()
model.fit(X,y)
# model.score(x,y)

#学習
from sklearn.model_selection import train_test_split # type: ignore
# X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=20)#初期 size=0.4 state=1→20→30→40 "本では42推奨しているけどここで調整するところ"
#-----警告処置-----

#微調整が必要かなsize=0.2→0.25→0.3 random_state= は20が基本で30→40で調整　---42---
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=0)
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=20)
# X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=30)
X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.2,random_state=42)


model.fit(X_train,y_train)
model.fit(X_test,y_test)

LinearRegression()

In [223]:
#002 検証---value test_size=0.2のとき---重回帰は"1"に近いと良い---マイナスになることもある。"-1"に近いのもOK---　webでは数値が高いほど学習効果あると研究段階ともある難しいみたいね-----
model.score(X_train,y_train)

# k = model.score(X_train,y_train)
# k = abs(k)
# print(k)

-1.5305868195603973

In [224]:
#003 先頭の25行くらいで予測値の補正が必要か分かるからやってみよう

for i in range(0,50):  #0～最終までの行数 25→50
    
    x=X.iloc[i,:] #予測する行番号-----#003で列数確認

    #y_predを識別するためy_pred42とする20260316
    y_pred42=model.predict([x])[0]
    
    # y_pred=round(y_pred) #四捨五入
    y_pred42=math.floor(y_pred42)#切り下げ

    print(i,y_pred42)

0 467
1 120
2 788
3 1377
4 140
5 805
6 1305
7 368
8 130
9 -341
10 756
11 791
12 1105
13 92
14 862
15 439
16 1521
17 648
18 692
19 336
20 388
21 710
22 704
23 137
24 443
25 936
26 -16
27 713
28 784
29 631
30 517
31 414
32 270
33 566
34 139
35 814
36 1037
37 1025
38 248
39 -267
40 662
41 611
42 792
43 567
44 587
45 1324
46 294
47 999
48 655
49 236

In [225]:
#004 最終行から25行までをみれば補正が必要かわかる

#最終行番号確認　→　行数あると予測値Textコピペできないので個別に表示_20240816_
k=last_row 
# print(k)

for k in range(k-50,k+1):  #0～最終までの行数 25→50
    
    x=X.iloc[k,:] #予測する行番号-----#003で列数確認
    y_pred42=model.predict([x])[0]
    
    # y_pred=round(y_pred) #四捨五入
    y_pred42=math.floor(y_pred42)#切り下げ

    print(k,y_pred42)

2070 864
2071 542
2072 252
2073 1407
2074 931
2075 1549
2076 634
2077 1256
2078 643
2079 526
2080 987
2081 1057
2082 1350
2083 770
2084 777
2085 904
2086 469
2087 968
2088 770
2089 750
2090 1091
2091 577
2092 493
2093 876
2094 915
2095 973
2096 1313
2097 508
2098 1475
2099 268
2100 1665
2101 680
2102 426
2103 131
2104 806
2105 778
2106 784
2107 1538
2108 850
2109 1862
2110 540
2111 806
2112 473
2113 422
2114 1222
2115 718
2116 420
2117 549
2118 769
2119 784
2120 424

In [226]:
#005 予測

i=last_row #最終行番号
x=X.iloc[i,:] #予測する行番号-----#004で列数確認
y_pred42=model.predict([x])[0]

# y_pred=round(y_pred) #四捨五入
y_pred42=math.floor(y_pred42)#切り下げ

print(i,':',y_pred42)

2120 : 424

In [227]:
#006 負の値と異常値のときの処理-----20251011_追加して経過を観察してみる-----
if -1000 < y_pred42 < 0:
    # y_pred_num1 = y_pred42 * 100 #100倍してから桁ごとの数値を取得
    y_pred42 = format(y_pred42, '04.0f') #format関数で4桁の文字列に変換（負の符号も含む）
    n1 = int(str(y_pred42)[-3]) #百の位
    n2 = int(str(y_pred42)[-2]) #十の位
    n3 = int(str(y_pred42)[-1]) #一の位

    print(i,':',n1,n2,n3,':','負の値を補正',y_pred42)

elif y_pred42 > 999:
    n1 = int(str(y_pred42)[-3]) #百の位
    n2 = int(str(y_pred42)[-2]) #十の位
    n3 = int(str(y_pred42)[-1]) #一の位

    print(i,':',n1,n2,n3,':','異常値を補正',y_pred42)

elif y_pred42 < -999:
    print(i,':','負の異常値',y_pred42)

else:
    print(i,':',y_pred42,':','正常値です')

2120 : 424 : 正常値です

In [228]:
#ここでおわり

In [229]:
#ここで並べて確認して購入判定しようかな_20260316_
print('00:',y_pred00, ',', '20:',y_pred20, ',', '30:',y_pred30, ',', '42:',y_pred42)

#-----購入判定の条件-----
# y_pred00が1000未満で0以上
# y_pred30が2000未満で-1000より大きい
# y_pred42が1000未満で-1000より大きい

#int型に変換してから判定_20260324_
y_pred00=int(y_pred00)
y_pred20=int(y_pred20)
y_pred30=int(y_pred30)
y_pred42=int(y_pred42)

if 1000>y_pred00>=0 and 2000>y_pred30>-1000 and 1000>y_pred42>-1000:
    print('購入判定：購入')
else:
    print('購入判定：見送り')

00: 880 , 20: 574 , 30: 564 , 42: 424
購入判定：購入

In [230]:
#学習ルールを考えた-----2024/8/16-----
#1_全体の予測(Num_3_challenge_6.jpynb)はPC負担軽減のため今後中止にする。2024/8/16～
#2_random_state=(20)で揃える。予測値が異常なときは(42)で行う。
#3_#007 検証のとき、出力値が"1"に近いとよい。#2の(20)で異常値のときはここも異常値である。(42)のときで比較して判断する。

In [231]:
# #逆換算__エラーでるのでキャンセルする
# result=model.score(x_train,y_train)
# model.inverse_transform(model.predict(result))

In [232]:
#全体をcheckすると学習時間が長いのでNum_3_challenge_6で行う　→　PC負担大きいため中止

In [233]:
# #000 ここから回帰分析開始して時間短縮-----20231001-----
# import os
# import pandas as pd
# import numpy as np
# from sklearn.preprocessing import OneHotEncoder

# #docker のときは/workdir/ を追記する
# New_data_dir='/workdir/Num_3_predict/01_output/challenge_5'

# import glob
# Num_3_file=os.path.join(New_data_dir,'/workdir/Num_3_predict/01_output/challenge_5/df_2018_2023.csv')
# Num_3_paths=glob.glob(Num_3_file)
# display(Num_3_paths)

In [234]:
# #001 csv_data 呼び出して確認
# New_data_dir='/workdir/Num_3_predict/01_output/challenge_5'
# Num_3_predict_dir=os.path.join(New_data_dir)
# Num_3_file='df_2018_2023.csv' #西暦ごとに出力 + #005欠損値も確認
# df=pd.read_csv(os.path.join(Num_3_predict_dir,Num_3_file))
# display(df)

In [235]:
# #002 説明変数と目的変数に分割-----まとめて出力できないか-----

# for i in range(0,1484): #スタートが0からで1つめ2つめ3つめ、ひとつの数値でもOK、rows行番号でOk
# # for i in range(1482,1483):    
    
#     X=df.iloc[:, :-1]
#     y=df.iloc[:, -1]

#     #モデルの構築と検証---"1"に近いと良い
#     from sklearn.linear_model import LinearRegression
#     model=LinearRegression()
#     model.fit(X,y)
#     # model.score(x,y)

#     #学習
#     from sklearn.model_selection import train_test_split
#     # X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=20)#初期 size=0.4 state=1
#     #-----警告処置-----
#     X_train,X_test,y_train,y_test=train_test_split(X.values,y,test_size=0.25,random_state=20)#初期 size=0.4 state=1　#微調整が必要かなsize=0.2→0.25→0.3
#     model.fit(X_train,y_train)
#     model.fit(X_test,y_test)


#     x=X.iloc[i,:] #予測する行番号-----#003で列数確認
#     y_pred=model.predict([x])[0]
#     # y_pred

#     y_pred=round(y_pred)
#     print(i,y_pred)



#     #予測値と比較
#     # from sklearn.metrics import mean_squared_error
#     # y=y.iloc[i,:]
#     # score=mean_squared_error(y_pred,y)
#     # print(score) 



#     #100個で8分
#     #1000個で95分
#     #1482個で133分、211分

# #-----警告処置-----

In [236]:
# #003 完全一致率を算出----これで楽になるね
# import pandas as pd
# import numpy as np
# from sklearn.metrics import mean_squared_error

# count=0
# score=0
# num=0

# for i in range(0,1484): #スタートが0からで1つめ2つめ3つめ、rows行番号
    
#     y=df.iloc[i, -1]
#     x=X.iloc[i,:] #予測する行番号-----#003で列数確認
#     y_pred=model.predict([x])[0]
#     y_pred=round(y_pred)
#     y_pred

#     if y == y_pred:
#         score += 1
    
#         num = str(i)
#     if num != '':
#         count += 1
       
#     # print(y,y_pred,num)
# print('Total', score, count)

# if count >= score:
#     print(f'Perfect_matching = {score}/{count} ({score/count *100:.1f}%)')